### PR TITLE
Bump Version to 2.2.0-dev

### PR DESCRIPTION
**Pull request by adrianduffell**
Bumps versions to `2.2.0-dev` now that the 2.1 branch has been cut.

No changelog is needed

### Testing Instructions

- Navigate to WooCommerce -> Status
- Ensure a value of `2.2.0-dev` for WooCommerce Admin package. 

Screen Shot 2021-02-26 at 7 26 59 am

### CODE REVIEW

**Review by psealock — APPROVED** [review]
Nice, thanks for this! Just checking, did you use the `npm run bump-version` script?

**Comment by adrianduffell** [comment]
> Just checking, did you use the npm run bump-version script?

Oh, nope I didn't know about the script and did this by hand.

I'll revert it and use the script just in case I missed something.

**Comment by adrianduffell** [comment]
@psealock I've rebuilt the PR using `npm run bump-version`. Thanks for checking whether the script was used 🙂 

Could you please take another look?

**Comment by adrianduffell** [comment]
In 591780a I moved some recent PRs out of the 2.1.0 changelog. I think some in-flight PRs will also land there instead of in Unreleased. I'll keep an eye on it.

**Review by mattsherman — APPROVED** [review]
@adrianduffell Any specific test instructions for this, or is is just a confidence check?

Things look okay to me -- pre-approving, so that you can merge this after addressing:
- the conflict in`readme.txt`
- add a "no changelog" to this description, so the changelog check is happy

**Comment by adrianduffell** [comment]
@mattsherman Thanks for pointing out the testing instructions. I've added those to the PR description now.

All items are now addressed so I'll merge this 🙂

**Pull request merged**
