### PR TITLE
Fix a number of crashes that occur in reports when Gutenberg is active

### LINKED ISSUE #5385: WooCommerce 4.6 Analytics Overview page breaks with Gutenberg plugin active
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
With the WooCommerce plugin updated to 4.6, the  Analytics Overview page is now blank and gives quite a few errors in the console. I noticed this occurs only when the Gutenberg (9.1.1) plugin is active. Deactivating the plugin fixes the issue and I can replicate this on multiple sites.

**Expected behavior**
Opening up the Analytics Overview page should display recent WooCommerce stats

**Actual behavior**
When Gutenberg plugin is active, the page is blank and has many console errors

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. On a site with WooCommerce 4.6 active as we'll as with Gutenberg plugin active(9.1.10)...
2. Click on WP-Admin ➤ Analytics ➤ Overview
3. The page loads blank.

**Screenshots**
Screen Shot 2020-10-14 at 12 48 29 PM

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://ksecommercetest.blog
Site address (URL): https://ksecommercetest.blog
WC Version: 4.6.0
REST API Version: ✔ 4.6.0
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.1
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.23
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.72.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
Total Database Size: 5.67MB
Database Data Size: 4.15MB
Database Index Size: 1.52MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 8
custom_css: 1
jetpack_migration: 2
nav_menu_item: 2
page: 7
post: 3
product: 18
product_variation: 7
revision: 4
wc_whsm: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Akismet Anti-Spam: by Automattic – 4.1.6
AMP: by AMP Project Contributors – 2.0.4
Facebook for WooCommerce: by Facebook – 2.0.5 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Force Default Variant: by HappyKite – 1.5.2 – Installed version not tested with active version of WooCommerce 4.6.0
Gutenberg: by Gutenberg Team – 9.1.1
Hide Shipping Method For WooCommerce: by theDotstore – 1.0.3 – Installed version not tested with active version of WooCommerce 4.6.0
Jetpack by WordPress.com: by Automattic – 9.0.2
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.6.0
Storefront Powerpack: by WooCommerce – 2.0.0
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.2.3 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.0 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.3 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Product Add-ons: by WooCommerce – 3.1.0 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Shipping & Tax: by Automattic – 1.25.0 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce UPS Shipping: by WooCommerce – 3.2.29 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.48 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce: by Automattic – 4.6.0
WordPress Importer: by wordpressdotorg – 0.7

### Inactive Plugins (13) ###

Classic Editor: by WordPress Contributors – 1.6
CoBlocks: by GoDaddy – 2.4.0
Klarna Checkout for WooCommerce: by Krokedil – 2.3.1 – Installed version not tested with active version of WooCommerce 4.6.0
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.1.3 – Installed version not tested with active version of WooCommerce 4.6.0

Layout Grid: by Automattic – 1.3
Page Optimize: by Automattic – 0.5.1
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.27 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.19 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.1.24 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce PayFast Gateway: by WooCommerce – 1.4.15 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Royal Mail: by WooCommerce – 2.5.31 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Square: by WooCommerce – 2.2.2 – Installed version not tested with active version of WooCommerce 4.6.0
WordPress.com Editing Toolkit: by Automattic – 2.7

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: woocommerce/woocommerce#6 - /shop/
Cart: woocommerce/woocommerce#7 - /cart/
Checkout: woocommerce/woocommerce#8 - /checkout/
My account: woocommerce/woocommerce#9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.8.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 9
Oldest: 2020-09-16 18:08:45 +0000
Newest: 2020-10-14 19:37:12 +0000

Pending: 1
Oldest: 2020-10-21 18:15:13 +0000
Newest: 2020-10-21 18:15:13 +0000

`
```
</details>

### PR DESCRIPTION
**Pull request by samueljseay**
Fixes #5385 Also note that on `main` there were other crashes happening
on all the report pages.

It seems there are some behaviour changes in how data is resolved
due to some recent updates to Gutenberg. I was not able to find
out why these happen but there were a lot of situations where
reports did not handle empty data well.

This adds more defensive code where the objects being drilled
into could have null or undefined properties.

### Detailed test instructions:

- Setup an environment woocommerce and this branch of wc-admin installed
- Install the gutenberg plugin
- Visit all the submenus of the `Analytics` section
- Confirm they do not crash

**Note:** this does not remove the warnings that will show as errors in console in development. Some new ones do appear as a result of Gutenberg being installed but there were existing ones too. I will raise a separate issue to fix all of these.

### Changelog Note:

Fix: a bug where reports crashed when Gutenberg was installed

### CODE REVIEW

**Comment by becdetat** [comment]
I’ve got Gutenberg and WooCommerce from the plugin directory and I uploaded a test zip from  your branch (`npm run test:zip`). When I go to the analytics page I still get a blank page, but there are no errors or warnings apart from the usual source map warning. Am I testing this correctly?

**Comment by octaedro** [comment]
>I’ve got Gutenberg and WooCommerce from the plugin directory and I uploaded a test zip from your branch (npm run test:zip). When I go to the analytics page I still get a blank page, but there are no errors or warnings apart from the usual source map warning. Am I testing this correctly?

I'm experiencing the same error (blank page). Here it's my [console log](https://github.com/woocommerce/woocommerce-admin/files/5393268/error.log) 😕

**Review by timmyc — COMMENTED** [review]
Adding in my test case that I did with this branch, though need to re-test with the new changes. Done on a live Atomic site.

- Added :gutenberg: 9.1.1, running Woo 4.6, no wc-admin plugin
- Verified Stats Overview and Customers Report were not working
- Uploaded zip built from the 5409 branch, activated
- Stats Overview and Customers Report are rendering fine now

**Review by octaedro — APPROVED** [review]
Great job @samueljseay! Now everything is testing well in JN. Code looks good 🚀

**Comment by timmyc** [comment]
cherry picked to `release/1.6.2` in https://github.com/woocommerce/woocommerce-admin/commit/829bdefb50f085ddbf734c9cc2dfce102521ba96

**Pull request merged**
