### PR TITLE
Fix industry args type in REST API

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes a `type` argument error that causes failing tests in WP 5.5.0.

WP 5.5 introduced a number of deprecated properties in the REST API.  ( See https://github.com/WordPress/WordPress/blame/master/wp-includes/rest-api.php ).  One of these requires a valid `type` property.

### Detailed test instructions:

1. Make sure tests pass.
1. Navigate to the profiler.
1. Make sure industry data can be updated still and persists across refresh.

### CODE REVIEW

**Review by jeffstieler — APPROVED** [review]
I approve your changes @joshuatf.

**Comment by joshuatf** [comment]
Thanks for the review and your fixes to this, @jeffstieler.  Your changes here look good as well and all tests are ✅

**Comment by timmyc** [comment]
Cherry picked to `release/1.4.0` in 5427b8a73d79bacafaaa8a1e1065b614dc06e20d

**Comment by becdetat** [comment]
Cherry picked to `release/1.5.0-beta.1` in 2b24747fe7c6fdb26f608031b3d44a8d52a6bd7b

**Pull request merged**
