### PR TITLE
Add/testing instructions

### PR DESCRIPTION
**Pull request by becdetat**
This adds a file for including test instructions for our PRs, to make it easier to pass them along to the testers.

### CODE REVIEW

**Comment by psealock** [comment]
Awesome! Should it be the responsibilty of PR authors to add to this file? If so, we can change the pull request template to reflect that

**Review by ilyasfoo — COMMENTED** [review]
I agree with @psealock, let's add to the PR instructions

**Review by ilyasfoo — APPROVED** [review]
LGTM!

**Comment by becdetat** [comment]
Thanks @psealock and @ilyasfoo , I've added to the PR template

**Review by psealock — APPROVED** [review]
Love the changes here

**Pull request merged**
