### PR TITLE
Update payment card style on mobile

### LINKED ISSUE #6393: In mobile view, the description of each payment option is pushed all the way to the left
**Describe the bug**
When you view the payment options in the 'Set up payments' page in mobile portrait view, you would notice that all the text descriptions are pushed all the way to the left of the screen, looking like they have 0px left margin or padding.

**To Reproduce**

1. Using a mobile device in portrait mode, go to 'Home'
2. Click on 'Set up payments'
3. Notice that all the text descriptions are pushed to the left, already touching the left edge of the screen.

**Expected behavior**
The descriptions should have a comfortable left margin or padding.

**Screenshots**
mobile - payment option contents have no left margin or padding

**Smartphone:**

* Device: Samsung Galaxy Note9
* OS: Android v10
* Browser: Firefox
* Version: 85.1.3

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #6393 

Update payment card style on mobile

### Screenshots
Before
before

After
after

### Detailed test instructions:

-   Go to your WooCommerce -> Home -> Choose payment methods.
-   See that card style render as expected.

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
This tests well and looks much better, thanks @hsingyuc! 

We have a new workflow for PRs to commit the testing instructions with the change. This will ensure your work will be tested again when the next beta is released.

Could you please add some steps under **Unreleased** in [TESTING-INSTRUCTIONS.md](https://github.com/woocommerce/woocommerce-admin/blob/main/TESTING-INSTRUCTIONS.md)? You can use the same format from previous releases.

I would also just change the instructions slightly:

```
- Using a small size screen, go to your WooCommerce -> Home -> Choose payment methods.
- See that the text descriptions for payment methods have a margin between them and the edge of the screen.
```

This will be ready to merge once the instructions are in place 🚀

**Comment by hsingyuc** [comment]
@adrianduffell  Thank you for letting me know! It's done.

**Comment by adrianduffell** [comment]
@hsingyuc Thanks for putting those in place!

I fixed a new conflict and merging this now 👍

**Comment by hsingyuc** [comment]
@adrianduffell  Thank you!!

**Pull request merged**
