### PR TITLE
Add required dependencies for pnpm nx build {package} command

### LINKED ISSUE #8433: Make packages work with pnpm nx install {package}
### Describe the bug

Running `pnpm nx install {package}` in The Merge environment fails due to missing dependencies. 

As a part of The Merge, packages in `/packages` should be installable with `pnpm nx install {package}` command.

### To Reproduce

1. Refer to Refer to `archives/C01SFMVEYAK/p1646777260567079?thread_ts=1646772045.138809&cid=C01SFMVEYAK` slack thread to setup The Merge environment
2. Run `pnpm nx build {package}`

### How to fix it?

Running the command should give you error messages with missing dependencies. We can simply add those missing dependencies to the packages.

For example, adding the following packages fixed `pnpm nx install @woocommerce/components` 

```
"css-loader": "^3.6.0",
"postcss-loader": "^3.0.0",
"sass-loader": "^10.2.1",
"webpack": "^4.46.0"
```

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #8433 

This PR adds required dependencies for the packages in `/packages` to make them work with `pnpm nx build {package}` in The Merge environment. 

- Also changed some imports in `@woocommerce/components` to the relative path to run the `test` command independently.

### Detailed test instructions:

1. Refer to `archives/C01SFMVEYAK/p1646777260567079?thread_ts=1646772045.138809&cid=C01SFMVEYAK` slack thread to setup The Merge environment. (You might need to run `brew install git-filter-repo` if you don't have `git-filter-repo` in your local.)
2. Once you have The Merge environment,  run `pnpm run clean && rm -r packages/**/node_modules` in WCA repo and copy `packages/*` from this branch to `packages/js/` in The Merge. 
3. Run `pnpm install` in The Merge.
4. Run the following commands in The Merge and confirm the commands work without an error.

```bash
pnpm nx run-many --target=build --all --exclude=@woocommerce/api,@woocommerce/api-core-tests,@woocommerce/e2e-core-tests,@woocommerce/e2e-environment,@woocommerce/e2e-utils,woocommerce,woocommerce-legacy-assets,@woocommerce/dependency-extraction-webpack-plugin
```

Copy the `config/development.json` from WCA to `packages/config/development.json` in the Merge.

```bash
pnpm nx run-many --target=test --all --exclude=@woocommerce/api,@woocommerce/api-core-tests,@woocommerce/e2e-core-tests,@woocommerce/e2e-environment,@woocommerce/e2e-utils,woocommerce,woocommerce-legacy-assets,@woocommerce/dependency-extraction-webpack-plugin,@woocommerce/admin-e2e-tests,@woocommerce/onboarding,@woocommerce/js-tests, @woocommerce/notices,@woocommerce/tracks
```

no changelog

### CODE REVIEW

**Comment by chihsuan** [comment]
@rjchow and I found that `test` command doesn't work with the `nx` environment. It somehow uses `jest@25.x.x` but not `jest@27`.

```
> pnpm nx test @woocommerce/data
....
TypeError: Jest: a transform must export a `process` function.`
```

However, if we can run the tests with the following commands:

```bash
cd packages/js/components
/node_modules/.bin/jest --config jest.config.json src

or 

pnpm run test --filter ./packages/js/components/ 

or

rm -r node_modules/.pnpm/jest-cli@25.5.4
pnpm nx run-many --target=test --all --exclude=@woocommerce/api,@woocommerce/api-core-tests,@woocommerce/e2e-core-tests,@woocommerce/e2e-environment,@woocommerce/e2e-utils,woocommerce,woocommerce-legacy-assets,@woocommerce/dependency-extraction-webpack-plugin,@woocommerce/admin-e2e-tests,@woocommerce/onboarding,@woocommerce/js-tests, @woocommerce/notices,@woocommerce/tracks
```



I think it's because jest uses the [`import-local`](https://www.npmjs.com/package/import-local) to import the CLI. 

Currently, I think this issue is beyond the scope of this PR. We might need to upgrade the jest in woo core or set up `nx` executors.

**Comment by chihsuan** [comment]
I just found that we should add `jest-cli` to devDependencies as well. We can run `pnpm nx test {package}` now.

**Comment by rjchow** [comment]
Yup confirmed that the pnpm test command given in the PR description works now! Thanks for figuring that out @chihsuan, that was a real head scratcher. I did notice that the tsc output has gone missing, though - haven't looked into it, not sure if it'll be a trivial fix, but if it isn't we can fix it in a follow up issue after the merge.

There's just that one workflow that's failing in CI (Run PHP unit tests / test-php (7.0, 5.6, latest, 6.5.9, 1.10.19) (pull_request)). I've tried re-running it but it still seems to fail and no one's talking about it - is it expected?

**Comment by chihsuan** [comment]
> There's just that one workflow that's failing in CI (Run PHP unit tests / test-php (7.0, 5.6, latest, 6.5.9, 1.10.19) (pull_request)). I've tried re-running it but it still seems to fail and no one's talking about it - is it expected?

@rjchow Yea, I've filed [an issue here](https://github.com/woocommerce/woocommerce-admin/issues/8439). I think this might be due to the new release wooCommerce since the other test-php workflows still passed the test.

**Review by rjchow — APPROVED** [review]
Cool, thanks!

**Pull request merged**
