### PR TITLE
Add cache-control header to low stock response

### PR DESCRIPTION
**Pull request by adrianduffell**
Fixes (partially) #7358

A performance issue is introduced in WooCommerce 5.5, where the combination of slow SQL query made multiple times via REST API request is impacting server load.

This PR mitigates the issue by adding a cache header to the response, directing clients to cache the response for 60 seconds. This has the effect of reducing the amount of times the slow SQL query is made.

This is intended as a temporary measure until a permanent solution is found.

### Questions

Is 60 seconds a good max age value? Should it be increased?

### Alternative approach

I considered caching the response server-side using WordPress transients. However I didn't feel comfortable I could create unique key names given all the different combination of parameters available in the REST API.  

### Detailed test instructions:

- Ideally, add 1000+ products to the site using WC Smooth Generator. 

- Open the browser console and filter XHR requests by `low_in_stock`

Screen Shot 2021-07-16 at 8 32 39 pm

- Wait 60 seconds.
- Visit the WooCommerce homepage.
- See that the `/wc-analytics/products` request, with parameter of `low_in_stock=true` is fetched. If the site has enough products, this should be marked as a slow query as well. There’s a turtle in Firefox for example 🐢 

Screen Shot 2021-07-16 at 8 19 17 pm

- Within 60 seconds, browse to another WC Admin screen.
- See that the next request is retrieved from cache.

Screen Shot 2021-07-16 at 8 19 23 pm

- Continue to browse other WC Admin screens.
- See that after 60 seconds the request is re-fetched.

<!--- Please add a Changelog note

Enter a changelog note using the following CLI command `npm run changelogger -- add` and commit changes.

### CODE REVIEW

**Comment by fitimvata** [comment]
@adrianduffell I don't think that this pr will resolve the issue. For one website that i and my team have developed we have more than 60k products, 500k orders and the query time is to high, basically never ends. So in my case the first request with timeout and the next request will use again the db until the mysql server hit 100% cpu usage. The only solution that I think is the best is to optimise the query for large db or add the option for user to opt out.

**Comment by adrianduffell** [comment]
@fitimvata Thanks for the feedback and I agree. We are working on different approaches to fix this at the same time. This PR aims to get the amount of REST API requests down to the same level as seen in 5.4.2, which hopefully would stabilize things for the majority of stores affected.

I agree 100% on the need to optimize the query for larger data sets. This is being worked on separately.

**Comment by atelierstudios** [comment]
Like @fitimvata, our very capable server with 4000 products, this query was timing out after 1.8 million ms/30 minutes. Cache wouldn't solve this for us either it would never resolve in time.

**Comment by adrianduffell** [comment]
Thanks @atelierstudios, rest assured we are working towards a solution for stores your size as well. I have left a [comment](https://github.com/woocommerce/woocommerce-admin/issues/7358#issuecomment-881808031) in the issue with an update on our query optimization efforts. I really appreciate your feedback here 🙂

**Review by ilyasfoo — APPROVED** [review]
This works well! 

>Is 60 seconds a good max age value? Should it be increased?

Since this is a temporary measure, I'm more keen to increase this to 5 minutes. Pre-approving!

**Comment by adrianduffell** [comment]
I've bumped the `max-age` value to `300` and now merging!

**Pull request merged**
