### PR TITLE
Store Profiler - Industry: reduced padding and removed industry

### LINKED ISSUE #5155: Store Profiler - Industry: reduce padding and remove industry
As a follow up of #5064, we're going to reduce 4px in the top/bottom padding (I think the CSS class is `woocommerce-profile-wizard__checkbox`) and remove the Art, Music & Photography industry to check if we can bring back the Industry step to the same conv. levels that we had before the change.

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #5155

This PR aims to reduce the size of the industries list in the second step of the Store profiler.
- The top/bottom padding of each list item is reduced by 4px
- The industry `Art, Music & Photography` is removed from the list.

### Screenshots
screenshot-one wordpress test-2020 09 17-17_46_55

### Detailed test instructions:

- Go to the second step of the OBW (URL: `/wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=industry`)
- Verify the item `Art, Music & Photography` is not visible.
- Verify that the list looks like the image above.

### Changelog Note:
Dev: Store Profiler - Industry step: reduced padding and removed industry

### CODE REVIEW

**Comment by samueljseay** [comment]
@octaedro Just a tip that your e2e tests are failing because the count of industries has changed. one test failing has a cascading effect to fail the others at the moment since some are dependent on others. It should just be a matter of changing the number of industries:

[here](https://github.com/woocommerce/woocommerce-admin/blob/main/tests/e2e/specs/activate-and-setup/complete-onboarding-wizard.test.js#L47)

and also [here](https://github.com/woocommerce/woocommerce-admin/blob/main/tests/e2e/specs/activate-and-setup/complete-industry-section.js#L12)

**Comment by octaedro** [comment]
> @octaedro Just a tip that your e2e tests are failing because the count of industries has changed. one test failing has a cascading effect to fail the others at the moment since some are dependent on others. It should just be a matter of changing the number of industries:

Thank you @samueljseay, nice catch! I fixed the e2e tests in the commit 887d721
Could you give this PR another look?

**Review by samueljseay — APPROVED** [review]
Looks good and testing well for me. 🚀

**Comment by timmyc** [comment]
cherry picked to `release/1.6.0-rc.1` in 91dde96

**Pull request merged**
