### PR TITLE
SummaryNumber: Switch to dropdown display on small screens

### LINKED ISSUE #131: SummaryNumber HiFi Updates
The `<SummaryList />` and `<SummaryNumber />` components are ready for another round of iterations to bring them into alignment with the finalized hi-fi designs ( p6riRB-3iy-p2 ). The hi-fi designs call for some styling changes that differ between usage on the Overview/Dashboard page, and on report pages. This task will focus on the usage in report pages, specifically the Revenue Report.

Included in this task are the following:

* Ensure the components are rending properly at the various breakpoints
* Adding support for the "Drop Down" functionality ( [inVision](https://automattic.invisionapp.com/d/main#/console/14559718/304694101/preview) ) at <783px
* Implement all states according to hi-fi design ( active, hover, etc )

screen-shot-2018-07-19-at-12-32-41

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #131 – This PR adds logic to collapse 2 or more SummaryNumbers into a dropdown/popover on screens smaller than 782px wide.

screen shot 2018-07-31 at 6 21 44 pm
screen shot 2018-07-31 at 6 21 55 pm

This also updates the semantics of the SummaryList component to use a NavigableMenu, which lets the user move through the list with either arrow keys or tab. I also moved the `isMobileViewport` function into a new file, `lib/ui`. In the future we might want to rethink this so that we can re-render the screens automatically as the browser resizes.

To test

- Shrink your browser (or test on a phone)
- Go to `/wp-admin/admin.php?page=wc-admin#/analytics/test`
- Check that the SummaryNumbers display as expected
- Open a dropdown, it'll take over the screen 
- Click an item, it should take you to the parent analytics page

### CODE REVIEW

**Review by timmyc — APPROVED** [review]
This is testing out quite nicely for me. The arrow nav is fantastic too 🙌 

I did notice that the summary numbers on the overview/dashboard page don't seem to collapse on the mobile view.

RE: update the mobile util to be screen-resize ready... I think we could look at that later on, but still feel it is kind of edge case outside of developers like us who resize browser windows just to test such things :)

The only place I really see it happening in real usage is on touch devices when users may change from horizontal to vertical screen orientation... we might want to see how that feels on some real devices.

**Comment by ryelle** [comment]
> I did notice that the summary numbers on the overview/dashboard page don't seem to collapse on the mobile view.

Oh right, I forgot to mention that. It's not collapsed in the mockup, so I've set the SummaryList to not collapse when there is no selected item.

**Comment by timmyc** [comment]
@ryelle heads up I rebased/force pushed to this remote branch so @LevinMedia could give this a test with Gutenberg 3.4

**Comment by LevinMedia** [comment]
@ryelle looking great! 

**Updates to the drop-down**

After reviewing the component in the context of a simulated mobile screen, I've updated the design of the initial state to be shorter in height. I'm trying to save vertical real estate and get the meat of the content which will apear below higher up on the page. The updated design is essentially the same as the > 250px wide version of this compoent for desktop screens, with the addition of the chevron to the right. 

screen shot 2018-08-01 at 9 08 16 pm

The update sketches are also available at p6riRB-3iy-p2

The chevron should be reduced in size from 36 to 24 px. 

On viewports <783px, the component should go edge to edge to maximize horizontal real estate 

screen shot 2018-08-01 at 9 21 08 pm

As a result, the component does not need left or right borders, just top and bottom. 

**Interactions**

The dropdown should be persistant and revealing the list of summary numers below it, rather than covering it with the full screen popover.

I created a small prototype to better detail the interaction that occurs when a user clicks on the dropdown - I added it to the bottom of p6riRB-3iy-p2 along with links to the screens for states and colors. When the dropdown is clicked, if it's possible I'd like the focus to be set on the currently selected item in the list.

**Comment by ryelle** [comment]
> Clicking the dropdown should reveal the list of summary numers below it, rather than covering it with the full screen popover.

@LevinMedia I know that's what the mockup says, but the overlay is how gutenberg handles mobile popovers. I saw [this comment about sticking with gutenberg's design](https://github.com/woocommerce/wc-admin/issues/151#issuecomment-407454965) and assumed it held for this as well. 

I've updated the percentage/previous value layout in the commit I just pushed, and I'm working on getting the edge-to-edge display working consistently now.

**Comment by ryelle** [comment]
SummaryNumbers are now edge-to-edge when the screen is <782px

screen shot 2018-08-02 at 11 35 45 am

**Comment by LevinMedia** [comment]
@ryelle Thanks for updating the width! 

>I saw this comment about sticking with Gutenberg's design and assumed it held for this as well.

that's a great point - however, in this case, we feel that interaction and data that the component presents is unique enough to warrant its own pattern. When using the popover in this case, you'll lose context.

**Comment by ryelle** [comment]
> I also noticed that when the initial state of the component is in focus, it looses the purple highlight

Hm, I had noticed that in a previous commit, but https://github.com/woocommerce/wc-admin/pull/265/commits/261123cf2c0ca9157d84dedcd5ec7545f162da81 should have fixed it – are you testing on an up-to-date branch?

Also, just to confirm, the popover style is the only thing remaining, which we'll address in a following PR. Is that right?

**Comment by LevinMedia** [comment]
> are you testing on an up-to-date branch

NOPE! Git pull solved that one.

Two additional comments, per a discussion with @ryelle on slack:

The original spec calls for this pattern to kick in at 1129px viewport sizes, with 24px left and right margins (the margins disappear at 782px).  We're going to use the 1100px breakpoint in WP core, rather than the original 1129px spec. 

Making a slight adjustment to the vertical alignment of the chevron

**Comment by ryelle** [comment]
The only "odd" thing about using the dropdown at >782 is that is does revert to an "inline"-ish dropdown:

screen shot 2018-08-02 at 5 02 55 pm

I'll address that in the same PR that updates the small screen popover styles.

**Pull request merged**
