### PR TITLE
Home Screen - modified tasks extensibility

### LINKED ISSUE #5242: Home Screen - tasks extensibility
**User story:**
As a 3PD
I want to easily extend the home screen task feature
So I can incorporate recurrent actions in my extension that require immediate attention

**Description:** our goal is to allow 3PDs to create home screen tasks for their extensions, in order to have a cohesive user experience. Ideally we should allow them to implement two different types of tasks:
- Setup tasks: that will be incorporated in the setup task list
- Recurring tasks: following the same approach that we have for orders, reviews and stock

We have a [wc-admin task example](https://github.com/woocommerce/woocommerce-admin/blob/master/docs/examples/extensions/add-task/woocommerce-admin-add-task-example.php), but I'm not sure if it can be reused for this.

**Acceptance criteria:**
- [ ] Allow 3pds to create setup tasks for their extensions with the following items: task name (with link to an extension page), time to complete the tasks and dismiss feature
- [ ] If a merchant completes the task list and then installs and extension that has a setup task associated, then we should display the task list again with that extension

- [ ] Allow 3pds to create recurring tasks and keep the limit that we have for our tasks: max 5 items per task

**Event tracking:**
NA

**Additional links:**
[P2 with links to the Figma file](pbIJXs-ma-p2)

### PR DESCRIPTION
**Pull request by octaedro**
Fixes #5242

This PR adds the modifications required for the task list extensibility.
 
* It should allow 3pds to create setup tasks for their extensions with the following items: task name (with link to an extension page), time to complete the tasks, and a dismiss feature
* If a merchant completes the task list and then installs an extension that has a setup task associated, then the task list will be displayed again with that extension.

### Accessibility

-   [x] I've tested using only a keyboard (no mouse)
-   [ ] I've tested using a screen reader
-   [x] All animations respect [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
-   [x] All text has [at least a 4.5 color contrast with its background](https://webaim.org/resources/contrastchecker/)

### Screenshots
screenshot-one wordpress test-2020 12 02-17_01_48

### Detailed test instructions:
1. Run `npm run example -- --ext=add-task`.
2. Activate the plugin `WooCommerce Admin Add Task Example`.
3. Be sure the setup task list is not hidden
```
UPDATE `wp_options` SET `option_value` = 'no' WHERE `wp_options`.`option_name` = 'woocommerce_task_list_hidden';
```
4. Go to the `Home` screen.
5. Verify the task list `Extensions setup` is visible.
6. Try the `Dismiss` button and undo the dismission. Verify everything is working as expected.

7. Hide the setup list (`Finish store setup`) and verify the other list is still there.
8. Hide the `Extensions setup` list and verify that it's not visible anymore. 
screenshot-one wordpress test-2020 12 02-18_49_37
9. Try adding another task * and verify the list now is visible again.
10. Confirm the callback method `onDismiss` is working correctly when a task is dismissed. To do it just take a look at the browser's console after dismissing a task, the message: `The task 'example-[number]' was dismissed
` should be visible.

_* I did that in the branch `add/5242_test` so you can check out that branch and run `npm run example -- --ext=add-task-two`, and activate the plugin `WooCommerce Admin Add Task Example Two`. The task button `Mark as complete` should mark all these tasks as completed after being pressed._

### CODE REVIEW

**Review by louwie17 — APPROVED** [review]
Great work @octaedro 💯  code changes look good, and overall it tested well :)

One question (not a blocker) I had was, should the extension maintainers be in charge of cleaning up if there plugin gets de-activated/uninstalled? Given the option data would linger around otherwise.
I suppose this might be something we will find out over time as developers make use of this.

**Comment by samueljseay** [comment]
Just noting that this won't need cherry picking since code freeze hasn't happened yet.

**Comment by octaedro** [comment]
Thank you for your review @louwie17 

> One question (not a blocker) I had was, should the extension maintainers be in charge of cleaning up if there plugin gets de-activated/uninstalled? Given the option data would linger around otherwise.

This is a good idea! I created a [follow-up PR with a few improvements](https://github.com/woocommerce/woocommerce-admin/pull/5833) and I added this one there too.

**Comment by franticpsyx** [comment]
@octaedro 

Kudos for the awesome work! 💯 

> WooCommerce Admin Add Task Example

Is this available somewhere? Any guides/docs in the making? Thanks! 👍

**Comment by octaedro** [comment]
Hi @franticpsyx,
This feature had a few modifications. The final version of this feature will be released in `WooCommerce Admin 2.0.0`. At the moment you can try it in the [(pre-release) rc2](https://github.com/woocommerce/woocommerce-admin/releases/tag/v2.0.0-rc.2-plugin).

To get an example task you have to execute `npm run example -- --ext=add-task` in your terminal. The example task code is [here](https://github.com/woocommerce/woocommerce-admin/tree/main/docs/examples/extensions/add-task).

A tutorial to use it will be published soon. I can provide you a draft of that if you need it. Otherwise, I can let you know as soon as the tutorial has been published.

**Comment by franticpsyx** [comment]
Thanks so much @octaedro -- 

> A tutorial to use it will be published soon.

We'll keep an eye out, then :) Keep up the awesome work!

**Comment by octaedro** [comment]
Hi @franticpsyx,
The tutorial I mentioned above will be published soon but if you're interested in the feature [this is a preliminary draft](https://github.com/woocommerce/woocommerce-developer-advocacy/blob/18c3bf912690cf52fbdba200a6a4ed9257d2e637/ownership-areas/resource-curation/ongoing/create-blog-posts/2021-q1/2021-02-16-extend-setup-tasklist.md).
Please let me know if you need more documentation related to the tasklist extensibility 🙂

**Comment by franticpsyx** [comment]
Hey @octaedro that's awesome to hear!

The link is throwing a 404 for me, I believe it's in a private repo. We'd sure love to give this a shot!

**Comment by samueljseay** [comment]
> I believe it's in a private repo. 

@franticpsyx sorry about that! I've chucked up the content in a gist so you can take a look, it will also be published soon, but if you have any feedback on how it can be improved then please let us know!

https://gist.github.com/samueljseay/74383ed736306b6019e3f77dea161efe

**Comment by franticpsyx** [comment]
Thank you Sam,

I'll leave some notes under the gist 👍

**Pull request merged**
