### PR TITLE
Docs: Remove REST API feature branch requirement.

### PR DESCRIPTION
**Pull request by timmyc**
With the reporting endpoints merged in, this sentence is no longer needed.

### CODE REVIEW

**Comment by ryelle** [comment]
Can you also update `docs/README.md`? We could eventually automate that, but right now it's not part of the generator script.

**Comment by timmyc** [comment]
Ah thanks for the reminder @ryelle, ran `npm run docs`

**Comment by ryelle** [comment]
oh, I meant manually update [the file `docs/README.md`](https://github.com/woocommerce/wc-admin/blob/master/docs/README.md) - that's the file at [the root of the docs site](https://woocommerce.github.io/wc-admin/#/) and it _isn't_ automatically copied.

**Comment by timmyc** [comment]
Ha I did that too, but discovered that I had to do it manually after I ran `npm docs` figured might as well update the docs while I'm here 😆

**Review by ryelle — APPROVED** [review]
Looks good, I recently merged #434 which also includes the `npm run docs` update, but I don't think this will conflict 👍

**Pull request merged**
