### PR TITLE
Homescreen layout changes

### LINKED ISSUE #5223: Home Screen - layout changes
**User story:**
As a new merchant
I want to easily access the setup task list
So I can focus on completing the setup as soon as possible

**Description:** moving the setup tasks to the home screen increased retention among new users. However, we ended up seeing more users drifting away and not using the setup tasks. We bet that by some changes in the layout we'll be able to increase the focus in the setup tasks.

**Acceptance criteria:**
- [ ] For brand new stores we'll display a single column layout with the following order (setup tasks, stats overview, inbox)

- [ ] Upon dismissing or completing the task list, the layout should default to two columns

dismiss-task-list-1

- [ ] For existing stores we'll keep the two-column layout (this also includes stores that already have the setup task list enabled before the Woo version where we include the layout changes). However, we'll change the sections displayed on each column: the left column should include the tasks and store management section, on the right column we should have the stats overview and inbox

**Event tracking:**
It won't be necessary to include additional event tracking for this work

**Additional links:**
[P2 with link to Figma ](pbIJXs-ma-p2)

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #5223.

**This PR implements the following from #5223:**

- Default new stores to the single column homescreen
- Dismissing the task list, or completing the task list switches the homescreen to two columns
- Move task list / quick links to the left column
- Move inbox to right column under stats

**Additional behavior not explicitly described in the issue:**
- User preference for homescreen layout always takes precedent over the default (even if changed before the task list is complete)
- Left column (with the task list) is now the sticky column (used to be the right)
- The "your store today" header only displays when two columns are visible (gleaned from designs - not 100% if that's intended)

**Implementation notes**

The default layout (for new vs. existing stores) is controlled using a new option, `woocommerce_default_homepage_layout`. The client side code defaults to `single_column` if it's unset. Existing stores will have the value `two_columns` set in the version `1.7.0` DB update routine - while new stores will not. Again, any user preferences set will override this value.

### Screenshots

Screen Shot 2020-10-22 at 1 41 28 PM

### Detailed test instructions:

- On an existing store (be sure to clear any `woocommerce_admin_homepage_layout` user meta if you've tested https://github.com/woocommerce/woocommerce-admin/pull/5429):
  - Verify the home screen default gets set to `two_columns` (check the `woocommerce_default_homepage_layout` option after the DB updates run)
  - Verify that you can toggle to a single column view
- On a new store:
  - Verify that the home screen is single column by default
  - Dismiss the task list
  - Verify the home screen default switches to two columns
- On another new store:
  - Verify that the home screen is single column by default
  - Complete the task list
  - Verify the home screen default switches to two columns
- Verify the two column layout changes - task list on left, quick links on left, inbox under stats
- Verify single column layout changes (see issue) inbox on bottom

### Changelog Note:

Tweak: alter homescreen layout.

### CODE REVIEW

**Comment by elizaan36** [comment]
> Left column (with the task list) is now the sticky column (used to be the right)

FYI just [commented on one small thing](https://app.zenhub.com/workspaces/start--manage-focus-5b0524212133e1068138a6fe/issues/woocommerce/woocommerce-admin/5223#issuecomment-715432991) in the issue. Since there's more content being added to the left column, it would be best if the left and right columns were each sticky upon reaching the end of their particular scrolls.

**Review by samueljseay — APPROVED** [review]
This tested well for me, code is great too. Just the design related comment needs addressing but from me: 🚀

**Comment by jeffstieler** [comment]
Ok, fixed up the sticky scrolling for both columns. This needs another full review I'd say given the 2 rounds of merge conflicts this just went through. 🙃 

Note: we're probably going to need to enhance the columns' ability to detect content height changes since the accordion is collapsible.

**Review by octaedro — APPROVED** [review]
Great job @jeffstieler! The code looks really good and this is testing well here.
I only found a nitpick detail in the `Display` menu:
screenshot-one wordpress test-2020 11 06-14_39_33
(Although the `Two columns` are selected, it's showing the first element with a border)

But I'll preapprove this PR since it's something really small.

**Comment by elizaan36** [comment]
single column scroll

Hey @jeffstieler, I was just testing this and noticed a bug with the single-column scroll. It looks like the stats overview and Inbox messages are scrolling under the task list and store management cards.

**Comment by elizaan36** [comment]
(I actually tested the branch before it was merged and deleted, but was in a user research interview so couldn't share until now🙃)

If you can reproduce want me to create a new issue for this?

**Comment by jeffstieler** [comment]
@elizaan36 I think this has been fixed - have you tried again recently?

**Comment by elizaan36** [comment]
@jeffstieler, yep that scroll overlap thing been fixed. I have a couple questions about the Display dropdown that I can put in another issue/PR.

When I click the display dropdown in two column mode, the single column option is showing as a focus state. In this case, the two columns should have the focus outline.
Screen Shot 2020-11-09 at 3 15 05 PM

Also, would be best to dismiss the dropdown after making your selection, rather than needing another click outside to close. What do you think?

**Comment by jeffstieler** [comment]
That sounds good @elizaan36 - do you mind creating a new issue for those changes? Thanks!

**Pull request merged**
