### PR TITLE
Try using fresh-data for OrderList

### PR DESCRIPTION
**Pull request by coderkevin**
Addresses #153 
This uses [`fresh-data`](https://github.com/automattic/fresh-data) for the order list data instead of `withApiData`.

To Test:

1. `npm install`
2. `npm test` and ensure the `wc-api` tests pass.
3. Load up the dashboard and click the "Orders" icon at the top-right.
4. All should be behave as before.
5. Every 5 minutes, Orders will be re-fetched and updated here.
6. Click "Fulfill" on an order with a "processing" status, it should change immediately due to an interim optimistic edit state.

### CODE REVIEW

**Review by timmyc — COMMENTED** [review]
🥇 super cool to see this PR! And +1 on Paul's comment about adding in a mutation, just for example.

I also left one comment about a method signature, and on that note thinking a selector such as that might want to passing additional arguments, maybe search eventually?

**Review by ryelle — COMMENTED** [review]
Thanks for the work on this PR. It's much easier to see how fresh-data works in a real setting 🙂 

I have my usual naming nitpicks, but also some other questions about different abstractions. I would also love to see more inline docs & READMEs 😁 Especially in `/wc-api` and `/state`.

**Comment by dmsnell** [comment]
> how would you handle optimistic updates

> I'd like for the api to always reflect the actual server data as faithfully as possible. Because of that, I think it would be best to hold onto the interim state until the operation is complete

also it can be helpful to think in terms of "the local app is the universal source of truth" and realize that _the act of requesting or announcing a change_ is different than _the act of making a change_. put differently, just update the data in the app and synchronize with the server. if the server response comes back showing a different value (if the server provides the confirmation in its response) then you simply make a new change.

we can pair this with request tracking to show that a setting has been changed but we haven't been able yet to confirm that the change is persisted on the backend.

**Comment by coderkevin** [comment]
>  just update the data in the app and synchronize with the server. if the server response comes back showing a different value (if the server provides the confirmation in its response) then you simply make a new change.

I disagree. I think there's value in knowing what the server state is, and knowing what unratified changes the client has outstanding are. It's much easier to combine the two than to sort them out when they're already together. (e.g. `{ ...serverObject, ...myEdits }` vs `inspectOutstandingRequests( combinedObject, requests )`

Furthermore, if we hang on to our edits separately, it's easy to update the server API data underneath, and then you get some nice features like updating the inventory count on the Product Edit page while you work (helps fight against incorrect inventory counts!), or even 3-way merges when something changes on the server and you have an edit on that same field.

**Review by claudiosanches — APPROVED** [review]
`client/wc-api` looks good to me.
Great work.

**Comment by timmyc** [comment]
With the decision to move forward with `wp.data` i'm going to close this try branch out.

**Pull request closed without merging**
