### PR TITLE
Hide shipping cost task if user has disabled shipping

### LINKED ISSUE #5562: Shipping tasks should be hidden if user has disabled shipping
**Describe the bug**

If you've disabled shipping, you'll notice that the shipping task just keeps spinning (screenshot below) with a console error.

**To Reproduce**

1. Complete the initial onboarding flow
2. Disable shipping: **WooCommerce > Settings > General > General options > Shipping location(s) > Select - Disable shipping and shipping Calculations**
3. Access: https://YOUR-DOMAIN/wp-admin/admin.php?page=wc-admin&task=shipping
4. Notice that the `Set shipping costs` task just keeps spinning with a console error (screenshot below)

**Expected behavior**

Hide / auto-complete the task if shipping is disabled.

**Screenshots**

https://d.pr/i/eX5WIx+

**Desktop (please complete the following information):**

ANY

**Smartphone (please complete the following information):**

ANY

**Additional context**

Originally reported in 3463481-zen

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #5562 

This PR checks general setting values and hide the shipping cost task if `settings.woocommerce_ship_to_countries` is disabled.

### Screenshots

**Original**
Screen Shot 2020-12-08 at 5 41 07 PM

**Shipping location(s)**: Disable shipping and shipping calculations

Screen Shot 2020-12-08 at 5 44 00 PM

### Detailed test instructions:

1. Complete the initial onboarding flow
2. Disable shipping: **WooCommerce > Settings > General > General options > Shipping location(s) > Select - Disable shipping and shipping Calculations**
3. Access: https://YOUR-DOMAIN/wp-admin/admin.php?page=wc-admin&task=shipping or navigate to WooCommerce -> Home and click "Set up shipping" under the `Finish setup`
4. Confirm that you have only 3 tasks and "Set shipping costs" task is missing.

### CODE REVIEW

**Review by louwie17 — CHANGES_REQUESTED** [review]
@moon0326 nice and straight forward change :) and it tested well.

Just requesting one change: I think this would be a great place to start writing some unit tests for the Shipping task, it doesn't appear there are any yet, and this would make for a good test case.

**Comment by moon0326** [comment]
@louwie17 Good suggestion 👍 I will include one.

**Comment by moon0326** [comment]
@louwie17 A test has been added in https://github.com/woocommerce/woocommerce-admin/pull/5850/commits/9e4127d6094a7acaaa69f98610083f07da4dda0f.

**Review by louwie17 — APPROVED** [review]
Good stuff on writing a test @moon0326, good to ship :)

**Comment by moon0326** [comment]
@louwie17 thank you! My first JS test in this repo 😄

**Comment by louwie17** [comment]
> @louwie17 thank you! My first JS test in this repo 😄

@moon0326 hopefully the first of many 😄 😉

**Pull request merged**
