### PR TITLE
Revert copy for setup checklist

### LINKED ISSUE #6943: Setup Checklist: Change Copy Back
@pmcpinto would like to revert some of the text changes made to the Setup Checklist in #6298

Pedro, wanting to confirm the only items you would like to revert from the original PR are the text changes in the following files:

image
 
and

image

There were quite a few other copy changes included in the original PR, but the above two files are the ones that resulted in changes to the setup checklist.

### PR DESCRIPTION
**Pull request by ilyasfoo**
Fixes #6943

This PR reverts back copy in Setup Checklist.

### Detailed test instructions:

- Compare the diff in this PR:
  -  `client/task-list/index.js` with [this change](https://github.com/woocommerce/woocommerce-admin/commit/ef6aa388c40abffecb512e1af49c915ebe1449a6#diff-148b443dac4ecc6e426b7dca0475271e131ff015d751fb90262bd16156695856R135)
  - `client/task-list/tasks.js` with [this change](https://github.com/woocommerce/woocommerce-admin/commit/ef6aa388c40abffecb512e1af49c915ebe1449a6#diff-5819c659c28ae2e77a147c661fe8bd0f1cc3206a636b74281ece1674cf88480dL86)

### CODE REVIEW

**Review by octaedro — APPROVED** [review]
Everything looks good to me. Nice job @ilyasfoo :shipit:

**Review by octaedro — CHANGES_REQUESTED** [review]
Oh, sorry @ilyasfoo for the back and forth.
I'm seeing that there are a few E2E tests failing because of the text changes. Could you take a look at that?

**Comment by ilyasfoo** [comment]
Thank you for catching that, I have addressed the issue. Please have another look @octaedro!

**Review by octaedro — APPROVED** [review]

**Comment by octaedro** [comment]
Great @ilyasfoo, everything looks good now.
Thanks!

**Comment by timmyc** [comment]
Thanks for fixing this in `main` @ilyasfoo - when I went to cherry pick this to `release/2.3.1` I hit quite a bit merge conflict in `client/task-list/index.js`. It looks like `main` has diverged from `release/2.3.0` quite a bit since the 2.3 release branch was cut. Thinking it might be best to make another PR with these changes in a branch off of `release/2.3.1` instead.

I'll try to get a PR up for that today.

**Comment by timmyc** [comment]
huh, scratch that, the 2.3.0 branch strings match what was implemented in this PR. so I think we are all good.

**Comment by timmyc** [comment]
#7049 is the pr that copies these changes to the 2.3.x branch file structure

**Pull request merged**
