### PR TITLE
Add a nonce check function when preparing note response

### LINKED ISSUE #27424: Notifications won't go away after clicking their button
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The notifications at the top won't go away after clicking their buttons:
"Coupon management has moved!"
"WooCommerce database update done"

I clicked their buttons many times, nothing happened.
I cleared cache, loged out, deleted cookies, cleared browser cache.

**Expected behavior**
The notification should go away after you click them once.

**Actual behavior**
The notifications at the top won't go away after clicking their buttons

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
This started after updating to the WC 4.4.1
Using PHP 7.4.9

**Screenshots**
https://ibb.co/hBjgzr3

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.japanese-knives.co.il
Site address (URL): https://www.japanese-knives.co.il
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.9
PHP Post Max Size: 2 GB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.71.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: hks_
Total Database Size: 361.97MB
Database Data Size: 304.73MB
Database Index Size: 57.24MB
hks_woocommerce_sessions: Data: 0.27MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_order_items: Data: 2.52MB + Index: 0.42MB + Engine InnoDB
hks_woocommerce_order_itemmeta: Data: 14.52MB + Index: 10.03MB + Engine InnoDB
hks_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_acl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_net: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_log: Data: 2.52MB + Index: 0.72MB + Engine InnoDB
cerber_qmem: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_traffic: Data: 159.27MB + Index: 2.48MB + Engine InnoDB
hks_actionscheduler_actions: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
hks_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_actionscheduler_logs: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
hks_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_atum_product_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_cerber_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_cerber_sets: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
hks_cerber_uss: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_commentmeta: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
hks_comments: Data: 7.52MB + Index: 2.64MB + Engine InnoDB
hks_duplicator_packages: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_detail_new: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_enquiry_quotation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_enquiry_thread: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_gcb: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_grp_google_place: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_grp_google_review: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_huge_itgallery_gallerys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_images: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_like_dislike: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_params: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
hks_imagify_files: Data: 0.36MB + Index: 0.33MB + Engine InnoDB
hks_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_itbbc_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_itbbc_history_items: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
hks_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_mclean_scan: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
hks_media_file_manager_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_slides: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
hks_options: Data: 27.50MB + Index: 0.59MB + Engine InnoDB
hks_postmeta: Data: 54.58MB + Index: 27.08MB + Engine InnoDB
hks_posts: Data: 9.52MB + Index: 2.42MB + Engine InnoDB
hks_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
hks_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
hks_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
hks_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_sliders: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
hks_revslider_sliders_bkp: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
hks_revslider_slides: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
hks_revslider_slides_bkp: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
hks_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tcb_api_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_termmeta: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
hks_terms: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
hks_term_relationships: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
hks_term_taxonomy: Data: 0.38MB + Index: 0.36MB + Engine InnoDB
hks_tge_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tge_questions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tqb_event_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_users: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_user_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_variations: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
hks_ukuu_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_usermeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
hks_users: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
hks_wcsc_error_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wcsc_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
hks_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_customer_lookup: Data: 0.34MB + Index: 0.20MB + Engine InnoDB
hks_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_product_lookup: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
hks_wc_order_stats: Data: 0.41MB + Index: 0.31MB + Engine InnoDB
hks_wc_order_tax_lookup: Data: 0.27MB + Index: 0.20MB + Engine InnoDB
hks_wc_product_meta_lookup: Data: 0.13MB + Index: 0.19MB + Engine InnoDB
hks_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_data: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_option: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_theme: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_bundled_itemmeta: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
hks_woocommerce_bundled_items: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
hks_yoast_indexable: Data: 6.52MB + Index: 1.09MB + Engine InnoDB
hks_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
hks_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_yoast_primary_term: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
hks_yoast_prominent_words: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_yoast_seo_links: Data: 0.34MB + Index: 0.11MB + Engine InnoDB
hks_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amn_smtp: 1
attachment: 3292
clients: 1
content_block: 75
decision_tree: 1
follow_up_email: 8
klaviyo_shop_cart: 1
nav_menu_item: 359
oembed_cache: 3
optionsframework: 12
page: 56
post: 29
postman_sent_mail: 250
product: 555
product_variation: 368
pys_event: 3
revision: 36
shop_coupon: 305
shop_order: 5003
shop_order_refund: 4
slide: 1
sp_wpsp_shortcodes: 1
thrive_image: 5
tqb_quiz: 4
tqb_results: 3
tqb_splash: 1
vc_grid_item: 1
wcct-deal-shortcode: 1
wcct_countdown: 45
wcst_trigger: 9
wc_zapier_feed: 2
wp-type-contacts: 2
wpb-rs-global: 7
wpcf7_contact_form: 1
wp_quiz: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (72) ###

Query Monitor: by John Blackbourn – 3.6.2
10bit-woocommerce-zap-mirror: by 10bit – 1.3.14 – Installed version not tested with active version of WooCommerce 4.4.1
Classic Editor: by WordPress Contributors – 1.6
Contact Form 7: by Takayuki Miyoshi – 5.2.1
Content Blocks (Custom Post Widget): by Johan van der Wijk – 3.1.1
Duplicate Menu: by Jonathan Christopher – 0.2.2
Enable Media Replace: by ShortPixel – 3.4.2
Envato Market: by Envato – 2.0.3
Facebook Post Embed: by Alobaidi – 1.0.0
Finale WooCommerce Deal Pages: by XLPlugins – 1.4.1 – Installed version not tested with active version of WooCommerce 4.4.1
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: by XLPlugins – 2.17.1 – Installed version not tested with active version of WooCommerce 4.4.1
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Global Content Blocks: by Dave Liske – 2.1.5
WhatsApp Chat for WordPress / WooCommerce: by idnovate.com – 1.3.9 – Installed version not tested with active version of WooCommerce 4.4.1
Imagify: by WP Media – 1.9.10
Klaviyo: by Klaviyo
Inc. – 2.2.4 – Installed version not tested with active version of WooCommerce 4.4.1

Loco Translate: by Tim Whitlock – 2.4.2
One Time Login: by Daniel Bachhuber – 0.3.0
Perfmatters: by forgemedia – 1.6.0
PixelYourSite PRO: by PixelYourSite – 7.6.4 – Installed version not tested with active version of WooCommerce 4.4.1
plugin load filter: by enomoto@celtislab – 3.3.0
Post SMTP: by Yehuda Hassine – 2.0.15
Product Filter for WooCommerce: by XforWooCommerce – 7.3.3 – Installed version not tested with active version of WooCommerce 4.4.1
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 4.1.3 – Installed version not tested with active version of WooCommerce 4.4.1
PushAlert - Web Push Notifications: by PushAlert – 2.6.0 – Installed version not tested with active version of WooCommerce 4.4.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Slider Revolution: by ThemePunch – 6.2.22
snip - The Rich Snippets & Structured Data Plugin: by wpbuddy – 2.19.0
Search & Replace: by Inpsyde GmbH – 3.2.1
ShiftNav Pro - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.7.0.1

Shortcode Empty Paragraph Fix: by  – 0.2
SmartLook Visitor Recording: by Smartsupp – 2.1.1
Hide SEO Bloat: by SO WP – 3.14.3
Social Icons Widget & Block by WPZOOM: by WPZOOM – 4.0.3
SOFT79 Cart Links for WooCommerce: by Soft79 – 1.1.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Thank You Page - NextMove: by XLPlugins – 1.14.0 – Installed version not tested with active version of WooCommerce 4.4.1
TWB Woocommerce Reviews: by Abu Bakar – 1.7.3 – Installed version not tested with active version of WooCommerce 4.4.1
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.7.2

Widget CSS Classes: by C.M. Kendrick – 1.5.4
CardCom Payment Gateway: by CardCom LTD – 3.3.2.8 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Breadcrumbs: by Anthony Hortin – 1.0.7 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce - Frontend Inventory: by Mirko Grewing – 0.7 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.6.9
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.14 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Notification Premium: by Andy Ha (villatheme.com) – 1.4.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Product Bundles: by SomewhereWarm – 6.3.3 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Product Primary Category: by BeoCode.d.o.o. – 0.1.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Show Attributes: by Isabel Castillo – 1.6.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Zapier: by OM4 – 2.0.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce: by Automattic – 4.4.1
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO Premium: by Team Yoast – 14.8
WP Accessibility Helper: by Alex Volkov – 0.5.9.4
WP Cerber Security, Anti-spam & Malware Scan: by Cerber Tech Inc. – 8.6.7
WP-Cron Status Checker: by Webhead LLC – 1.2.1
Custom Body Class: by Andrei Lupu – 0.7.2
WP Memory: by Bill Minozzi – 1.1
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

WP Rocket | Set Tablets As Mobile: by WP Rocket Support Team –
WP Rocket | YITH WooCommerce Recently Viewed Products Integration: by WP Rocket Support Team –  – Installed version not tested with active version of WooCommerce 4.4.1
WP Rocket | Custom cURL Timeout For Preload Requests: by WP Rocket Support Team –
WP Rocket | CPCSS Debug Helper: by WP Rocket Support Team – 1.0.0
WP Rocket | Exclude Files from Defer JS: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.6.4
WP-RTL: by Fahad Alduraibi – 1.0
WP Server Stats: by Saumya Majumder
Acnam Infotech – 1.6.9

WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.3
WP User Avatars: by John James Jacoby – 1.4.0
WPX Cron Manager Light: by Giovambattista Fazioli – 2.3.4
Finale Email Countdown Timer: by XLPlugins – 1.2.0 – Installed version not tested with active version of WooCommerce 4.4.1
XL WooCommerce Sales Triggers: by XLPlugins – 2.10.0 – Installed version not tested with active version of WooCommerce 4.4.1
Embed Plus for YouTube Pro - Gallery, Channel, Playlist, Live Stream: by Embed Plus for YouTube Team – 13.4.1

### Inactive Plugins (13) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Contact Form 7 Captcha: by 247wd – 0.0.7
Duplicator: by Snap Creek – 1.3.36
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Hello Dolly: by Matt Mullenweg – 1.7.2
Media Cleaner (Pro): by Jordy Meow – 6.0.2
Redirection: by John Godley – 4.8
Stop Generating Unnecessary Thumbnails: by codexpert – 3.0.4
What The File: by Never5 – 1.5.4
Widget Options: by Widget Options Team – 3.7.4
Widget Shortcode: by Hassan Derakhshandeh – 0.3.5
WooCommerce Blocks: by Automattic – 3.2
WooCommerce Conversion Tracking: by weDevs – 2.0.8 – Installed version not tested with active version of WooCommerce 4.4.1

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

aaa-wp-cerber.php: by Cerber Tech Inc. – 1.0
Health Check Troubleshooting Mode: by  – 1.7.1
plugin load filter [plf-filter]: by enomoto@celtislab – 3.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1812 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /order/
My account: #7 - /my-account/
Terms and conditions: #605 - /legal/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.12.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Product Bundles ###

Database Version: 6.3.3
Loopback Test: ❌ Loopback test failed.
Template Overrides: –

### Action Scheduler ###

Complete: 2,132
Oldest: 2020-07-20 16:17:44 +0300
Newest: 2020-08-20 13:53:48 +0300

Failed: 10
Oldest: 2019-05-30 09:09:52 +0300
Newest: 2020-03-27 22:20:38 +0300

Pending: 3
Oldest: 2020-08-21 04:21:09 +0300
Newest: 2020-08-21 13:59:37 +0300

### WooCommerce Zapier ###

Database Version: ✔ 12
Detailed Logging Enabled: No
Legacy Mode Disabled: ❌ No
SSL: ✔ Yes
REST API Authentication Key(s): ❌ 0
Task History Record Count: ❌ 0
Legacy Cron Tasks: ✔ 0
Active Legacy Feeds: ❌ 2 active Legacy Feed(s) need to be migrated before 30/04/2021. Migrate Your Zaps Now
Legacy Feed #1: WooCommerce new order to Pipedrive
- Trigger: New Order
- Webhook URL: https://hooks.zapier.com/hooks/catch/1820158/az4tnv/
Legacy Feed #2: WooCommerce new person to Pipedrive
- Trigger: New Order
- Webhook URL: https://hooks.zapier.com/hooks/catch/1820158/w3lvd2/
`
</details>

### PR DESCRIPTION
**Pull request by roykho**
Fixes https://github.com/woocommerce/woocommerce/issues/27424

### Detailed test instructions:

Please see https://github.com/woocommerce/woocommerce/pull/28500

* Add - An optional nonce check for passed in admin note.

### CODE REVIEW

**Review by Konamiman — APPROVED** [review]

**Comment by roykho** [comment]
Hey @timmyc - Would you mind getting this reviewed by someone on your team? Thanks!

**Review by adrianduffell — CHANGES_REQUESTED** [review]
Hi @roykho

Thanks for the PR! If I understand it correctly, this refreshes the values of any nonces found in action URLs.

I think a drawback to returning nonces in the REST response is the data can't then be cached. Would it be possible to refresh the nonce closer to the time of render instead, such as in the [InboxNoteAction]( https://github.com/woocommerce/woocommerce-admin/blob/cd781a9f923e489c6a83571666b3a97b2627188e/client/inbox-panel/action.js#L140) component?

**Comment by roykho** [comment]
@adrianduffell - in that case perhaps we can just hook in via this filter here https://github.com/woocommerce/woocommerce-admin/blob/550a93dcafe355f054b487610ad70429b3490331/src/API/Notes.php#L489

Since that is after coming back from the API response. Then we wouldn't need to make any changes here and we'll just hook in from WC core. What do you think?

**Comment by adrianduffell** [comment]
@roykho thanks, the filter looks like a good workaround :thumbsup:

I think there would be value bringing native support for nonces to the Notes feature. How about I work on a proposal for this, and you could use the `woocommerce_rest_prepare_note` filter in the meantime?

**Comment by roykho** [comment]
@adrianduffell  - Do you have a timeline in mind to support this natively? Not to put you on the spot of course. Just a rough timeline and if it isn't too far out, perhaps we could just wait for this native solution rather than having to ship with interim solution and have to remove it later.

**Comment by adrianduffell** [comment]
> Do you have a timeline in mind to support this natively?

@roykho I have in mind the next 1-2 months. How would that place things for you?

**Comment by roykho** [comment]
@adrianduffell - sounds good! Thanks!

**Comment by roykho** [comment]
I am closing this in favor of a native solution. Thanks @adrianduffell

**Pull request closed without merging**
