### PR TITLE
REST API: Allow sorting by stock_status in stocks endpoint

### LINKED ISSUE #966: /wc/v3/reports/stock should allow sorting products by `stock_status`
For the Stock report (#174) we will sort the products and variations by `stock_status` by default.

The current API endpoint only allows sorting by `stock_quantity`, `date`, `id`, `include`, `title` and `slug`.

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #966 

Allows sorting by `stock_status` on stocks endpoint.

### Detailed test instructions:

1.  Make a request to `/wp-json/wc/v3/reports/stock`
2.  Pass `stock_status` as the `orderby` param.
3.  Check that sorting returns by status.
4.  Change the `order` param to `desc` and check that sorting by status is reversed.

### CODE REVIEW

**Review by Aljullu — COMMENTED** [review]
This is testing well for me. But would it be possible to use `stock_quantity` as the second sort value?

Sorting by `stock_status` with `order=desc`, `Out of stock` products appears on top, so I would expect the products with a lower `stock_quantity` to appear above:

image

Same, when sorting in the other direction (when `In stock` products appear on top), I would expect products with the higher `stock_quantity` to appear above).

I don't know if that's possible, but that's what I would expect as a user.

I created #1340 as a follow-up of this PR, it updates the UI to use `stock_status` by default. Feel free to merge in into your branch.

**Comment by joshuatf** [comment]
@Aljullu That seems reasonable.  I added a commit to do this and also reversed the order of status quantity since it seems like you'd want to see the larger (absolutely bigger values) stock values first when sorting with this method.  Let me know what you think.

**Review by Aljullu — COMMENTED** [review]
Thanks for making these changes @joshuatf, it looks much better now. The only last issue I noticed is that you need to click two times on the _Status_ header to reverse the order, now:

status

**Review by claudiosanches — APPROVED** [review]
PHP part looks good.

**Review by Aljullu — APPROVED** [review]
> I noticed that issue across a number of reports as it seems the order is disconnected from `tableQuery` and `query`. Opened a separate issue here to handle that. Let me know if that sounds okay to you.

Thanks for filling an issue for that @joshuatf!

**Pull request merged**
