### PR TITLE
Fix dataEndpoints notice

### PR DESCRIPTION
**Pull request by emdashcodes**
See p1544812123280800-wc-admin-slack.

### Detailed test instructions:

- Check debug/error log and see no notice.
- Optionally spot check the country dropdown on the customer report.

### CODE REVIEW

**Comment by timmyc** [comment]
I'm still seeing the warning output with this branch:

`<b>Notice</b>:  Undefined index: /wc/v3/data/countries in <b>/srv/www/example/public_html/wp-content/plugins/wc-admin/lib/client-assets.php</b> on line <b>185</b><br />`

but adding in a check for the key like so clears it up:

```
foreach ( $preload_data_endpoints as $key => $endpoint ) {
		if ( ! isset($settings['dataEndpoints'][ $key ] ) ) {
			continue;
		}
		$settings['dataEndpoints'][ $key ] = $preload_data[ $endpoint ]['body'];
	}
```

**Comment by jeffstieler** [comment]
I can't seem to get the warning to show up in the first place 🤷‍♂️.

> but adding in a check for the key like so clears it up

That looks like it will prevent the `dataEndpoints` array from being populated.

**Comment by justinshreve** [comment]
@timmyc Does the country autocompleter make suggestions for you? Seems like `$preload_data` is not getting set.

* What version(s)/branches of WP and WC are you using? (And Gutenberg if applicable).
* Can you do a `error_log( print_r( $preload_data, 1 ) );` after the `array_reduce` on line 156? Does this give you an error instead of API data?

**Review by timmyc — APPROVED** [review]
Updated my Woo and G-berg versions and all is well now.

**Pull request merged**
