### PR TITLE
Activity Panel: Inbox: Add Woo Extension Subscription / Connection Notes

### PR DESCRIPTION
**Pull request by allendav**
See #176 

Adds woo extension subscription and connection notes to the merchant inbox. Note: Bumping expiring notices at 45/20/7/1 days out will be done under a separate PR (#711) since this one got big.

READY FOR REVIEW / TESTING

### Screenshots

screen shot 2018-10-25 at 3 09 22 pm

screen shot 2018-10-25 at 4 43 21 pm

screen shot 2018-10-25 at 4 50 19 pm

### Detailed test instructions:

*Connection Test*

 - You will need to be able to connect your site to WooCommerce.com for this test.
- Start with your site not connected to WooCommerce.com
- Go to wp-admin > WooCommerce > Dashboard > Inbox and make sure you have a *Connect to WooCommerce.com* note in your inbox.
- Connect to a WooCommerce.com
- Verify the *Connect to WooCommerce.com* note is no longer in your inbox.

*Expiring Test*

- At WooCommerce.com, buy a single site subscription for Product Add-Ons
- DO NOT ENABLE AUTORENEW FOR PRODUCT ADD ONS
- Modify the order on woocommerce.com so that Product Add-Ons expires about 30 days from today.
- Download, install, and activate Product-Add Ons
- Set the Product-Add Ons subscription to active on wp-admin > WooCommerce > Extensions > WooCommerce.com Subscriptions
- Go to wp-admin > WooCommerce > Dashboard > Inbox and make sure you have a note that the Product Add Ons subscription is expiring in 30 days.
- Set the Product-Add Ons subscription to inactive on wp-admin > WooCommerce > Extensions > WooCommerce.com Subscriptions
- Go to wp-admin > WooCommerce > Dashboard > Inbox and make sure you DO NOT have a note about the Product Add Ons subscription.

*Expired Test*
- IMPORTANT: Set the Product-Add Ons subscription to active on wp-admin > WooCommerce > Extensions > WooCommerce.com Subscriptions (or you will not be able to do so once it has expired)
- Modify the order on woocommerce.com so that Product Add-Ons expired last week.
- Go to wp-admin > WooCommerce > Dashboard > Inbox and make sure you have a note that the Product Add Ons subscription expired.
- Set the Product-Add Ons subscription to inactive on wp-admin > WooCommerce > Extensions > WooCommerce.com Subscriptions
- Go to wp-admin > WooCommerce > Dashboard > Inbox and make sure you DO NOT have a note about the Product Add Ons subscription.

### CODE REVIEW

**Comment by belcherj** [comment]
> Verify the Connect to WooCommerce.com note is no longer in your inbox.

After connecting this was still in my inbox.

**Comment by allendav** [comment]
@belcherj - that's odd - if you try disconnecting and connecting again, does it still persist?

**Comment by allendav** [comment]
@belcherj - if the error is no longer reproducible, I would love to get this committed before it ages into conflict

**Comment by timmyc** [comment]
I did a rebase of this branch against master and had to resolve a few conflicts which I'm not sure _why_ as no conflicts are showing here, both conflicts were in 

`includes/data-stores/class-wc-admin-reports-data-store.php`

I wanted to rebase in order to use the new build utility to generate a zip file to upload to my test site 😄 

I too am running an old PHP version on my test site:

image

Which resulted in two errors in the reports data store file:

haiku2 com wp-admin plugins php activate true plug

anoterhaiku2 com wp-admin plugins php activate true plug

But after I fixed those up, this is testing as expected for me. I got the connect notif when expected, and it was no longer there once connected. I'm not an admin on wc.com so I couldn't test the last two steps, but I'm okay with getting this merged in so it doesn't get too old. Seems like both you and JB tested those out.

As for the PHP 5 errors detailed above, those exist in `master` so I will open up issues for them.

**Review by timmyc — APPROVED** [review]
:boom:

image

**Pull request merged**
