### PR TITLE
Try: Fetch hook data from REST endpoint for use in client

### LINKED ISSUE #7925: Spike to investigate wrapping Settings/Product extensions HTML injection in a React app
A future plan with both Settings and Product Management is to reactify those pages and make them both faster and easier to use for the end user.

A major sticking point with recreating Settings and Product Management is supporting existing 3PD and Automattic extensions that currently generate and insert HTML into those pages.

This spike is intended to investigate what would be required to wrap the generated HTML in a way that it can be inserted into the new pages in a safe and React-friendly manner. Postbacks will also need to be considered.

- [ ] create a stub React application within Settings
- [ ] wrap a HTML insertion from an extension in some way
- [ ] insert the wrapped HTML into the React application
- [ ] provide a mechanism for posting back to the extension when the generated HTML is interacted with/submitted by the user
- [ ] verify that the same approach will work in Product Management (and Order Management if you have time)

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #7925 

This is part of an initial spike to use plugin data from existing hooks in the new Reactified pages.  This PR fetches the registered hook data from a REST endpoint and injects that into the page.

I may take a stab at an alternative approach listed below in a follow-up to see what that would look like.

## Rest approach (this PR)

**Benefits**

* Actions and filters are readily available on any page
* Very performant and no preloading of data/pages required

**Disadvantages**

* Hooks and respective scripts may be registered under `admin_init` or checking a `$_GET` param which does not get triggered under this REST route
* We may need to pass params back with the hook names to get the correct data (`do_action( 'my_hook', $some_var, $some_other_var );`)
* We need to sanitize HTML before injecting (though this is probably true of all approaches)

**Things to improve with this method**

* The endpoint should allow for filters to be retrieved (easy)
* The endpoint should allow for params to be passed to actions/filters (technically easy, potentially difficult to gather all the correct data to pass back to the server)
* Need a way to catch form data and submit (moderate difficulty if the WC hooks are correctly used, impossible if they are not being used).  This may even be possible async; capture form data, on submit post to the save hook filter, invalidate cache on success, render new action hook content.

### Overwrite WC Settings pages

**Advantages**

* Existing hooks are guaranteed to work and scripts don't need to be updated
* URLs don't change

**Disadvantages**

* Breaks React routing (I don't believe we can transition between the `wc-admin` and `wc-settings` namespace, can we?
* Not very performant given we'll probably be loading all the data from the original settings pages on top of the new data we add

### Render content to a hidden div

**Advantages**

* No fetching involved

**Disadvantages**

* Data has to be preloaded for all WCA pages which makes it a deal breaker IMO

### Screenshots

Screen Shot 2021-12-15 at 4 37 29 PM

### Detailed test instructions:

1. Add a plugin that adds data to the settings start hook:
```php
add_action( 'woocommerce_settings_start', function() {
	echo '<div>This is content generated from the <strong>server-side</strong> hook</div>';
} );
```
2. Make sure you re-run the build to trigger feature config update (`settings => true`)
2. Enable the settings feature under `wp-admin/admin.php?page=wc-settings&tab=advanced&section=features`
3. Navigate to general settings `wp-admin/admin.php?page=wc-admin&path=%2Fsettings%2Fgeneral`
4. Note the custom hook content is shown

### CODE REVIEW

**Comment by ilyasfoo** [comment]
I don't know how common this is, but is it possible that extensions include inline JavaScript in the hooks? I've tried with this try branch and it didn't work where it would originally. Not sure if this is worth to be considered though.

**Comment by joshuatf** [comment]
Thanks for taking a look, @ilyasfoo!

>I don't know how common this is, but is it possible that extensions include inline JavaScript in the hooks?

Great point.  Probably more common than we would like.  If they register by enqueuing scripts, then is less of an issue (though if they're expecting to be on `wc-settings` or a specific tab then we need the "Overwrite WC Settings pages" approach above).  Otherwise, we'd have to eval the scripts which I don't see as a viable or safe option.

While the "Overwrite WC Settings pages" may resolve the lack of a script being evaluated, it doesn't solve elements on the page not being ready by the time a script is executed.

```
<div class="react-container>
Still loading, but will clone elements in `.old-page-code`
</div>

<div class="old-page-code">
  <div class="color-picker" />
  <script>
    $( '.color-picker' ).colorPicker();
  </script>
</div>
```

In this example, color pickers that were cloned will not have the code executed on them.

**Comment by louwie17** [comment]
@joshuatf that is an interesting approach, but I could see it working given it is a temporary solution, until the plugins update (I assume?).
From a security point of view, do you think it could be problematic for a user to be able to trigger any action from the API? This could allow for actions to be triggered that otherwise would only be triggered under specific circumstances or under specific privileges (assuming that not everyone checks for permissions in the `add_action` call back, if the `do_action` is only triggered in a certain situation).
This point makes me lean more towards the **Hidden div** approach, aside from the HTML having to be rendered on each WCA page, although I think this would be a burden we could bear over a couple versions.

(Maybe this question doesn't pertain strictly to this issue, given we are talking about data/configuration vs injecting html) Do you think we could also use this in places like the Payment methods table in settings where a plugin can add extra columns? Where it then exposes a separate filter for the new column. I wonder if in scenario's like these a custom API would be better where we get the column names and values from the API and render it.

**Comment by joshuatf** [comment]
Thanks for the feedback, @louwie17!

>From a security point of view, do you think it could be problematic for a user to be able to trigger any action from the API?

Yes, definitely!  I have a todo note in `get_items_permissions_check` that this should be based on user capability, otherwise this could be abused.

`// @todo This should probably be limited by the given filter/hook.`

>This point makes me lean more towards the Hidden div approach, aside from the HTML having to be rendered on each WCA page, although I think this would be a burden we could bear over a couple versions.

I was starting to lean this way as well, however it's worth noting that those actions/filters are dependent on the context they're in (settings tab, order ID, etc) so we'd have to preload data for all settings, all orders, all products, etc and this would be disastrous for performance.

Overriding the WC Settings page is a more viable approach, but we do lose most of React's routing benefits this way.

>Do you think we could also use this in places like the Payment methods table in settings where a plugin can add extra columns? Where it then exposes a separate filter for the new column. I wonder if in scenario's like these a custom API would be better where we get the column names and values from the API and render it.

A custom API would always be the favorable approach over this generic hook REST API, but I think that decision boils down to whether or not the REST API is beneficial long-term or if it's a temporary stop-gap.  If the REST API is needed either way, then that's a far better option, but if we just need a couple versions of allowing some actions/filters, then I would go with the REST API.

I'll also point out that while I'm playing devil's advocate for the sake of conversation, I don't particularly like any of these approaches.  I think they introduce a lot of technical debt at best and are in reality unlikely to work well for all use cases.

**Comment by louwie17** [comment]
> Yes, definitely! I have a todo note in `get_items_permissions_check` that this should be based on user capability, otherwise this could be abused.

Aaah I missed this, that makes sense, we probably would have to keep a strict list of what actions could be triggered from the API and which permissions are required for each. If we go this route.

> I was starting to lean this way as well, however it's worth noting that those actions/filters are dependent on the context they're in (settings tab, order ID, etc) so we'd have to preload data for all settings, all orders, all products, etc and this would be disastrous for performance.

I also missed the fact that we would have to pre-load the data for all the old pages, that does indeed make this a hard sell, changing my mind on this now haha

> I'll also point out that while I'm playing devil's advocate for the sake of conversation, I don't particularly like any of these approaches. I think they introduce a lot of technical debt at best and are in reality unlikely to work well for all use cases.

Yeah, I am with you on this, I would much prefer keeping the old pages and adding depreciated notices for all the old actions, so 3PD's have time to update there plugins to use the new approach and then just doing a full swap in one of our versions.
The only caveat on this, is that there will be a delay in when we can make our switch to a reactified page, but will prevent lots of bugs that could be caused by supporting backward's compatibility for this functionality in particular.
cc @becdetat was this a consideration, or is this not possible?

**Comment by becdetat** [comment]
@louwie17 @joshuatf Great conversation happening around this, thanks :-)

> I would much prefer keeping the old pages and adding depreciated notices for all the old actions, so 3PD's have time to update there plugins to use the new approach and then just doing a full swap in one of our versions.
The only caveat on this, is that there will be a delay in when we can make our switch to a reactified page, but will prevent lots of bugs that could be caused by supporting backward's compatibility for this functionality in particular.
cc @becdetat was this a consideration, or is this not possible?

It would be nice to just drop output buffered hook output into the page, but I can see that there are plenty of edge cases and caveats where this won't work. I would be ok with:

step 1: keep old pages and add deprecation notices for old actions (have this in place for a few major versions, publish 3pd developer advisories)
step 2: (after a few major versions) remove old pages and replace with the output buffering technique, with the understanding that a) it's just for backwards compat, and b) it will have edge cases where it won't work, such as the inline JS example above.

The intention of the project is to reactify and update the settings pages which is going to take a few cycles anyway, so I think it's ok to stage it.

cc @pmcpinto

**Comment by becdetat** [comment]
I did some investigating (and wrote some code! only happens very rarely) and I feel like I understand the `dangerouslySetInnerHTML` using `exec` approach now. There is similar approach [using a range](https://github.com/christo-pr/dangerously-set-html-content/blob/master/src/index.js) that avoids `exec` which we could play with. I'm starting to feel like this could be an ok (but with acceptable danger) approach, making sure that the hooks are deprecated and we have appropriate communications in place for 3PDs to migrate to or use SlotFill/REST API.

**Comment by joshuatf** [comment]
Thanks for the input, @becdetat!  Just a heads up that there is a more comprehensive overview of the approaches at p90Yrv-2B0-p2.

> it will have edge cases where it won't work, such as the inline JS example above.

Just to make sure it's clear, I think this is not an edge case and could possibly be the majority of cases.  Here are the cases I currently see not working:

🟢  - Occurs, but not as often
🟡  - Occurs with relative frequency
🔴  - Very likely

* The inline JS mentioned above 🟢 
* Styles where selectors rely the old page structure, e.g. `.woocommerce .form-table .my-element` 🟡 
* Scripts where selectors rely on the old page structure (not just inline scripts) 🟡 
* Plugin hooks that are checking `$_GET['page']` or `$_GET['tab']` or any other URL param that most likely will not match the new URL structure 🔴 
* Plugin hooks run on `admin_init` or `current_screen` or any other hook that does not get processed during REST requests 🔴 

It is possible for plugin authors to fix up each of those issues, but for the time involved they may as well register the correct way within the new page.  I'm a little hesitant to put a lot of time into a feature that works less than half the time and will be removed in the near future.  But confirming the number of working cases with a more thorough audit of plugins may give us a better idea of how well this does or does not work.

**Comment by joshuatf** [comment]
I'm going to close this PR for now.  We can pick up discussion again if we are considering implementing.

**Pull request closed without merging**
