### PR TITLE
Fix php unit test "test_deleted_coupons" for wc >= 6.1.0

### LINKED ISSUE #8154: test-php (7.0, 5.6, latest, 6.5.9, 1.10.19) is failing
### Describe the bug

test-php (7.0, 5.6, latest, 6.5.9, 1.10.19) is failing with 

php: 7.0
wordpress: 5.6
woocommerce: latest
phpunit: 6.5.9
composer: 1.10.19

Error logs:

```
1) WC_Tests_Reports_Coupons::test_deleted_coupons
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
-            'coupon_id' => 521
-            'amount' => 3.0
+            'coupon_id' => 522
+            'amount' => 7.0
             'orders_count' => 1
             'extended_info' => ArrayObject Object ()
         )
         2 => Array (
-            'coupon_id' => -1
-            'amount' => 7.0
+            'coupon_id' => 521
+            'amount' => 3.0

/tmp/wordpress/wp-content/plugins/woocommerce-admin/tests/reports/class-wc-tests-reports-coupons.php:430
```

Action link: https://github.com/woocommerce/woocommerce-admin/actions/workflows/test-php.yml

The latest (6.1.0) [woocommerce](https://github.com/woocommerce/woocommerce/releases) was released a few hours ago. Not sure if it causes this.

### PR DESCRIPTION
**Pull request by chihsuan**
Fixes #8154

This PR fixes the failing `test-php (7.0, 5.6, latest, 6.5.9, 1.10.19)` CI. 

In WC Core 6.1.0 Coupon Data is stored consistently in the order item meta, which breaks our `WC_Tests_Reports_Coupons::test_deleted_coupons` test. 

- https://github.com/woocommerce/woocommerce/pull/31338
- [6.1.0 changelog.txt](https://github.com/woocommerce/woocommerce/blob/6.1.0/changelog.txt)

To test in local, I also fixed the `bin/install-wp-test.sh` as we did in https://github.com/woocommerce/woocommerce-admin/pull/8108.

### Detailed test instructions:

Please check the https://github.com/woocommerce/woocommerce-admin/runs/4798506778?check_suite_focus=true

To test manually:

1. Rebuild the php-test-suite docker image: `cd docker/wc-admin-php-test-suite && docker build . -t wc-admin-php-7-test-suite-phpunit:1.2.2`
2. Run php tests with wc 6.1.0: `WC_VERSION=6.1.0 npm run test:php` to verify the issue is fixed.
3. Run `docker-compose down -v` to make sure we can get a new db in the next step. 
4. Run php tests with wc 6.0.0: `WC_VERSION=6.0.0 npm run test:php` to verify old versions still work as epxected.

no changelog

### CODE REVIEW

**Review by ilyasfoo — COMMENTED** [review]
Thanks for working on this, @chihsuan! Unfortunately, I had troubles running `WC_VERSION=6.1.0 npm run test:php` in my local. I've tried it in a fresh clone and deleted local docker images but to no avail. This is the last error that made me gave up for now:

image

**Comment by chihsuan** [comment]
> Thanks for working on this, @chihsuan! Unfortunately, I had troubles running `WC_VERSION=6.1.0 npm run test:php` in my local. I've tried it in a fresh clone and deleted local docker images but to no avail. This is the last error that made me gave up for now:
> 
> image

@ilyasfoo Thanks for the test. Can you try `WP_VERSION=5.6 WC_VERSION=6.1.0 npm run test:php`? 

I just found that the default `WP_VERSION` is 5.4 in the `docker-compose.yml` which does not support 6.1.0 WC. (I didn't notice that because I set the WP_VERSION in my local env config. 😢 )

You should be able to see something like below:

Screen Shot 2022-01-17 at 18 06 49

If you don't see the `Plugin 'woocommerce' activated.` line, there should have some error messages.

Screen Shot 2022-01-17 at 18 07 23

Screen Shot 2022-01-17 at 18 12 59

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
@chihsuan Thanks, I was able to get the test to run.

I'm wondering if you also have checked the implication of the coupon deletion change in WCA. In particular, I've found this [line](https://github.com/woocommerce/woocommerce-admin/blob/fe9a209e7f54b8aaaaf3738833e786c044fb0302/src/API/Reports/Coupons/DataStore.php#L165) to invoke `$coupon->get_id()` which I don't think was affected but just making sure. (If there's an issue with this, we don't have to address it here, just submit a new issue)

Also, I think we can simplify the test a little. Previously, we have coupon_2 and coupon_3 because coupon_2 will not have metadata while coupon_3 will have. Since the change, I think it's better for us to remove the coupon_2 altogether since that will not be the case any longer because all coupons will have metadata. What do you think?

**Comment by chihsuan** [comment]
@ilyasfoo Nice!

> I'm wondering if you also have checked the implication of the coupon deletion change in WCA. In particular, I've found this line to invoke $coupon->get_id() which I don't think was affected but just making sure. (If there's an issue with this, we don't have to address it here, just submit a new issue)

Yeah, I think it's not affected, but to verify, I'll test it today.


> Also, I think we can simplify the test a little. Previously, we have coupon_2 and coupon_3 because coupon_2 will not have metadata while coupon_3 will have. Since the change, I think it's better for us to remove the coupon_2 altogether since that will not be the case any longer because all coupons will have metadata. What do you think?

Do we need to include it for testing with the previous WooCommerce versions? If it's not needed, I think we can remove it.

**Comment by ilyasfoo** [comment]
>Yeah, I think it's not affected, but to verify, I'll test it today.

Thank you!

>Do we need to include it for testing with the previous WooCommerce versions? If it's not needed, I think we can remove it.

Yup, I'd prefer forward-looking tests. Since the feature is also not being actively worked on at the moment, it's the better decision I think.

**Comment by chihsuan** [comment]
> Yup, I'd prefer forward-looking tests. Since the feature is also not being actively worked on at the moment, it's the better decision I think.

Okay, I've updated it in fe03492546efd450ad22d48d04bf68e9ab69a56e.  Please review again. Thanks!

**Review by ilyasfoo — APPROVED** [review]
LGTM! Thanks for fixing this @chihsuan 🚢 🚢

**Pull request merged**
