### PR TITLE
Adds GitHub templates to ensure good issue and PR descriptions

### PR DESCRIPTION
**Pull request by belcherj**
### Good Description:

This PR adds GitHub templates so it is easier to create PR's and Issues.  These templates auto-populate the description box when an issue of that type is created.

The formats added here may not be best for this repo.  Please let me know if there is too much structure, too little, asking the wrong questions.  This is meant to get a conversation going.  

 ### Changes proposed in this PR:
 
* Adds Bug Report template
* Adds Feature template
* Adds Pull Request template

 ### Clear Detailed Test instructions:
 
 * Difficult to test w/o merging.  You can see these in action at the WooCommerce.com repo
 
### Screenshots

screen shot 2018-10-10 at 10 40 16 am
screen shot 2018-10-10 at 10 39 02 am
screen shot 2018-10-10 at 10 38 52 am
screen shot 2018-10-10 at 10 38 45 am

### CODE REVIEW

**Comment by ryelle** [comment]
🎉 I was thinking about adding these recently, thanks! I like the issue & feature request templates, but I think the PR one is too formatted - I think we can add placeholder sections, but I'd rather get rid of the titles. What about something like this?

```
/\*_ @format _/

Fixes #

_Replace this with a good description of your changes & reasoning._

### Screenshots

### Detailed test instructions:

 - Ex: Open page `url`
 - Click XYZ…
```

**Comment by belcherj** [comment]
@ryelle 's changes made

**Comment by timmyc** [comment]
Great idea @belcherj - definitely makes the repo more approachable to all, and hopefully encourages participation from in the community too. Thanks for taking the time to do this.

**Review by timmyc — APPROVED** [review]
🚢

**Pull request merged**
