### PR TITLE
Add new note for the theme marketplace

### LINKED ISSUE #5955: New message: Choosing a theme?
**Title:** Choosing a theme?
**Copy:** Check out the themes that are compatible with WooCommerce and choose one aligned with your brand and business needs.
**Segmentation:** new users without Storefront installed
**Timing:** 1 day after store creation
**Cadence:** Once
**CTA leads to:** https://woocommerce.com/product-category/themes/?utm_source=inbox
**CTA label:** Visit the theme marketplace

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #5955 

This PR adds a new note about the theme marketplace.

### Screenshots
Screen Shot 2021-01-05 at 6 23 17 PM

### Detailed test instructions:

1. Navigate to WordPress -> Plugins
2. Deactivate WooCommerce Admin and activate it again
3. Open `wp_wc_admin_notes` table and confirm a new note with name `wc-admin-choosing-a-theme`
4. Navigate to WooCommerce -> Home and confirm that you have a new note with the title `Choosing a theme?` (refer to the screenshot)

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
This looks good and tests well.

**Comment by samueljseay** [comment]
@moon0326 I went back and forth on the test instructions but I'm now certain they're wrong so just wanted to reiterate that the testing instructions should involve running the `wc_admin_daily` job for them to turn up.

**Comment by moon0326** [comment]
@samueljseay Hey Sam, thank you for the review and suggestion. I figured deactivate -> activate runs the notes again. Could you please teach me how to run `wc_admin_daily` manually? That would be nice for testing purposes.

**Comment by samueljseay** [comment]
@moon0326 yeah sure :)

1. Install plugin "wp control"
2. Go to tools > cron events
3. There is a list of all cron events. Find "wc_admin_daily" click "run now" and the cron will run immediately.

**Comment by moon0326** [comment]
ttr

> @moon0326 yeah sure :)
> 
> 1. Install plugin "wp crontrol"
> 2. Go to tools > cron events
> 3. There is a list of all cron events. Find "wc_admin_daily" click "run now" and the cron will run immediately.

Thank you so much! I think that's better than using eval with WP CLI :)

Thank you for the introduction of wp control plugin. It looks neat!

**Pull request merged**
