### PR TITLE
Remove the use of Dashicons and replace with `@wordpress/icons` or `gridicons`

### LINKED ISSUE #3613: Use @wordpress/icons instead of Dashicon
**Is your feature request related to a problem? Please describe.**
Yesterday, Riad (from the Gutenberg team) and I, made some progress on the new icon package, mainly https://github.com/WordPress/gutenberg/pull/17055, https://github.com/WordPress/gutenberg/pull/19809, and https://github.com/WordPress/gutenberg/pull/19808
Icons are now tree shaken, we should start migrating away from Dashicon toward a more modern approach, the previous approach included the whole dashicon (90kb) set each time you used a single Icon, this prevented us in WooCommerce Blocks from using some of the components in the frontend, it also caused large bundle sizes.

**Describe the solution you'd like**
Migrate to `<Icon icon={ name } />` instead of `<Icon icon="name" />`, if the icon is already migrated in Gutenberg, then use the new one, if not, wait until it’s moved or help move it, [example](https://github.com/WordPress/gutenberg/blob/a5e0740063a2a0c8dc9a9b845ef0a2c7c99907a9/packages/icons/src/library/check.js).

Depending on how you use WordPress packages, you might need to change the way you bundle packages to get extra gains on the UI, so instead of relying on icons in external (as in `wp.icons`, which is not possible) you will have to call it directly from npm.

**Should this be prioritized? Why?**

There is no urgent prioritization, but it's something to work on by time.

**Additional context**

### PR DESCRIPTION
**Pull request by louwie17**
Fixes #3613 

As suggested in #3613, this PR removes the use of Dashicons anywhere within wcAdmin and makes use of the `@wordpress/icons` or `gridicons`, as they are tree-shakeable.
This does actually make our bundle size a little bit bigger, as the icons are individually imported, and we used `window.wp.components` for dashicons.
~~*Note: I currently can't seem to get the wordpress/icons tree shaking to work, and it is pulling in the entire library.~~
It seems all good now.
cc'ing @senadir & @samueljseay incase either of you know what I am missing, this is what a [quick gif of the package](https://d.pr/i/55WkM8) compiled into the `app/index.js`. 

### Detailed test instructions:

- Load this branch
- Check the updated icons, there are quite a few
    - The android banner app dismiss icons (I [uncommented this condition](https://github.com/woocommerce/woocommerce-admin/blob/main/client/mobile-banner/index.js#L44), and [removed display none](https://github.com/woocommerce/woocommerce-admin/blob/main/client/mobile-banner/style.scss#L27)) 
    - The move up/down and trash icons in the Dashboard overview (click on the ellipsis)
    - Remove a couple items and also click on the plus icon to add a view back in
    - Go to the products analytics page and select a custom date (the calendar icons should show)
    - Icon in shipping label I added a `true ||` for testing purposes[ here](https://github.com/woocommerce/woocommerce-admin/blob/main/src/Features/ShippingLabelBanner.php#L88)

### CODE REVIEW

**Comment by louwie17** [comment]
The only icon that looked a little different from the dashicons was the calendar icon, cc'ing @elizaan36 if this is ok? We should otherwise be able to add the dashicon calendar icon to the `wordpress/icons`.
Screen Shot 2021-05-19 at 10 51 52 AM

**Comment by elizaan36** [comment]
I think the updated WordPress icon looks way better and simpler than the Dashicons one.👍

**Review by samueljseay — APPROVED** [review]
Looks awesome to me. Thank you @louwie17 this is really high impact! 🚀

**Comment by samueljseay** [comment]
Note, you'll just need to merge recent changes to work around e2e issues

**Pull request merged**
