### PR TITLE
Preventing the legacy coupons page from being readded when the naviga…

### LINKED ISSUE #5330: Navigation: Marketing menu items from WCA not added
WooCommerce Admin registers some menu items around Marketing.  The newly added Coupon page should be added to the new navigation and replace the legacy coupon page.

This will require opening a PR in WCA to handle the new menu item, but may also require a PR in this repo to allow de-registering items or overriding items with the same ID.

Screen Shot 2020-09-30 at 10 05 52 AM

### PR DESCRIPTION
**Pull request by joelclimbsthings**
Fixes #5330 

This change is to address the issue that's logged in the woocommerce/navigation repo, #122. In short, the marketing team has recently removed the Coupons page from the main `WooCommerce -> Coupons` into `Marketing -> Coupons` instead. However, to assist people in find it in it's new place it's actually re-added into the original spot based on a few conditions with a note at the top of the page allowing users to dismiss it and remove the obsolete one. 

When the new navigation is in use "re-adding" the coupon page just causes it to be duplicated and sent into the general `WooCommerce -> Settings` category. We're basically just suppressing the activity if the navigation plugin is active.

I also noticed that the note pictured below can still continue to appear after the original menu was suppressed. I added a condition to prevent this behavior within `CouponPageMoved.php -> can_be_added()`. 

Note that I'm still a _little_ uncertain on whether this note could still be added before the navigation plugin was active, and consequently remain if the plugin was activated thereafter. I haven't entirely unraveled the ins and outs of the Notes, but I'm skeptical that this would be a real world issue. 

### Screenshots

Before:
image

After:
image

Note:
image

### Detailed test instructions:
_Note:_ This is not currently testable in this branch without merging since navigation was migrated as a feature instead of a plugin in `main`, and I adapted the code to suit this change. I temporarily merged `main` to test myself, but leaving the merge commit in this branch heavily pollutes the "files changed" on this PR, so I've rebased it back out. If anyone has awesome git powers that can resolve this, let me know!

_Cumbersome test instructions_
- Create a new branch from `main` and temporarily merge this branch (or visa versa) (see note above)
- Create new site (or ensure that the `wc_admin_show_legacy_coupon_menu` option key does not exist)
- Have the new navigation feature is enabled
- Navigate to WooCommerce -> Settings via the new nav
- You should **not** see the Coupons page listed
- Navigate to WooCommerce -> Marketing
- You **should** see the Coupons page listed
- If the pictured note appears, you may need to delete `wc-admin-coupon-page-moved` from the `wp_wc_admin_notes` table, and ensure it's not recreated

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
Just noting that once the Navigation is moved over, the check will more likely be `Loader::is_feature_enabled( 'navigation' )` instead of checking the plugin.

**Comment by joelclimbsthings** [comment]
> Just noting that once the Navigation is moved over, the check will more likely be `Loader::is_feature_enabled( 'navigation' )` instead of checking the plugin.

Right! I'd actually thought to ask about that, thanks for chiming in.

**Comment by psealock** [comment]
I'm going to mark this as `On hold` until https://github.com/woocommerce/woocommerce-admin/pull/5309 is merged

**Comment by psealock** [comment]
The Navigation code has been migrated to `main`, so this one is ready to be updated.

**Comment by joelclimbsthings** [comment]
I've updated the code to support navigation as a feature instead of a plugin, although this consequently makes this untestable in this branch since those changes are only present in `main`. I've added a note under "Detailed Test Instructions" above to note this conundrum. Let me know if there is a good way to resolve this with git powers I've yet to explore.

**Review by psealock — APPROVED** [review]
Nice one @joelclimbsthings, this is testing great and the code looks good.

>Let me know if there is a good way to resolve this with git powers I've yet to explore.

You can rebase against `main` to incorporate the latest from that branch. If there are no merge conflicts `git rebase -i main` and force pushing `git push -f origin fix/nav-122` will do the trick. I rebased locally to test this out, but didn't push. You can merge as is.

**Comment by psealock** [comment]
Whoops, I didn't mean to merge this 😅  Sorry about that

**Pull request merged**
