### PR TITLE
Add E2E tests for initial store currencies with different onboarding countries

### LINKED ISSUE #7711: Add E2E tests for locale-info.php modifications
@tpaksu commented on [Mon Jul 26 2021](https://github.com/woocommerce/woocommerce/pull/30350)

### All Submissions:

* [x] Have you followed the [WooCommerce Contributing guideline](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR contains the E2E tests for the PR #30216, to get review for that PR before the E2E tests are completed. The related change will/seems to be only affect the automatic currency selection after the onboarding process (because other occurences seem to be in deprecated functions) and the tests will contain scenarios for that area only. 

The manual testing steps are:

1. While onboarding, select Aruba as your country, and finish onboarding. If you have already finished onboarding, you can go to WooCommerce > Orders, then on the above tab drawer, choose Help > Setup Wizard, then click on the Setup Wizard button to re-access the onboarding workflow.
2. After you finish onboarding, go to WooCommerce > Settings > General and on the Currency select, you should see Aruban florin (Afl.) as the selected currency for that store.  

Related issue: 

### How to test the changes in this Pull Request:

1. Prepare your testing environment with `npm run down && npm run up`
2. Run E2E tests with `npm run test:e2e`

### Other information:

Parent PR: https://github.com/woocommerce/woocommerce/pull/30216
Parent issue: https://github.com/Automattic/woocommerce-payments/issues/2246

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

---

@rrennick commented on [Mon Jul 26 2021](https://github.com/woocommerce/woocommerce/pull/30350#issuecomment-886617630)

@tpaksu Your PR branch is 140+ commits behind `trunk`. It won't pass the checks until you merge in current `trunk`.

---

@tpaksu commented on [Mon Jul 26 2021](https://github.com/woocommerce/woocommerce/pull/30350#issuecomment-886636882)

> @tpaksu Your PR branch is 140+ commits behind `trunk`. It won't pass the checks until you merge in current `trunk`.

Thanks @rrennick for pointing that out, my local trunk was behind and because of that the PR's connected to it were out-of-date, I'll sync them.

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #7711

This PR adds tests for automatic currency selection after an user completed the KYC flow. The tests are checking if these country selections end with the corresponding currencies listed below:

```
Australia — Queensland => AUD
Canada — Quebec => CAD
China — Beijing => CNY
Spain — Córdoba => EUR
India — Delhi => INR
United Kingdom (UK) => GBP
```

No changelog
No interaction change

### Detailed test instructions:

- Run E2E tests locally `npm install && npx wc-e2e docker:up` and then `npx wc-e2e test:e2e`
- Check if the github action passed correctly

### CODE REVIEW

**Comment by rrennick** [comment]
@tpaksu Thanks for the ping. These changes tested fine against WooCommerce core `trunk`. I'll leave the review of this PR to the WC Admin dev team.

**Comment by tpaksu** [comment]
Thank you @rrennick for checking and redirecting it to the WC admin team!

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
Thank you for adding tests, @tpaksu! I have a few comments:

- Can you remove all changes on `changelog.txt` and add changelog to `packages/admin-e2e-tests/CHANGELOG.md` instead
- Delete `changelogs/add-7711-e2e-tests-for-different-locale-onboarding` file for the same reason above, we don't need to add changelog there. You can add the text `No changelog` to the PR description to bypass the changelog check in GitHub
- It seems the tests are a bit flaky, it fails about 2 times for every 5 runs I tried in my local. If this can be improved, it'll be great. Here's an example failure on GH (I've re-run the e2e in this PR): https://github.com/woocommerce/woocommerce-admin/pull/7712/checks?check_run_id=3865631225#step:7:1369
- And a couple of nitpicks in code:

**Comment by tpaksu** [comment]
Thanks for testing it and adding your valuable input @ilyasfoo! I've fixed your requested changes, but there's a single PHPUnit test failing every time I run the tests, I guess it's not something I did in this PR. While the function is there, both in VSCode and the test runner searches it inside the namespace, and results with throwing that error. The fix needs to be done in the WC Gutenberg Blocks plugin, so it seems out of our reach. 

> Can you remove all changes on changelog.txt and add changelog to packages/admin-e2e-tests/CHANGELOG.md instead

Done, but the editorconfig removed all trailing whitespace from the release titles inside that file, and it seems like a changed file in this PR. There is actually nothing changed.

> Delete changelogs/add-7711-e2e-tests-for-different-locale-onboarding file for the same reason above, we don't need to add changelog there. You can add the text No changelog to the PR description to bypass the changelog check in GitHub

Thanks, I've deleted the file, I didn't know we could bypass the changelog linter with "No changelog" text in the PR! Thanks for the heads up!

> It seems the tests are a bit flaky, it fails about 2 times for every 5 runs I tried in my local. If this can be improved, it'll be great. Here's an example failure on GH (I've re-run the e2e in this PR): #7712 (checks)

Yep I've found and corrected the mistake, onboarding doesn't show WCPay installation option on unsupported countries (which I learned just now) listed here https://docs.woocommerce.com/document/payments/countries/ so I've splitted the check into supported and unsupported countries. That fixed the flakiness of the tests.

I'm requesting a re-review now :) Thanks for your review 🎉

**Review by ilyasfoo — APPROVED** [review]
Thanks for the changes, @tpaksu! This LGTM 🚢

**Pull request merged**
