### PR TITLE
Docs Project: Add markdown files, docsify to render site

### PR DESCRIPTION
**Pull request by ryelle**
This is the final PR, building on #334 & #336. This PR includes setup for a docsify site and the generated markdown files (which is why the diff is so large, and between this & copying the inline comments, why I created 3 PRs).

The goal of this set of PRs is to have a documentation source that third-party devs (and us) can look at for referencing the components exported on `wp.components`. We haven't been great at keeping READMEs up-to-date, but we're pretty good at propTypes. `react-docgen` can extract info from PropTypes & inline documentation, which is what we're doing in #336. Once we have that documentation info, we build it into markdown files that live in `/docs/components`.

Now we can use [`docsify`](https://docsify.js.org/) to render the files in `/docs` in a webpage. As long as we keep the inline docs up to date, which will be easier to check in PRs, the documentation will be correct. 🎉

We can even customize the docsify page with themes & plugins, so I've added the text search & customized the theme to be woo-flavored:

docs

**To test**

- Run the docsify server locally: `npm install`, then `npx docsify serve ./docs`
- Make sure the documentation matches reality
- Change some documentation in an exported component, and run `npm run docs` to rebuild the markdown files
- The change should live-reload in docsify
- Export a new component in `client/components/index.js` (copy order-status for a simple one, change some names)
- Run `npm run docs` to rebuild the markdown files
- Check that the new component's docs are built in `/docs/components`, and that it shows up in the docsify site.

**Other notes**

- If this is merged to master, we can set up github pages to [automatically show this website](https://docsify.js.org/#/deploy?id=github-pages), so no need to host it anywhere special 👍 
- The docs generation script only builds `/docs/components`, we can manually write any other markdown files in the `/docs` dir & docsify will load it. We'll need to tweak how the sidebar is generated, though.
- `npm run docs` will now work to build the markdown files. This is not run on any commit hooks, but it could be? It might drastically slow down commits if we grow the components more…
- This doesn't handle live examples or code samples, I was thinking we might leave an `example.js` or `example.md` in each component dir, and read from that when building the markdown files, and inject the content there above the props listing.

### CODE REVIEW

**Comment by timmyc** [comment]
SO MUCH 🎉 !!!

> npm run docs will now work to build the markdown files. This is not run on any commit hooks, but it could be? It might drastically slow down commits if we grow the components more…

Seems like we could just rebuild the md files during our build process when doing releases. I'd hate to slow down merges.

> This doesn't handle live examples or code samples, I was thinking we might leave an example.js or example.md in each component dir, and read from that when building the markdown files, and inject the content there above the props listing.

Is there a pattern already established for this in Gutenberg? Seems like we should follow suit with whatever is in place there, as this will help keep things in alignment for devdocs inclusion eventually.

While trying to review locally, i'm getting the following with this branch:

```
➜  woo-dash git:(try/docs-inline-comments) ✗ npx docsify serve ./docs

No docs found, please run docsify init first.
```

and

```
➜  woo-dash git:(try/docs-inline-comments) ✗ npm run docs
npm ERR! missing script: docs

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/timmyc/.npm/_logs/2018-08-31T16_14_18_463Z-debug.log
```

**Comment by timmyc** [comment]
Never mind my errors above... super helpful to actually check out the right branch, thanks @justinshreve 😆

**Comment by justinshreve** [comment]
> Seems like we could just rebuild the md files during our build process when doing releases. 

Yeah I think that this is a good way forward, unless we can do something on post commit. Or maybe generate them on a weekly basis? We'll want to keep the GitHub site updated so we'll need to pick a cadence.

**Comment by ryelle** [comment]
> Yeah I think that this is a good way forward, unless we can do something on post commit. Or maybe generate them on a weekly basis?

Agreed. If we did try something on a github commit hook or on a weekly basis, we'd need a bot to make a commit to master or create a PR we merge, since the docs themselves live in the repo. Updating the docs as part of a pre-release plan is probably the "path of least resistance" at the moment.

> Is there a pattern already established for this in Gutenberg? Seems like we should follow suit with whatever is in place there, as this will help keep things in alignment for devdocs inclusion eventually.

No, because gutenberg is just using handwritten READMEs, while we're trying to build ours automatically. The devdocs rendering of Gutenberg components does some magic where it looks for the first code block in the README, and renders that as the example in the top section, then prints out the full README below (see [Autocomplete on devdocs](https://wpcalypso.wordpress.com/devdocs/gutenberg-components/autocomplete), [Autocomplete README](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/autocomplete)).

For our integration into devdocs, I imagine us doing something similar, where devdocs will read the `/docs/components/…` files just like it does the Gutenberg READMEs - but we need have a code block in the markdown file so that it can be pulled out and rendered on the page. The question here is where should that demo code live, since we're not hand-editing our generated markdown files (and we can't automate good examples). My suggestion is to have a separate file in each component's folder, like `example.md`, that we can copy into the generated markdown file, but I was wondering if anyone had a different idea.

**Review by timmyc — APPROVED** [review]
🎉 X 💯

**Pull request merged**
