### PR TITLE
Update the options API to allow nested properties

### PR DESCRIPTION
**Pull request by joshuatf**
In some upcoming changes with the remote payments config, we need to allow more easily edit nested options properties.  For example, many plugins don't use an option `my_plugin_enabled`, but instead use the format:

```
'my_plugin' => array (
    'other_plugin_info' => ...,
    'enabled' => 1
)
```

This PR simply allows modifying only the specified nested property while retaining other values in the option.  In the above example, you can send a request to update `my_plugin/enabled` to only update the `enabled` property.

While initially I used a `.` to delineate the nested property, I switched to `/` since I found options that use a dot in the option name while I did not find any in my DB that use a slash.

### Detailed test instructions:

1. Make a REST API request to the options endpoint `/wp-json/wc-admin/options?_locale=user`.
2. Use a slash to specify a nested property to modify:
```json
{
"my_option/nested_property": "a"
}
```
3. Make sure `my_option` contains the correct data `array( 'nested_property' => 'a' )`
4. Make another request to the same option with a different property.
```json
{
"my_option/other_property": "b"
}
```
5. Make sure `my_option` contains both values without overwriting the first  `array( 'nested_property' => 'a', 'other_property' => 'b' )`
6. Test with multiple depth levels, e.g., `my_option/level1/level2`. Properties that don't have arrays at a given index should be overwritten with an empty array.
7. Make sure no other regressions have occurred with non-nested options.

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
So the purpose is to create a shortcut from having to get the option first, update the value and send it back? Or is there a more concrete need?

This is working well for POST requests, but I think if we do this we should add GET request support as well. Do you think the added complexity is worth it?

**Comment by joshuatf** [comment]
>So the purpose is to create a shortcut from having to get the option first

@psealock This is correct.  In the case of the remote payments gateway, most of these properties are nested in a parent option.

Currently for this to work properly, we would need to:
1. Get the parent option. `my_option`
2. Wait for resolution to finish.
3. Merge the data for the nested property in the parent option on the client. `const updatedData = { ...previousValue, nested_property: 'new value' };`
4. Update the parent option with all the data. `updateOption( 'my_option', updatedData );`
5. Hope that async requests are being made to a common parent option as they could overwrite each other's data.  Updating two keys in the same option would cause this issue, which is very common for payment/shipping settings:

```
// Assume previousValue = { existing_property: 'value' }
const updatingProperty1 = { ...previousValue, nested_property1: 'new value' };
...
const updatingProperty2 = { ...previousValue, nested_property2: 'new value' };
// Final value of option { existing_property: 'value', nested_property2: 'new value' }
```

Aside from complications behind conflicting async data updates, this is also going to represent some challenges with remote payments where the parent option will not be readily available and we can't write custom logic to merge said data.

With this update, the new steps would be:

1. Send an update to `my_option/nested_property` with the data only for the nested property.

>This is working well for POST requests, but I think if we do this we should add GET request support as well. Do you think the added complexity is worth it?

I'm not opposed to doing this.  Though the `GET` requests don't carry similar performance issues or async problems, it might be a nice shortcut to have.

**Comment by psealock** [comment]
>Aside from complications behind conflicting async data updates, this is also going to represent some challenges with remote payments where the parent option will not be readily available and we can't write custom logic to merge said data.

Does the problem still exist if the parent option is edited by the conventional method? If the parent option is not readily available, I can send the following payload to update a nested property:

```
{
    "my_option/nested_property": "a"
}
```
And then the option is updated elsewhere:

```
{
    "my_option": { "hello": "world" }
}
```
This overwrites the nested property, unless of course I use a payload like `"my_option/hello": "world" `. Maybe thats ok though. Can we document it somewhere?

I imagine the next step is to create a method on the options data store to discourage use of the options endpoint directly because that would lead to stale data in the store.

I'm just thinking out loud here. Thanks for the detailed explanation, this makes more sense now.

**Review by psealock — APPROVED** [review]
This is working well and tests how I imagine it should. As I mentioned above, some kind of documentation would be good although I don't know where that might live.

**Comment by adrianduffell** [comment]
I’m not sure this is really needed. Taking a step back, I think it would be better to update third party option values using an API.

This would enable the third party to provide validation of the new value. Without validation we’re adding a risk of storing bad data, or in the worst case scenario data corruption should the third party make internal changes to their data structures.

For the remote payments config, my vote would be to modify the field values using a REST API endpoint provided by the plugin. I think it would be a safer approach overall.

**Comment by joshuatf** [comment]
>I think it would be better to update third party option values using an API.

@adrianduffell I disagree with this.  This would mean implementing a new REST API for each plugin, which would be both costly and error prone.

>This would enable the third party to provide validation of the new value.

While I agree that it would be nice to have more customized validation, we can easily add this via actions/filters in the options API and allow plugins to hook into that data.  Forcing plugins to create their own APIs and conforming to our specs seems more risky IMO.

>Without validation we’re adding a risk of storing bad data, or in the worst case scenario data corruption should the third party make internal changes to their data structures.

We already have this risk as part of the options API.  I'd argue that the inclusion of this nested property feature into the options API actually mitigates some of this risk for the reasons mentioned in https://github.com/woocommerce/woocommerce-admin/pull/6866#issuecomment-827105071.  Plugins would also be responsible for specifying these options so the potential for data corruption is entirely within the plugin's control.

This precedent is already set in core with how they update settings:

https://github.com/woocommerce/woocommerce/blob/8095f7962c32365e2fba39dd659157c889b443ad/includes/abstracts/abstract-wc-settings-api.php#L188

I think an all around better approach here would be to use the `PUT` route on `/wp-json/wc/v3/payment_gateways/<id>` to update individual settings.  This comes with 2 caveats though:

1. This means additional data stores.  Not a bad thing, but we need to put in the time to flesh out payment gateway data stores.  Some of this is already planned so I don't see this as a huge blocker.
2. It limits us to registered settings fields and would not allow altering other options during the payment settings update.  This may be okay, but would need to do a full audit on settings to be sure.

If you'd like we can pursue that path, though I don't see this PR as a risky API in the meantime unless you see other risks I'm not aware of.

**Comment by adrianduffell** [comment]
Thanks @joshuatf, 

> I think an all around better approach here would be to use the PUT route on /wp-json/wc/v3/payment_gateways/<id> to update individual settings.

This approach sounds really good to me. By using an API it would address the concerns I had previously. 

> I don't see this PR as a risky API in the meantime unless you see other risks I'm not aware of.

I think it is risky 🙂 

I guess with any PR there is likely to be edge cases that weren’t thought of, however I think the risk is amplified here because data is being modified. I personally think the risks could be justified if there were better use-cases for it, but so far the only one identified is to modify third party options, which has further risks associated with it. So all around it is raising a number of red flags for me.

I don't want to stand in the way of the PR but I worry it promotes some unsafe practices for handling data.

**Comment by joshuatf** [comment]
>I think it is risky 🙂

@adrianduffell Understood and I don't want to merge if you think the risks are too high, but could you expand a bit more on this?  Maybe an example showing the risks of this?

>however I think the risk is amplified here because data is being modified.

Agreed that there is some risk involved in modifying data, however I think this point is invalid in this case because:

* We already have this risk with `updateOptions` and currently make changes to third-party data that could cause corruption.  This PR provides a safer way to do that without the risks that come along with asynchronous requests.
* The settings API that exists in core does exactly what we're doing here (assumes an array and replaces based on keys) - https://github.com/woocommerce/woocommerce/blob/8095f7962c32365e2fba39dd659157c889b443ad/includes/abstracts/abstract-wc-settings-api.php#L188 The one advantage the core version has is better field sanitization, which is why I hope to eventually move to that one.
* We will not be directly making these data changes.  Plugin authors define the fields and keys used.

Again, I'm very much in favor of moving to the core payment gateways API, but this will push our ability to get this feature working into the next sprint.  If there are valid concerns or cases where this PR is more dangerous than our existing logic, then I'm happy to do that and we'll rescope this sprint to include those data stores and APIs.

**Comment by adrianduffell** [comment]
> Understood and I don't want to merge if you think the risks are too high, but could you expand a bit more on this? Maybe an example showing the risks of this?

Thinking about this more, I think my concern is more rooted in the options endpoint rather than this PR.

The major risk I see is this endpoint blindly trusts client-side data. This results in issues like #6887 where existing data on the server gets stomped on because of bugs in the client.

I think a more appropriate way to handle data is through dedicated endpoints. It allows validation to be performed server-side while enabling the complexities of the storage implementation, such as nested properties, to be abstracted from the client.

This PR however brings those complexities to the client which results in a strong coupling between the client and the storage implementation. I feel like this creates a technical debt where it is difficult to make server-side changes without breaking existing clients. An example of this might be moving data away from options storage for performance reasons. However this is complex to maneuver because an unknown amount of clients across the Woo ecosystem are coded to seek this data from the options storage via this endpoint.

> Again, I'm very much in favor of moving to the core payment gateways API, but this will push our ability to get this feature working into the next sprint. If there are valid concerns or cases where this PR is more dangerous than our existing logic, then I'm happy to do that and we'll rescope this sprint to include those data stores and APIs.

I agree this PR is no more dangerous than our existing logic. This risks could be summarized as:

 1. Bugs due to the lack of server-side validation of data. 
 2. Adding technical debt.

**Comment by jeffstieler** [comment]
> While initially I used a `.` to delineate the nested property, I switched to `/` since I found options that use a dot in the option name while I did not find any in my DB that use a slash.

There's nothing stopping an option name from containing slashes.

> I think an all around better approach here would be to use the PUT route on `/wp-json/wc/v3/payment_gateways/<id>` to update individual settings.

I'm not up to speed on the remote payment gateway stuff, so perhaps I'm missing some important context. That said the `PUT` request method mentioned here sounds like The Way™️ to me. Is there a reason this isn't the easiest path forward? Are remote payment gateways not registering settings in the normal way?

If for some reason settings registration isn't possible, could we implement this PR as `PUT` behavior for our options endpoint? E.g.:

`PUT /wp-json/wc-admin/options/my_option`
```json
{
    "nested_property": "a"
}
```

> Thinking about this more, I think my concern is more rooted in the `options` endpoint rather than this PR.

Same for me. While this PR isn't any more "dangerous" than what we already have, it's a good opportunity to rethink our approach.

**Comment by joshuatf** [comment]
>Thinking about this more, I think my concern is more rooted in the options endpoint rather than this PR.

I definitely agree with you here, @adrianduffell.  

>The major risk I see is this endpoint blindly trusts client-side data. This results in issues like #6887 where existing data on the server gets stomped on because of bugs in the client.

Ya, this represents a ton of technical debt.  The original options API only allowed several options and had validation, but those restrictions were removed as some point to allow for quick iteration.

>That said the PUT request method mentioned here sounds like The Way™️ to me. Is there a reason this isn't the easiest path forward? Are remote payment gateways not registering settings in the normal way?

@jeffstieler I agree it's the best.  It's not the "easiest" because it involves some filters required server-side and new data stores, but that's also not "hard" either.

I think it represents a lot of benefits and the only downside I can see right now (aside from added time to develop) is that any settings shown on payments will have to be registered with the old settings screen (no allowance for options outside of the ones registered with the old settings API).  I _think_ there are workarounds for this, however.  Will try in another PR.

I spoke with @psealock about this though and I think he's on board with delaying things a bit to get this in place so we'll move forward with those data stores and API changes.

>If for some reason settings registration isn't possible, could we implement this PR as PUT behavior for our options endpoint? 

This is a good idea as well if the payments API doesn't work out.

**Comment by joshuatf** [comment]
Going to close this PR for the time being.

**Pull request closed without merging**
