### PR TITLE
Add tracking for the business step

### LINKED ISSUE #6491: Business features step: improve Tracks
**Description:** the experiment implemented in #5287 showed positive results. Recap here: pbIJXs-GS-p2. We're going to make some improvements in the flow and start targeting more people. Currently, we have one event that tracks the activity in the two tabs: `wcadmin_storeprofiler_store_business_features_continue`. With just this event we're not able to understand if users are dropping in the business details or in free features tab. It would be better to have two separate events.

**Acceptance Criteria:**
- [ ] We can keep `wcadmin_storeprofiler_store_business_features_continue` to track the activity in the free features tab and keep all the associated event props: `all_extensions_installed`, `install_wcpay`, etc
- [ ] Add a new one just for the business details tab. We can call it `wcadmin_storeprofiler_store_business_details_continue_variant`. 
- [ ] And this one should include all the props associated with this step: `used_platform`, `revenue`, `product_number`, `already_selling`, `used_platform_name`
Event name: `wcadmin_storeprofiler_store_business_features_link_click`
Event description: When the user clicks on one of the extensions link
Event prop: `extension_name` (value: name of the extension that was clicked)

### PR DESCRIPTION
**Pull request by samueljseay**
Fixes #6491 

Changes:

* Add a new tracking event that captures the user filling out the business details step
* Move the props tracked in the original event to the new one
* Add a tracking event for clicking extension links

I'd like to double check with @pmcpinto that I've done this correctly.

The original tracking for the event `storeprofiler_store_business_features_continue` remains but I've removed from it all the information that we capture in the new track. so this event just captures:

```
all_extensions_installed
install_woocommerce_services
install_mailchimp
install_jetpack
install_google_ads
install_facebook
install_wcpay
install_creative_mail
```

I have moved the others across to the new track: `storeprofiler_store_business_details_continue_variant`

So this new event tracks:

```
already_selling
currency
product_number
revenue
used_platform
used_platform_name
```

Currency stands out as one that wasn't originally suggested to move over, but I felt it made sense to capture here, and keep the other tracks purely related to the installed plugins.

As for the new event for tracking extension link clicks, this is straightforward and tracks just `extension_name`

### Accessibility

n/a

### Screenshots

n/a

### Detailed test instructions:

1. Make sure you have tracks logging enabled in development. Reach out if this is an issue for you
2. Go through the OBW on a fresh site, make sure you choose "US" as country and for industry choose anything but CBD
3. When you get to the "business details" step, try filling it out with various values and clicking "continue". Check that the `wcadmin_storeprofiler_store_business_features_continue` event is logged in console and has the props you expect.
4. Now choose some extensions in the "free features" step and confirm that when you click continue a track is logged with the props you expect
5. Now from "theme" step, go back to the previous step, and then choose the "free features" tab. Expand the extension list and click links found in the description for each one, confirm that a track is recorded correctly for these link clicks.

### Testing instructions

I don't think this warrants a testing instructions step? Happy to negotiate that, but I'd be more concerned that the OBW works as it currently does which would be covered by other testing.

### CODE REVIEW

**Comment by pmcpinto** [comment]
@samueljseay the tracking changes look good. Just a couple of details

Fernando implemented the inclusion of Mailpoet in the bundle in #6489, but I forgot to ask him to add an event prop to track the Mailpoet installs. Can you implement this in this PR or is it better to be implemented alongside #6489?
The event prop should be identical to the other extensions props: `install_mailpoet`: True|False

In the #6491 acceptance criteria I also included a new event: 
> Event name: wcadmin_storeprofiler_store_business_features_link_click
> Event description: When the user clicks on one of the extensions link
> Event prop: extension_name (value: name of the extension that was clicked)
Is this going to be implemented in a separate PR?
Thanks!

**Comment by samueljseay** [comment]
> but I forgot to ask him to add an event prop to track the Mailpoet installs. 

@pmcpinto no problem, I won't add that to this PR, but I'll make sure that gets done ASAP.

> In the #6491 acceptance criteria I also included a new event:

Sorry my description of this PR isn't that good, but I did indeed do the link click event here: https://github.com/woocommerce/woocommerce-admin/pull/6575/files#diff-7a83a417976ce71d8cf448c40b9317526ff3bd72919863e49e21e2d758ae18bcR44

**Comment by pmcpinto** [comment]
> I won't add that to this PR, but I'll make sure that gets done ASAP.

Thanks!

> Sorry my description of this PR isn't that good, but I did indeed do the link click event here:

NP! Thanks for the clarification :)

**Review by adrianduffell — APPROVED** [review]
Thanks @samueljseay this tested well and LGTM 🚀 

> I don't think this warrants a testing instructions step?

I tend to agree due to the complexity of testing this in the browser console.

**Pull request merged**
