### PR TITLE
Admin Notes: Add new Note suggesting Jetpack Backup to WooCommerce users

### PR DESCRIPTION
**Pull request by grassfedfarmboi**
As part of the effort to cross-promote Jetpack Backup to WooCommerce users, this PR adds a new Admin Note under the following conditions:
- Jetpack is installed
- Site does not have a Jetpack Backup product or plan
- WooCommerce has been enabled for at least a week

### Screenshots
Screen Shot 2021-03-29 at 3 36 43 pm

### Detailed test instructions:

-   Create a test site that has Jetpack and any of the Jetpack plans/products which include Jetpack Backup (e.g. Jetpack Backup Daily, Jetpack Security Realtime, etc). You can use JN.
-   Either use a test site that is more than a week old or use the following SQL to make it so (you can use [this plugin](https://wordpress.org/plugins/wp-phpmyadmin-extension/)):
```
UPDATE `wp_options` SET `option_value`=UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 10 day)) WHERE `option_name` = 'woocommerce_admin_install_timestamp';
```
-   Check out this branch and activate WooCommerce Admin.
-   Run the `wc_admin_daily` cron job. You can use a plugin like [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/).
-   Check the WooCommerce Inbox and ensure that the Note appears as in the screenshot.
-   Ensure the CTA button works as expected and takes you to the [custom landing page with the correct UTM params](https://jetpack.com/upgrade/backup-woocommerce/?utm_source=inbox&utm_medium=automattic_referred&utm_campaign=jp_backup_to_woo)
-  Remove the Jetpack Plan or change it to one that does NOT include Backup.
-  Run the cron job again and ensure that the Note no longer appears.

### CODE REVIEW

**Comment by adrianduffell** [comment]
@grassfedfarmboi Nice work on this so far, the code is looking good 👍 

Just wondering if you aware the note could be added from within Jetpack? We encourage the Woo extensions to add their own notes. It perhaps makes sense for Jetpack to do the same? I see a benefit being you would have more control over the maintenance of the note. 

There is a tutorial about it [here](https://developer.woocommerce.com/2020/10/16/using-the-admin-notes-inbox-in-woocommerce/).

**Comment by grassfedfarmboi** [comment]
@adrianduffell Thanks for the feedback! I'm just now picking this up again after returning from AFK, so apologies for the time gap.

> We encourage the Woo extensions to add their own notes. It perhaps makes sense for Jetpack to do the same? I see a benefit being you would have more control over the maintenance of the note.

Yeah, someone else pointed that out, and I started to switch to that method! But this was our first foray into Woo-anything, and after all the other new stuff, learning the quirks of a new approach was proving too costly in terms of time for right now. So we decided to stick with the work that was already done, but we'll definitely look at the extension approach in the future, and probably end up replacing this note and consolidating everything at that point.

And by the way, thanks for the way you explained the difference between _these_ Admin Notes and _those_ Admin Notes. I was still a bit confused about the divide. It seems obvious now, but thanks for clarifying that for me, haha! 😆

**Comment by grassfedfarmboi** [comment]
Ugh, sorry about all the whitespace fixes from my auto-linter. Let me know if I should undo that or if it's fine.

**Comment by adrianduffell** [comment]
@grassfedfarmboi 

> Yeah, someone else pointed that out, and I started to switch to that method! But this was our first foray into Woo-anything, and after all the other new stuff, learning the quirks of a new approach was proving too costly in terms of time for right now. So we decided to stick with the work that was already done. But we'll definitely look at the extension approach in the future, and probably end up replacing this note and consolidating everything at that point.

Sounds good, thanks for letting me know! Just reach out if you need any assistance with the extension approach in the future. 

> Ugh, sorry about all the whitespace fixes from my auto-linter. Let me know if I should undo that or if it's fine.

Hmm don't worry about it. I'll create a separate PR to fix the whitespace issues now so the diff in this PR is clearer.

**Comment by becdetat** [comment]
Hi @grassfedfarmboi 

How do I:

> Remove the Jetpack Plan or change it to one that does NOT include Backup

I've got Jetpack Backup Daily:

image

but I can't see a way to remove it.

Creating the note is working well though. I just can't get it to be actioned if I'm not using a backup module.

**Comment by grassfedfarmboi** [comment]
@becdetat Thanks for the review!

You can remove the plan in Store Admin if you have access, or you can just make another site without backup and "age" in the database it as described. But if you have any trouble, let me know, and I can send you a test key to use with the Jetpack Start GUI in MC—that's probably the easiest way to add and remove plans on the fly.

**Comment by becdetat** [comment]
Possibly I'm doing something wrong but I   can't get the note to be automatically actioned after subscribing to a plan with backups.

1. create a JN site
2. install WooCommerce
2. onboard WooCommerce, connect jetpack
3. create a test zip from this branch `npm run test:zip`
4. upload and activate the test zip
5. upload and activate the [test helper](https://github.com/woocommerce/woocommerce-admin-test-helper/releases)
6. set the date back by 10 days
7. run `wc_admin_daily`
8. The new note appears, success!
9. go to jetpack and add the Jetpack Backup Daily plan
10. run `wc_admin_daily`
11. the new note is still present - it hasn't been actioned

Everything else works well. I wonder if I'm adding the right plan for `Jetpack::is_module_activated` to work.

**Comment by grassfedfarmboi** [comment]
Ah, I understand the issue now! Let me look further into this and I'll get back to you. 👍

**Comment by grassfedfarmboi** [comment]
Got to taking a look a this today. Found a bug; fixed it; revealed another bug; working on that. Thanks y'all for your patience! 😅

**Comment by grassfedfarmboi** [comment]
Bugs fixed! I tested using your exact flow, @becdetat. You may need to visit a Jetpack page to refresh the cached plan info when adding or removing Jetpack products. (If you happen to know a super convenient method for doing that manually, let me know, but it's certainly not a blocker.)

And thaaaaaank you for telling me about the WC Test Helper!!! Oh man, what a lifesaver! 😄

**Review by becdetat — APPROVED** [review]
Looks great @grassfedfarmboi ! and it works really well. :shipit:

**Pull request merged**
