### PR TITLE
Add country validation to subscription inclusion

### PR DESCRIPTION
**Pull request by octaedro**
This is a follow-up to [PR 7734](https://github.com/woocommerce/woocommerce-admin/pull/7734) to add a country validation.

The Subscription inclusion will be [visible only for `US` stores](https://github.com/woocommerce/woocommerce-admin/pull/7734#issuecomment-937440527) and this PR adds the changes necessary to accomplish that.

The requested changes here also required a small refactor to how we handle the product types. 

No changelog is necessary.

### Detailed test instructions:

0. Checkout this branch.
1. Deactivate and delete `WooCommerce Payments` if you have it installed.
2. Go to step one of the store profiler and select `France` (or any country other than the US) as the store `Country / Region`.
3. Go to step three of the store profiler (`Product Types`) and verify `Subscriptions` is shown as a paid extension (with a price chip).
5. Check `Subscriptions` and continue with the OBW.
6. Go back to the `Home` screen by pressing `Skip setup store details` in the step one of the store profiler. Check that the task item `Add Subscriptions to my store` is visible in the setup task list.
7. Press `Add my products` in the setup task list.
8. Select `Start with a template`. Verify that the option `Subscription product` is not visible in the popup.
9. Go to step one of the store profiler and select `US` as the store `Country / Region`.
10. Verify `Subscriptions` is shown as free (without a price chip). Also, verify that the text

```
The following extensions will be added to your site for free: WooCommerce Payments. An account is required to use this feature
```

is visible at the bottom when `WooCommerce Payments` is not installed.

screenshot-one wordpress test-2021 09 30-14_12_58

11. Check `Subscriptions` and  press`Continue` and verify that the `WooCommerce Payments` plugin is installed and activated and it's not shown in the `Free features` list

screenshot-one wordpress test-2021 09 30-14_32_20

12. Verify that the `WooCommerce Payments` plugin is being shown in the `Free features` list when the store country is other than the `US`.

13. Go back to the `Home` screen by pressing `Skip setup store details` in step one of the store profiler. Check that the task item `Add Subscriptions to my store` is not visible in the setup task list. It should be visible if the store is from any country other than the US.

14. Press `Add my products` in the setup task list.
15. Select `Start with a template`. Verify that the option `Subscription product` is visible in the popup (verify that this is not being shown when the store is from a country other than the US)

screenshot-one wordpress test-2021 09 30-14_35_22

### UPDATE

15. Verify that [this error](https://github.com/woocommerce/woocommerce-admin/issues/7775) is not happening anymore.

### CODE REVIEW

**Review by louwie17 — COMMENTED** [review]
@octaedro Things were testing well, and overall the changes look great!
I just left a couple small comments, and one question in relation to the `getTaskLists` invalidation call, otherwise close to ready 👍

**Review by louwie17 — APPROVED** [review]
Thanks for the changes @octaedro, it looks great and still tested well 😄

**Comment by louwie17** [comment]
@octaedro @mattsherman these changes do look good, but it is a rather large change to be cherry-picking into our RC version. So just wanted to ask if it is necessary to cherry-pick this? and if so, if we could forgo any of the refactored changes? It might require a couple more thorough tests if we do go ahead.

**Review by mattsherman — APPROVED** [review]
Tested and works as expected. Code looks good, just a minor comment or two that doesn't need to be addressed in this PR, given that it has already been tested and reviewed and our timeline.

This PR is quite large to cherry-pick, but given the requirements and timeline, we will do so.

**Pull request merged**
