### PR TITLE
Only allow Customer Effort Score gathering if tracking is allowed

### LINKED ISSUE #5339: Customer effort score: Only show the modal if tracking is enabled
Part of #5259

The modal should only be displayed if tracking has been opted in.

### PR DESCRIPTION
**Pull request by becdetat**
Fixes #5339

This adds a condition such that if tracking is not allowed, the CES hook JS won't be added to the output. It also adds a similar condition to the `CustomerEffortScoreTracks` JS component.

### Detailed test instructions:

- With tracking allowed (`/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com`), and with `delete from wp_options where option_name = 'woocommerce_ces_shown_for_actions'` executed
- Add a new product. The CES modal should be displayed.
- Add another product. The CES modal should _not_ be displayed.
- Disable tracking and `delete from wp_options where option_name = 'woocommerce_ces_shown_for_actions'` again
- Add another product. The CES modal should _not_ be displayed.

To test the JS component, comment out the `return` in `/src/Features/CustomerEffortScoreTracks.php:61`:

```
		// Only add the JS if tracking is allowed.
		$allow_tracking = 'yes' === get_option( 'woocommerce_allow_tracking', 'no' );
		if ( ! $allow_tracking ) {
			//return;            <------ here
		}
```

### Changelog Note:

Dev: Only allow Customer Effort Score gathering if tracking is allowed

### CODE REVIEW

**Comment by psealock** [comment]
Hey @becdetat I'm a bit confused on the branches in this PR because I see changes reflected in https://github.com/woocommerce/woocommerce-admin/pull/5373 and not sure where the base branch's PR is. Should I just do a bid review of https://github.com/woocommerce/woocommerce-admin/pull/5373 ?

**Comment by becdetat** [comment]
>  I'm a bit confused on the branches in this PR

Sorry @psealock , I didn't intend for this to be reviewed yet, I should have put it in draft mode.

The spike will most likely be ready for review today, this and a couple of other PRs will be ready for review after that lands.

**Comment by octaedro** [comment]
Hi @becdetat,
I tried to follow the test instructions in my environment and on a jurassic.ninja instance, but the CES modal wasn't being displayed after adding a product.
I'm not sure if an extra step is necessary.

**Review by mattsherman — APPROVED** [review]
Tested and works as expected (after changing option name in the testing instructions to `woocommerce_ces_shown_for_actions`).

**Comment by mattsherman** [comment]
@octaedro 

> Hi @becdetat,
> I tried to follow the test instructions in my environment and on a jurassic.ninja instance, but the CES modal wasn't being displayed after adding a product.
> I'm not sure if an extra step is necessary.

The testing instructions referenced an old option name. With the new option name, `woocommerce_ces_shown_for_actions`, I was able to verify that things work as expected.

**Comment by becdetat** [comment]
> The testing instructions referenced an old option name 

Whoops, sorry about that @octaedro , and good catch @mattsherman !

**Pull request merged**
