### PR TITLE
WCPay: Update supported countries

### PR DESCRIPTION
**Pull request by timmyc**
For #6976

This branch updates the list of countries in the international roll out of WC Pay to be current with what is supplied in the issue above.

### Detailed test instructions:

I believe this functionality has been tested quite extensively, but if you please, you could go through the OBW and setup checklist on a site using countries listed in this PR to verify WC Pay is shown as an option.

### CODE REVIEW

**Comment by samueljseay** [comment]
@timmyc just checking, does US need to be included in this list? or is it included somewhere else by default?

**Review by samueljseay — COMMENTED** [review]
@timmyc just checking, does `US` need to be included in this list or is it included by default elsewhere?

**Comment by ilyasfoo** [comment]
@samueljseay Yes it's already included
image

**Comment by samueljseay** [comment]
Ah so it is, thanks @ilyasfoo !

**Review by samueljseay — APPROVED** [review]
🚀

**Comment by ilyasfoo** [comment]
Cherry picked to `release/2.3.1` in f7d0d0447afbf815b435ddfa301321540e0383bd

**Pull request merged**
