### PR TITLE
Fix Accessibility issues: tabpanel behavior, and reduced motion setting

### PR DESCRIPTION
**Pull request by emdashcodes**
This PR fixes issues one and three from #181.

* It updates the tablist to use `NavigableMenu` which supports the correct keyboard navigation (with arrows).
* It also stops the animations from running on the panel if the the reduced motion setting is turned on.

To Test:
* Load up the branch and verify that you can still interact with the tabs. Try using your keyboard to navigate between tabbable elements, then try navigating and switching between the activity panel tabs using your arrow keys.
* Go to `System Preferences > Accessibility > Display` and turn on `Reduce motion`. Use a browser like Safari, and confirm that the animations don't occur.

### CODE REVIEW

**Review by ryelle — COMMENTED** [review]
The tabs themselves work as expected now 👍  But the tab panel isn't correctly labelled or focusable, I think - I keep having trouble when tabbing away from a selected tab.

Reduced motion effect also looks good! 🙂

**Comment by timmyc** [comment]
@ryelle do the last changes in 3f1642c look good to you?

**Review by ryelle — COMMENTED** [review]
This does work, but I think technically the tabIndex, role, and aria-label should all be on the same element.

**Review by ryelle — APPROVED** [review]
Needs to be rebased now that I've merged #182, but it's working great now 👍

**Pull request merged**
