### PR TITLE
Add 2col Experiment

### LINKED ISSUE #7635: Task List UI: 2 column layout experiment
In this experiment, the home screen will default to the **two column layout** so users can view the horizontal task list layout

**Experiment name (dynamic):** `woocommerce_tasklist_progression_headercard_2col_<current month number>`
**Countries**: Australia (AU) and Canada (CA) only.

A custom segment  will need to be applied via ExPlat using the `woo_country_code` param to limit the countries. It will need to be compatible with the dynamic experiment name.

### PR DESCRIPTION
**Pull request by adrianduffell**
Fixes #7635

Implements the `woocommerce_tasklist_progression_headercard_2col` experiment to decide whether users see the single column (default) or 2 columns (treatment) homepage.

### Detailed test instructions:

- Remove the `woocommerce_admin_homepage_layout` meta option if it is set.
- Apply the `woocommerce_tasklist_progression_headercard` treatment bookmarklet or update the localStorage item value.
- Confirm that homepage loads single column by default.
- Apply the `woocommerce_tasklist_progression_headercard_2col` treatment bookmarklet or update the localStorage item value.
- Confirm that homepage loads 2 columns.

### CODE REVIEW

**Review by moon0326 — COMMENTED** [review]
Thank you @adrianduffell 👍 

It LGTM and tested well, but I have a question.

In the https://github.com/woocommerce/woocommerce-admin/issues/7635, it says` horizontal task list layout`, but the changes in this PR is for the original task list (vertical). Don't we want to apply these changes for the new Task List UI?

**Comment by ilyasfoo** [comment]
Hi @adrianduffell, just had a quick look. According to my understanding, both single-column and two-column experiments are to be utilized with the new Tasklist UI, not just the homepage default column settings:

Single-column P2: pbxNRc-WS-p2
Two-column P2: pbxNRc-ZP-p2

**Comment by adrianduffell** [comment]
Thanks @moon0326 @ilyasfoo, I think I have this working properly now by moving the logic to `layout.js` and adding a conditional check whether the main experiment run.

**Comment by moon0326** [comment]
> Thanks @moon0326 @ilyasfoo, I think I have this working properly now by moving the logic to `layout.js` and adding a conditional check whether the main experiment run.

Thank you @adrianduffell for the update 👍 

two-column layout worked as expected, but it still loads the original task list.
Screen Shot 2021-11-02 at 3 16 19 PM
I think we want to load the new Task List UI.

**Review by moon0326 — APPROVED** [review]

**Comment by adrianduffell** [comment]
Ah sorry @moon0326 , I was missing a step in the instructions 😅 

Updated now!

**Pull request merged**
