### PR TITLE
Removing grow section from local free extensions in OBW

### LINKED ISSUE #7312: Remove “Grow” extensions from onboarding profiler
### User story

As a merchant,
I so not want to have to select extensions to install during the initial setup,
so that I complete the initial setup quickly and can then install only those extensions I really need.

### Description

In preparation to move the marketing extensions into the onboarding task list, these extensions should be removed from the onboarding profile Business Details step.

Screen Shot 2021-07-08 at 2 55 25 PM

Since the task list appears to have multiple extension categories, we may want to go with a more whitelist approach from the extensions retrieved from `/wc-admin/onboarding/free-extensions`.  E.g, only show the "basics" category.

### Acceptance criteria

- [ ] The "grow" extensions should not appear in the Business Details step of the OBW
- [ ] The "Get the basics" header should be removed (keep the items under it though!)

### Tasks

- [ ] Remove the "Grow" extensions from the Business Details step of the OBW
- [ ] Remove the "Get the basics" header

### PR DESCRIPTION
**Pull request by joelclimbsthings**
Fixes #7312

Removing the grow section, and all plugins, from the local free extensions on the OBW as they're being moved to the new marketing task.

Note that this only impacts local extensions, whereas by default most will be using remote free extensions that are hosted on WCCOM. That will require another PR in that repo.

Note that I deleted entirely the `client/profile-wizard/steps/business-details/data/extension-benefits.js` file, which just seemed to be orphaned. Let me know if this is actually utilized in some way and I can restore it.

## Tasks
- [x] Remove the "Grow" extensions from the Business Details step of the OBW
- [x] Remove the "Get the basics" header

### Screenshots

image

### Detailed test instructions:

1. Ensure that the `remote-extensions-list` feature is toggled **off**
2. Navigate through the OBW until you reach the recommended business features list, and confirm that the "Grow your store" section along with related plugins are no longer displayed, as pictured.
3. Also ensure that "Get the basics" header is no longer displayed
4. Hit continue, and then confirm that only the listed plugins were installed.
5. Repeat steps 2-4 after reenabling `remote-extensions-list` feature and refreshing.

### CODE REVIEW

**Review by joshuatf — COMMENTED** [review]
Nice start on this, Joel!

>Note that this only impacts local extensions, whereas by default most will be using remote free extensions that are hosted on WCCOM. That will require another PR in that repo.

I think we can go ahead and create an allowed list in this PR for specific extension lists.  See `ALLOWED_PLUGIN_LISTS` in https://github.com/woocommerce/woocommerce-admin/pull/7383

**Comment by joelclimbsthings** [comment]
Thanks @joshuatf , done in https://github.com/woocommerce/woocommerce-admin/pull/7386/commits/864b54c9f0dfcad7831b78cb789bbd27a3db5108, and I removed the header as per the requirements. Should be ready for review 👍🏻

**Review by joshuatf — APPROVED** [review]
Looks great @joelclimbsthings!  @pmcpinto made a [comment on the original issue](https://github.com/woocommerce/woocommerce-admin/issues/7312#issuecomment-887562067) about keeping Mailpoet in both places.  I think we're going to end up creating a v2 of this REST endpoint to resolve this, but just noting here that this will occur on the WCCOM side.

We'll have a few more items to clean-up once that new endpoint is created, but this PR is testing well and LGTM in the meantime! 🚢

**Comment by pmcpinto** [comment]
@joelclimbsthings @joshuatf do you need a new issue about this?

> @pmcpinto made a comment on the original issue about keeping Mailpoet in both places

I can create one if necessary. Thanks!

**Comment by mattsherman** [comment]
> @joelclimbsthings @joshuatf do you need a new issue about this?
> 
> > @pmcpinto made a comment on the original issue about keeping Mailpoet in both places
> 
> I can create one if necessary. Thanks!

@pmcpinto Please.

**Comment by mattsherman** [comment]
@joelclimbsthings @joshuatf By merging this removal before the marketing plugin task stories were completed, don't we run the risk of shipping a release of wc-admin without the marketing plugins at all, if for some reason we were to cut a release before we completed everything else? Am I missing something? I thought we had discussed the order of implementation in planning to account for this.

**Comment by joshuatf** [comment]
@mattsherman I don't recall having a discussion around the order of implementation, but my memory may not be serving me well.

We have all the marketing tasks PR ready for review and the main one merged.  While I think this might have been better merged after all others were merged, I also feel this is a small risk and easily handled with a revert PR if for some reason those PRs don't get reviewed in time.

**Comment by mattsherman** [comment]
@joshuatf Okay. I agree that I think that in this case it seems like we will be fine. I think the first beta of wc-admin 2.6 is coming up on Tuesday, so we will just need to make sure we are in a reasonable/known state then.

**Comment by pmcpinto** [comment]
> @pmcpinto Please.
Done: #7449

**Pull request merged**
