### PR TITLE
Fixes number formatting on charts

### LINKED ISSUE #516: Non Revenue Data Points In Charts
Thanks to #504, we now have non revenue data in analytics. (Average items per order, and total orders)

At the moment, even if a user has selected one of these non revenue based data in a summary numbers, the chart continues to render the revenue symbol before the data. 

To re-produce: In master, select the orders report. Select the average items per order, or total orders summary numbers. Note the data in the chart:

**Example**

screen shot 2018-10-12 at 7 58 44 am

- [ ] Remove revenue symbol from y-axis tick for non revenue data
- [ ] Remove revenue symbol from tool tip data
- [ ] Round the average items per order decimal in the tool tip per #515 

cc @greenafrican @Aljullu @belcherj

### PR DESCRIPTION
**Pull request by belcherj**
/\*_ @format _/

Fixes #516 

Adds formatting functions where neccesary to show correct number formats on graph.

### Screenshots

screen shot 2018-10-15 at 2 30 40 pm
screen shot 2018-10-15 at 2 30 46 pm

### Detailed test instructions:

 - Go: /wp-admin/admin.php?page=wc-admin#/analytics/orders?period=month&compare=previous_period&chart=orders_count
 - Observe correct formatting on charts

Note:  This function would probably be best in a utils somewhere.  Where is the best place to put it?

### CODE REVIEW

**Comment by belcherj** [comment]
The problem is that in some places we need the D3 format: '.3s' and in some places we need a string format.  Thinking through how to make this work with one param.

**Comment by timmyc** [comment]
Just took the branch for a spin and I'm getting the following in the console:

image

**Comment by belcherj** [comment]
Weird:  charts: PropTypes.array.isRequired,

**Comment by belcherj** [comment]
Could you give it another try?

**Review by timmyc — APPROVED** [review]
All good now. Thanks @belcherj

**Pull request merged**
