### PR TITLE
Try: Consume remote payment methods on frontend

### LINKED ISSUE #6851: Remote Payment Recommendations: Hook up individual methods
Render the payment method setup using data from `/wc-admin/onboarding/payments`.

Screen Shot 2021-04-22 at 2 59 14 PM

Below are relevant parts of the schema:

```
"fields": [ // Fields to be shown during the configuration step.
	{
		"type": "text",
		"label": "Client ID",
		"validate": "/([A-Z][a-z]+)/", // Regex to validate the input value.
		"option": "option_name" // An option to fetch and prefill this field as well as update.
	},
	{
		"type": "text",
		"label": "Secret Key",
		"validate": "/([A-Z][a-z]+)/",
		"option": "option_name"
	}
],
"plugins": [ "hello-dolly" ], // An array of plugin slugs to be installed.
"imageUrl": "https://…", // URL to method logo.
"manageUrl": "admin.php?page=wc-settings&section=...", // URL to manage the payment after configuration.
"connection": {
	"url": "/wp-json/my-extension/get_connection_url", // A REST endpoint which returns data for the connection URL.
	"property": [ "myProperty" ]
}
```

### PR DESCRIPTION
**Pull request by joshuatf**
This PR is a preliminary look at how that remote payment methods would be hooked up to the frontend.  This will help us better shape the schema required for various methods.

This PR does not (follow-ups):

* Include a data store for payment methods.
* Remove existing method files and clean up unused payment items.
* Handle enabled payment methods in the task list.
* Handle connection flows.

### Screenshots
Screen Shot 2021-04-22 at 6 15 51 PM
Screen Shot 2021-04-22 at 6 15 45 PM

### Detailed test instructions:

1. Install and activate https://github.com/joshuatf/remote-payments-tester
2. Note that `PayFast` is fetched and included under the payments task when the store country is set to South Africa.
3. Click `Set up` and note the `PayFast` fields are also included.
4. Optionally rebase with https://github.com/woocommerce/woocommerce-admin/pull/6866 for option saving to work as expected.

### CODE REVIEW

**Review by psealock — COMMENTED** [review]
Nice @joshuatf, a question comes to mind: How does will this work with the feature flag? The feature flag is a nice way to develop behind the safety of the flag, but I'm wondering if a feature branch may have to work in this case? Otherwise, we'd have to leave the old logic in place because the `remote-payment-methods` flag isn't enabled for core or plugin.

**Review by psealock — APPROVED** [review]
This is really cool to see all the logic removed from the client in favour of the rule processor! This is working as expected according to instructions. Approving, but I suppose it depends how you want to handle the feature flag/feature branch question if you want to merge this.

**Comment by joshuatf** [comment]
@psealock Thanks for the review!

I updated this to a separate folder `RemotePayments/` so we can use the feature flag and toggle back to the old feature.  This results in a good amount of duplication, but it should be temporary and we can phase out the old payments when we're ready. 
 Sound like a good plan to you?

Would you mind giving this a quick look?  Made a couple small changes to the payment component names and where logic lives, but should be more or less the same as before.  🤞

**Review by psealock — APPROVED** [review]
The re-organisation looks great. I'll be looking forward to seeing the removal of LocalPayments and its relevant files soon 😄 

I think at some point the check for `window.wcAdminFeatures[ 'remote-payment-methods' ]` could determine if the config is derived from endpoint or a local copy.

**Comment by adrianduffell** [comment]
Was SlotFill considered for this? 

Just looking at this PR via #6866 and noticed it seems to be overlapping with work started for the WC Pay configuration in PR #6755. In this PR there was a discussion around using SlotFill. If I could tldr; concerns were raised about using an object schema to configure the UI. Some of those concerns were that it is not flexible and places a burden on WC Admin to write features for other teams. Instead SlotFill was proposed as an alternative. 

cc @samueljseay who was the main advocate for SlotFill in this discussion.

**Comment by joshuatf** [comment]
@adrianduffell `SlotFill` is still planned here and it does appear there's a large amount of overlap.

The remote JSON would still be responsible for returning the specs/config, but we have `SlotFill` planned for both default payment gateways as well as a solution for WC Pay.

https://github.com/woocommerce/woocommerce-admin/issues/6853
https://github.com/woocommerce/woocommerce-admin/issues/6868

>Some of those concerns were that it is not flexible and places a burden on WC Admin to write features for other teams. Instead SlotFill was proposed as an alternative.

💯  - Most of our work will be around moving non-generic payment steps to the plugins.  However, we do have a bit of a catch-22 with WC Pay as the initial WC Pay card can't be slotfill'ed by WC Pay until it has been installed.

Our current solution is to keep the initial list item for WC Pay somewhat coupled to WooComerce Admin, but moving as much as possible to the config and `SlotFill`.  Open to suggestions if you know a way to also decouple the list item card here as well.

**Pull request merged**
