### PR TITLE
Updated copy in task lists

### PR DESCRIPTION
**Pull request by elizaan36**
Made updates to copy and punctuation to be more conversational and consistent.

- Home screen task list: Changed articles from "my" to "your" to match with onboarding and elsewhere in WooCommerce, updated the task list title to be more motivational, and tweaked copy for some tasks to be more readable
- Products task list screen: Changed "Migrate" to "Import from another service" for more approachable language, and added "via CSV" to the other Import option
- Removed periods from success messages (CreateNotice). Short helper text doesn't need a period

Home screen task list
image

Have a look and let me know if you see any other copy that could be improved.

cc @pmcpinto

### CODE REVIEW

**Review by samueljseay — APPROVED** [review]
All the copy changes look great, I'll just fix up the JS lint for you

**Comment by pmcpinto** [comment]
Looks good to me :shipit:

**Comment by samueljseay** [comment]
There are some tests to fix too, I'll do that.

**Comment by elizaan36** [comment]
thank you so much @samueljseay - sorry for the extra work, I'll remember to go through all the tests next time.

**Pull request merged**
