### PR TITLE
Remove googlefonts/material icons. Migrate to @wordpress/icons and gridicons

### LINKED ISSUE #4472: Remove GoogleFonts from Woocommerce admin (fonts.googleapis.com)
Hi,
I like new Woo admin, great job! 

There is one thing that bothers me. I would be happy if you removed GoogleFonts. I have several reasons for that:

1. They are **not essential, just a cosmetic**. 
2. It is **additional request** for external domain (it **slows down the performance**).
3. It's (potential) **3th party tracker**.
4. Requests to Google's servers **increase GDPR complexity**.
5. Our company's **firewall block similar requests** so I see [this](https://i.imgur.com/m3omwX4.png).

 Suggested solutions:

1. **Use native Wordpress / Woocomerce** [icons](https://developer.wordpress.org/resource/dashicons/#menu) instead.
2. **Bundle the icon font with Woocommerce plugin**
3. Give people an **option to opt-our from using GoogleFonts** in Woo settings.

What's do you think?

### PR DESCRIPTION
**Pull request by samueljseay**
Fixes #4472

There is lots of good rationale for dropping google fonts / material icons. See the original issue for details.

I have tried to first and foremost use `@wordpress/icons`, but if there was nothing similar there I have used gridicons. 

I'll post some screenshots of the different areas I've updated because some are departures.

cc @elizaan36 could you take a look at this?

#### The product management setup task (probably the biggest departures are here):

Screenshot 2021-02-16 at 3 07 05 PM

Here is the **old** for that one:

Screenshot 2021-02-16 at 2 28 20 PM

#### The theme preview:

Screenshot 2021-02-16 at 2 12 48 PM

This one looks almost identical to the original.

#### The analytics search box:

Screenshot 2021-02-16 at 2 25 28 PM

#### One of the "business details" a/b tests:

Screenshot 2021-02-16 at 2 51 57 PM

### Detailed test instructions:

1. Go to the product management setup task and see how the icons look. the chevrons, the icons on the left hand side etc (see the screenshot above)

2. Preview a theme. To do this, go through the OBW to the theme step, then click the "live demo" button. You should see the device icons in the top right of the screen.

3. See how the search icon looks in the select control. Go to `Analytics > Coupons`. Inspect the search box at bottom of screen. (See the screenshot above for reference.)

4. For the business details a/b test go through the OBW and make sure to choose US as location and industry of fashion or health and beauty, once you get to the business details step, there is a popover that appears if you hover over the info icon. Confirm the info icon and check marks in the popover look good.

### CODE REVIEW

**Comment by elizaan36** [comment]
hey @samueljseay - Just checked this out and besides the small note on hover states on the products task list (that we chatted about in Slack) this is looking ace.💯

**Comment by samueljseay** [comment]
@elizaan36 so that behaviour was accidental it seems. every item's title in that list happened to be wrapped in a link except the first one.

Since we agreed they should all look "link like and clickable" on hover, I have changed the style to ensure that they are always blue on hover. Could you take another look?

**Comment by elizaan36** [comment]
Looking good! The links and icons staying blue on hover definitely feels more actionable.

**Review by psealock — APPROVED** [review]
Nice clean up here @samueljseay, thank you!

I had a run through the screens and didn't find anything out of place. Code changes look good and my search for any left over material icons or google fonts remnants did not find anything :shipit:

**Pull request merged**
