### PR TITLE
Uses PHPCBF to autofix warnings and errors

### PR DESCRIPTION
**Pull request by belcherj**
Uses PHPCBF to fix all autofixable errors and warnings in the project. 202 in 25 files

### Detailed test instructions:

 - From the command line run PHPCBF: ./vendor/bin/phpcbf --standard=phpcs.xml.dist $(git ls-files | grep .php$)
 - Was anything fixed? It should not have been.

### CODE REVIEW

**Comment by belcherj** [comment]
There will be no way to merge this without ignoring PHPCS errors, which existed before this PR or fix all the errors.  My inclination is to merge this PR as it is already huge and fix those errors at a later time.

**Comment by ryelle** [comment]
>  My inclination is to merge this PR as it is already huge and fix those errors at a later time.

I agree, but if we merge this, will all future PRs also fail until we fix the PHP issues? or is travis only checking changed files?

**Review by ryelle — APPROVED** [review]
Changes seem to be mostly alignment-related, a scan of the PR looks good. Also did some light testing (clicking around), all still works.

**Comment by belcherj** [comment]
@ryelle If you edit a file that has errors your pre-commit hook will fail as well as travis.  This PR just cleans up a lot of them so the chance of that happening is lower.

**Pull request merged**
