### PR TITLE
Adds php compatibility range for phpcs

### PR DESCRIPTION
**Pull request by belcherj**
Adds a range of PHP version compatibility to test against. It will now only test compatibility for 5.2 and greater.

### Detailed test instructions:

 - Run phpcs

### CODE REVIEW

**Comment by timmyc** [comment]
Does this match up with the same value that exists in `woocommerce/woocommerce`?

**Comment by belcherj** [comment]
Yes, double checked with @claudiulodro

**Review by timmyc — APPROVED** [review]
🚀

**Comment by claudiosanches** [comment]
@belcherj this has been duplicated on this PR.

screenshot from 2018-11-26 16-17-30

**Pull request merged**
