### PR TITLE
Dashboard: Add Top Products block.

### PR DESCRIPTION
**Pull request by timmyc**
For #108 

This branch implements a `TopSellingProducts` component for use on the dashboard. Currently the component is using mock data as the endpiont for this report is still under development.

dashboard woo test woocommerce 2018-08-08 16-54-36

__Questions / Caveats__
- I opted for adding the concept of `isCompact` to the table component to hide pagination for usage on the dashboard like this, but not certain if this is the best approach.
- While looking at the code in PR format here, seems like `lib/numbers` should have tests 😄 
- This particular component will also need to query the API for product data since the`reports/products` endpoint only returns `product_id`
- Since this use case only has five records shown, I have opted to disable sorting on the table... sorting 5 rows of data seems overkill, and if we have multiple compact tables on the dashboard that could get interesting with query params to track sorting.

__To Test__
- Open up the dashboard and behold the mock data!

### CODE REVIEW

**Review by jameskoster — DISMISSED** [review]
Unable to  get my local env running atm to test properly, but here are some cosmetic changes based on card content;

* Links should be purple and regular weight
* On that note, the entire row should act as a link. IE highlight on hover.
* Numerical cells (and column headings) should be justified right

**Comment by ryelle** [comment]
> I opted for adding the concept of isCompact to the table component to hide pagination for usage on the dashboard like this, but not certain if this is the best approach.

You can use `Table` directly, inside a card – that's why I made sure to export the individual table components too. You'll loose the column toggle, but I'm not sure that's really useful on this view anyway

> if we have multiple compact tables on the dashboard that could get interesting with query params to track sorting.

Yeah, the query params don't expect multiple tables on a page. Maybe each table should have a link off to the full report, and users can sort the tables there?

re @jameskoster's feedback – none of the tables are styles "correctly" yet, I wouldn't worry about that for this PR - I opened a new issue for updating the style so we don't miss it #286

**Comment by timmyc** [comment]
Thanks for the review @ryelle - I started down using my own card first but got excited by the built in card header and everything ;) - I'll use the table directly.

@jameskoster are you okay with waiting on the base table design updates too?

**Comment by timmyc** [comment]
Okay added in some tests, and am only using the base table component so ready for some more 👀 

RE: Linking the entire row to a specific target URL - seems like we could add an optional `onRowClick()` prop perhaps in a follow-up pr? @ryelle any thoughts there? Site stats on wpcom has the same pattern and it works pretty well... not entirely certain how that translates on an a11y side of things.

**Comment by ryelle** [comment]
> Site stats on wpcom has the same pattern and it works pretty well... not entirely certain how that translates on an a11y side of things.

The row-clicking behavior on the list tables in store-on-calypso actually broke the table behavior for screen readers 😞 because we re-cast the rows to "buttons". I haven't tested this on site stats, not sure if the same thing happens. So this is what I meant with my suggestion in #286 - we can add an onClick, but should ignore the jsx-a11y suggestions to add an aria role.

**Comment by jameskoster** [comment]
> @jameskoster are you okay with waiting on the base table design updates too?

Absolutely!

**Comment by timmyc** [comment]
Okay, on that note I'll dismiss your review @jameskoster - @ryelle are you okay with this getting merged in?

**Review by ryelle — APPROVED** [review]
Looks good now 👍

**Pull request merged**
