### PR TITLE
Fix child theme upload error

### LINKED ISSUE #4188: [GlobalStep - 4.1 RC]: "The response is not a valid JSON response" error message is displayed while uploading zip file in Themes
Steps to Reproduce:
1. Create a test site using JN. 
2. Complete initial screens.
3. On theme screen try to upload business-street.1.2.4.zip or manasa.1.0.2.zip or punte.1.0.0.zip or pushan.1.0.0.zip.
4. Click on upload button.
5. Observe that "The response is not a valid JSON response" error message is displayed.

Actual Result:
"The response is not a valid JSON response" error message is displayed while uploading zip file in Themes.

Expected Result:
Theme should be uploaded and should be visible

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #4188.

This PR seeks to fix the PHP Fatal error encountered when uploading a child theme through the OBW.

cc: @gglobalstep, @juliaamosova 

### Detailed test instructions:

- Go through the OBW to the theme step
- Upload a child theme .zip **that you do NOT have the parent theme installed for**
- Verify success and no PHP error log messages

### Changelog Note:

Fix: Installation of child theme zip files from the store setup wizard.

### CODE REVIEW

**Review by joshuatf — COMMENTED** [review]
Nice fix here!  This PR works nicely to resolve the child theme upload issue.

I'm seeing one error in the logs when uploading a child theme on this branch:

Screen Shot 2020-07-23 at 4 37 50 PM

**Comment by jeffstieler** [comment]
> I'm seeing one error in the logs

Fixed in 9deb750ca.

**Review by joshuatf — APPROVED** [review]
Thanks for the fix!  Error free and LGTM 🚢

**Comment by jeffstieler** [comment]
We should consider this for `1.4` @timmyc

**Comment by psealock** [comment]
Does this need 🍒  ?

**Comment by timmyc** [comment]
Cherry picked to `release/1.4.0-beta.2` in aec14f7

**Pull request merged**
