### PR TITLE
Move admin menu manipulation from admin_head to admin_menu

### PR DESCRIPTION
**Pull request by mattsherman**
**_Note: This PR should be tested in conjunction with https://github.com/woocommerce/woocommerce/pull/29088_**

### Changes proposed in this Pull Request:

This PR move WooCommerce Admin's admin menu manipulation from `admin_head` hooks to `admin_menu` hooks. This, along with a corresponding fix in `woocommerce/woocommerce`, addresses the issues seen when the WooCommerce admin menu is displayed in Calypso when WordPress.com's Nav Unification is enabled (currently only for Automatticians). See pbIJXs-Ee-p2 for more details.

Specifically, the following issues are fixed when using Calypso with WordPress.com's Nav Unification enabled:

- The WooCommerce submenu item gets replaced by the Home submenu item, and clicking on it correctly shows the WooCommerce Admin home screen
- The Orders count appears

When accessing wp-admin, there should be no change to the WooCommerce admin menus.

#### Before

Before admin_menu

#### After

After admin_menu

Note: The following issues will be addressed in separate PRs:

- Products menu item position: May be fixed by either https://github.com/woocommerce/woocommerce/pull/28763 or https://github.com/Automattic/jetpack/pull/18758
- WooCommerce and Products menu icons: Issue https://github.com/Automattic/wp-calypso/issues/49145; may be fixed by switching to SVG icons (issue with that: https://github.com/Automattic/wp-calypso/issues/49145)

#### General wp-admin testing without Nav Unification

1. Checkout the corresponding `woocommerce/woocommerce` branch (see https://github.com/woocommerce/woocommerce/pull/29088).
2. Checkout this branch.
3. Access wp-admin.
4. Verify that all WooCommerce admin menus appear and function the same as before.

#### Testing Nav Unification

Make your test site act like an "Atomic" site:

5. Connect Jetpack on your test site to WordPress.com.
6. Clone `wpcomsh` repo (see https://github.com/Automattic/wpcomsh for details)
7. Checkout the `add/admin-menu-request-impersonation` branch (577-gh-Automattic/wpcomsh)
8. Add a plugin to `mu-plugins` with the following line, to enable Nav Unification:

```
add_filter( 'jetpack_load_admin_menu_class', '__return_true' );
```

9. Access your connected site from WordPress.com (Calypso) and verify that the menu items appear correctly (excluding issues described above)

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Dev: Admin menu modification has been moved from `admin_head` hooks to `admin_menu` hooks.

### CODE REVIEW

**Comment by psealock** [comment]
In preparation for inclusion into wc-admin 2.0.0, I added a conditional check for WC Core 5.1 or greater in https://github.com/woocommerce/woocommerce-admin/pull/6310/commits/156dc470fdd8f14066488513974326d2bf6e0c52. Since the corresponding changes made in https://github.com/woocommerce/woocommerce/pull/29088 will be released as part of WC Core 5.1 the changes in this PR could potentially be run in environments where Core doesn't also have the right changes, ie 5.0. 

### Additional Test Instructions

1. Locally, checkout WooCommerce Core release branch [release/5.0](https://github.com/woocommerce/woocommerce/tree/release/5.0).
2. See that the changes in this PR do not cause errors or fatals.

**Comment by becdetat** [comment]
> I added a conditional check for WC Core 5.1 or greater

Thanks @psealock ! I was just testing this and mentally preparing myself to add this check.

**Comment by psealock** [comment]
Changes to WC Navigation are in this pull request off of this one https://github.com/woocommerce/woocommerce-admin/pull/6319. If this PR and the WC Core PR are merged, Navigation will be broken unless thats merged too.

**Review by becdetat — APPROVED** [review]
After a lot of messing around with SSH forwarding and building WooCommerce I have been able to test this and it works well.

**Comment by becdetat** [comment]
> If this PR and the WC Core PR are merged, Navigation will be broken unless thats merged too

@psealock I'll review #6319 now, we should be able to get it in to 2.0.0.

**Comment by becdetat** [comment]
Cherry-picked to `release/2.0.0`

**Comment by mattsherman** [comment]
Thanks for adding the version check @psealock and for testing and merging this into 2.0.0 @becdetat ! 🙌

**Comment by mattsherman** [comment]
Changelog entry has been added.

**Pull request merged**
