### PR TITLE
Add `slotFill` to Abbreviated Notification panel

### PR DESCRIPTION
**Pull request by octaedro**
This is a follow-up PR to [7017](https://github.com/woocommerce/woocommerce-admin/pull/7017)

In order to avoid filtering an array of data that turns into components, this PR aims to use `slotFill` instead.

3PD will be able to extend the abbreviated notification panel by adding their fill to the `AbbreviatedNotification` slot.

### Screenshots
screenshot-one wordpress test-2021 05 30-11_45_25

### Detailed test instructions:

-   Go to your terminal and run: `npm run example -- --ext=add-abbreviated-notification`
-   A new plugin should have been added (`WooCommerce Admin Add Abbreviated Notification Example`). Activate it.
-   A new abbreviated notification should be visible in the panel.

### CODE REVIEW

**Comment by samueljseay** [comment]
Hey @octaedro, I know we discussed me giving this an early review, its looking good and I don't see any issues. I'll just wait to see the final changes to the dependent PR before giving a final review but its looking good so far :)

**Review by louwie17 — APPROVED** [review]
This looks good @octaedro 🚀

**Comment by jeffstieler** [comment]
Could the existing abbreviated notification cards be rewritten to use the Slot? Would that allow for the removal of the duplicate `applyFilters()` call for getting the extended tasks?

**Comment by jeffstieler** [comment]
@octaedro ah, I missed that the `Slot` is only rendered when the extended task list is visible - I thought it was always rendered (and I'd argue it should be).

My thought was that if the Slot were always present, you could eliminate the second use of `applyFilters()` and render Fills instead inside the `TaskDashboard` component - but.. that component isn't always rendered, so perhaps let's just forget this suggestion for now. 😛

**Pull request merged**
