### PR TITLE
Remove tasks feature flag and old components

### LINKED ISSUE #7374: Clean up and removal of old task components
Once the new task list has been tested and is working well, we should remove the old task list and potentially the `task` feature flag as well.

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #7374 

* Enables the task list components in all environments and cleans up old components.
* Moves completion checks and tracks to `Task` and `TaskList` models.
* Updates the task `isComplete` to check for all finished tasks completed instead of previously tracked completion (this could use a quick sanity check to make sure this is the information we want).

### Detailed test instructions:

1. Switch to this branch (make sure to `npm start` again to refresh the feature flags).
2. Smoke test the task list.
3. Delete the options `woocommerce_task_list_completed_lists` and `woocommerce_task_list_tracked_completed_tasks`
4. Load the task list.
5. Make sure the above options now contain the correct completed items (list IDs and task IDs respectively)

### CODE REVIEW

**Review by louwie17 — COMMENTED** [review]
Some things that stood out after the first run through:
- It appears some of the css is missing, that might of been included in the old task list, but not the new task list, see these screenshots below
- The personalize store stay's as unfinished even if I make use of the `skip` button for uploading a logo for example. This would previously still complete the task.
Screen Shot 2021-10-01 at 10 23 35 AM
Screen Shot 2021-10-01 at 10 23 06 AM
Screen Shot 2021-10-01 at 10 22 56 AM

**Comment by joshuatf** [comment]
Thanks for the feedback, @louwie17.  It looks like we missed the main tasks `style.scss` file when copying over to the new tasks feature.  Interestingly, this didn't show for me until I cleared my cache; I wonder if cache busting is not working with our dev files or if I have a local problem.

I migrated these styles over in https://github.com/woocommerce/woocommerce-admin/pull/7736/commits/c385b0db9c4b9b62b1f05c71ef93cd3fb033ce11 and then migrated them to their respective fills in https://github.com/woocommerce/woocommerce-admin/pull/7736/commits/19354bf6fe20d50a2c44978a536999e9b4480c42.

Its worth noting that these could still be cleaned up significantly and I did find some redundant styles while moving these, but I think it's best to save that for its own PR.

**Comment by joshuatf** [comment]
>The personalize store stay's as unfinished even if I make use of the skip button for uploading a logo for example. This would previously still complete the task.

I created some methods and an endpoint to handle "actioning" a task that might be useful here in https://github.com/woocommerce/woocommerce-admin/pull/7746.  I can create an issue and follow-up on that if that sounds okay to you.

**Review by louwie17 — APPROVED** [review]
I think this is looking good @joshuatf, things are testing quite well. I did have to rebase with `main` to get the task list updates to work on the fly (without a full refresh). But in my opinion it's good to replace the task list and at a good point to do some more global testing I think.

One thing I did notice with the extended task list, they could rely on `onClick`, which didn't work with my changes, I will push up a fix for that.
I assume the new proposal is to recommend the `WooOnboardingTaskListItem` where they can handle the `onClick` themselves?

**Comment by joshuatf** [comment]
>One thing I did notice with the extended task list, they could rely on onClick, which didn't work with my changes, I will push up a fix for that.

Awesome, thank you!

>I assume the new proposal is to recommend the WooOnboardingTaskListItem where they can handle the onClick themselves?

That's correct.  You can ping @joelclimbsthings or myself if you have any trouble implementing 😄

**Pull request merged**
