### PR TITLE
Introduced new hooks for jetpack sync

### LINKED ISSUE #754: Add actions for tracking changes to wc-admin tables
Jetpack Sync and Rewind need to track all of Woocommerce's custom tables to provide reliable live backups. We need WordPress actions that we can hook into which let us know that data has changed.

Can we please have some actions added to wc-admin to allow us to follow changes on the new tables:
```
{$wpdb->prefix}wc_order_stats
{$wpdb->prefix}wc_order_product_lookup
{$wpdb->prefix}wc_order_tax_lookup
{$wpdb->prefix}wc_order_coupon_lookup
{$wpdb->prefix}woocommerce_admin_notes
{$wpdb->prefix}woocommerce_admin_note_actions
{$wpdb->prefix}wc_customer_lookup
```

This is important as a part of supporting the WordPress.com eCommerce plan that is slated for release in mid-November.

For context: https://teamisotope.wordpress.com/2018/10/29/rewind-for-woocommerce-tables-and-events/

### PR DESCRIPTION
**Pull request by claudiosanches**
Fixes #754.

Introduced new actions to help Jetpack Sync and Rewind:

- `woocommerce_reports_update_coupon`
- `woocommerce_reports_new_customer`
- `woocommerce_reports_update_customer`
- `woocommerce_reports_update_order_stats`
- `woocommerce_reports_delete_product`
- `woocommerce_reports_update_product`
- `woocommerce_reports_update_tax`

By default admin notes already have actions:

- `woocommerce_new_note`
- `woocommerce_update_note`

And updated `woocommerce_trash_note` to `woocommerce_delete_note`, since we don't control statuses for admin notes and it's possible only to permanently delete admin notes.

Other actions for when objects are excluded from data base should be introduced in #1412:

- `woocommerce_reports_delete_coupon`
- `woocommerce_reports_delete_order_stats`
- `woocommerce_reports_delete_product`
- `woocommerce_reports_delete_tax`

### CODE REVIEW

**Comment by claudiosanches** [comment]
@thingalon can you help review it? Please let me know if those actions are enough.

**Comment by thingalon** [comment]
Awesome! I'm really happy to see new hooks going in to expand our Sync capabilities. Thank you for doing this! 

I will need to add code to Jetpack to handle these hooks in the near future. Do you know when this update is likely to get released? 

I can see that this will allow me to track changes to these extra things: 
- Admin notes
- Coupon reports
- Customer reports
- Order stats reports
- Product reports, and
- Tax reports.

This looks great to me! :)

**Comment by claudiosanches** [comment]
@joshuatf works for me, probably better to read too. I'll change all hooks.

**Comment by thingalon** [comment]
> We will probably have this in our release next week. Does that work okay for you?

Absolutely. I'll look at getting this into an upcoming Jetpack release. :)

**Pull request merged**
