### PR TITLE
Sync changelog from 2.8.0-rc.2

### PR DESCRIPTION
**Pull request by mattsherman**
This PR syncs the changelog from `2.8.0-rc.2` back to `main`.

## Testing instructions

1. Confidence check - make sure changelog changes look correct.

(no changelog is needed here)

### CODE REVIEW

**Comment by mattsherman** [comment]
Putting this back in progress, as I need to fix the conflict in `changelog.txt`

**Review by adrianduffell — APPROVED** [review]
LGTM thanks @mattsherman !

**Comment by adrianduffell** [comment]
Oops, just saw it was still in progress. I'll re-review once the conflict is settled.

**Comment by mattsherman** [comment]
> Oops, just saw it was still in progress. I'll re-review once the conflict is settled.

Sorry about that @adrianduffell. I've addressed the conflict and included the updates from `rc.1` and `rc.2` as well, so this now ready for a re-review! Thanks!

**Review by louwie17 — APPROVED** [review]
LGTM 🚀  this looks good to me @mattsherman

**Pull request merged**
