### PR TITLE
Render a spinner while woocommerce_setup_jetpack_opted_in is being loaded

### LINKED ISSUE #7239: [GlobalStep] "Terms of service" link disappears from "Set up Tax" screen.
## Bug Description:
 "Terms of service" link disappears from "Set up Tax" screen when user completed the OBW setup without installing "WooCommerce Tax" and "WooCommerce shipping" plugins on Free features step.

## Environment:
Woocommerce Version : WooCommerce 5.5.0 Beta
WordPress version: v5.8-beta3-51218

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Go to OBW setup wizard.
1. Uncheck the "WooCommerce shipping" and "WooCommerce Tax" options at Free features step.
1. Complete the OBW setup.
1. Go to WooCommerce->Home.
1. Click on "Set up Tax" option on Task list.
1. Observe that  "Terms of service" link disappears after 2-3 seconds.

## Actual Result:
"Terms of service" link disappears from "Set up Tax" screen.

## Expected Result:
"Terms of service" link should be display on  "Set up Tax" screen.

## Video:

https://user-images.githubusercontent.com/41110392/123285278-87494200-d52a-11eb-8613-fd2a49746b63.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WordPress address (URL): https://slender-bison.jurassic.ninja
Site address (URL): https://slender-bison.jurassic.ninja
WC Version: 5.5.0
REST API Version: ✔ 5.5.0
WC Blocks Version: ✔ 5.3.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.0-rc.2
Log Directory Writable: ✔
WP Version: ❌ 5.8-beta3-51218 - There is a newer version of WordPress available (5.8-beta3-51224)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.0
WC Database Prefix: wp_
Total Database Size: 10.42MB
Database Data Size: 7.69MB
Database Index Size: 2.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
customize_changeset: 2
mailpoet_page: 1
nav_menu_item: 5
page: 23
post: 6
product: 19
product_variation: 7
revision: 2
shop_order: 15
shop_order_refund: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Facebook for WooCommerce: by Facebook – 2.6.0
Google Listings and Ads: by WooCommerce – 1.0.0
Gutenberg: by Gutenberg Team – 10.8.2
Jetpack: by Automattic – 9.8.1
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
MailPoet 3 (New): by MailPoet – 3.64.1
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce: by Automattic – 5.5.0-beta.1
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 3.1.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 212
Oldest: 2021-06-23 07:47:24 +0000
Newest: 2021-06-24 13:51:43 +0000

### Status report information ###

Generated at: 2021-06-24 14:29:23 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by moon0326**
Fixes #7239 

This PR preloads `woocommerce_setup_jetpack_opted_in` option to prevent Jetpack and WC Tax TOS text flickering.

The TOS text gets rendered first then we make an Ajax request to get the value of [tosAccepted](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/tasks/tax.js#L536). If the value returned is true, then `tosAccepted` becomes true and the text disappears. Since Ajax requests can take a second, the text might blink depending on the value returned. Preloading the option value fixes the problem.

### Screenshots

Screen Shot 2021-06-29 at 2 36 50 PM

### Detailed test instructions:

1. Go to OBW setup wizard.
1. Uncheck the "WooCommerce shipping" and "WooCommerce Tax" options at Free features step.
1. Complete the OBW setup.
1. Go to WooCommerce->Home.
1. Click on "Set up Tax" option on Task list.
1. TOS should not blink.

### CODE REVIEW

**Review by ilyasfoo — COMMENTED** [review]
This fix works well in terms of not flickering the text. However, I've also found a bug regarding rendering the option `woocommerce_setup_jetpack_opted_in` in tax [here](https://github.com/woocommerce/woocommerce-admin/blob/d4e981dc2de2b235c2b9f8d0d7be81cbf29b8340/client/task-list/tasks/tax.js#L536), the value it returns is either `'0'` or `'1'`. The problem is when it tries to render [here](https://github.com/woocommerce/woocommerce-admin/blob/fix/7239-tos-link-disappears-from-setup-tax-screen/client/task-list/tasks/tax.js#L292), the value actually of `! '0'` is actually `false` since its a string, when it actually should be `true`.

I'd suggest making the fix in this PR as well since it's related, but let me know if you think otherwise! The fix should be simple, I think changing the option query to `getOption( 'woocommerce_setup_jetpack_opted_in' ) === '1'` should be enough.

**Comment by moon0326** [comment]
> This fix works well in terms of not flickering the text. However, I've also found a bug regarding rendering the option `woocommerce_setup_jetpack_opted_in` in tax [here](https://github.com/woocommerce/woocommerce-admin/blob/d4e981dc2de2b235c2b9f8d0d7be81cbf29b8340/client/task-list/tasks/tax.js#L536), the value it returns is either `'0'` or `'1'`. The problem is when it tries to render [here](https://github.com/woocommerce/woocommerce-admin/blob/fix/7239-tos-link-disappears-from-setup-tax-screen/client/task-list/tasks/tax.js#L292), the value actually of `! '0'` is actually `false` since its a string, when it actually should be `true`.
> 
> I'd suggest making the fix in this PR as well since it's related, but let me know if you think otherwise! The fix should be simple, I think changing the option query to `getOption( 'woocommerce_setup_jetpack_opted_in' ) === '1'` should be enough.

Good catch @ilyasfoo 💯 I agree that the fix should be in this PR 👍 I will make an update.

**Comment by moon0326** [comment]
@ilyasfoo Sorry for the delay in response. Updated the change in https://github.com/woocommerce/woocommerce-admin/pull/7269/commits/a0cecba914853d28e9da9d2aa4dd9aed78a68e34 🙇

**Review by joshuatf — COMMENTED** [review]
Sorry for stepping in here after the first round of feedback, but would it be possible to avoid adding a preloaded option?  I think the list of preloaded options is something we should be reducing and not adding new items to where possible.

Maybe we could check if the `woocommerce_setup_jetpack_opted_in` option is being fetched so we don't flicker?

**Comment by moon0326** [comment]
> Sorry for stepping in here after the first round of feedback, but would it be possible to avoid adding a preloaded option? I think the list of preloaded options is something we should be reducing and not adding new items to where possible.
> 
> Maybe we could check if the `woocommerce_setup_jetpack_opted_in` option is being fetched so we don't flicker?

I totally agree 👍  That's a really good suggestion. I'll check to see if I can use `woocommerce_setup_jetpack_opted_in` to prevent the flickering.

**Comment by moon0326** [comment]
> Sorry for stepping in here after the first round of feedback, but would it be possible to avoid adding a preloaded option? I think the list of preloaded options is something we should be reducing and not adding new items to where possible.
> 
> Maybe we could check if the `woocommerce_setup_jetpack_opted_in` option is being fetched so we don't flicker?

I tested it by using the following code, but the delay was noticeable visually even in my local env. I totally agree that we should try our best to reduce the # of preloaded options, but I think this one should be preloaded for the use case.

```
// In render

render() {
   if (isResolving) { 
       return '';
   }
}


// Pass this to prop to render
const isResolving = isResolving( 'getOption', [
	'woocommerce_setup_jetpack_opted_in',
] );
```

**Comment by joshuatf** [comment]
@moon0326 If the delay in text is not okay in this case, then I think showing a spinner for the whole component would be appropriate until all the data needed is fetched.

We really need to be moving away from preloading altogether due to its performance impact and due to the fact that these options are preloaded on every page regardless of use.  See https://github.com/woocommerce/woocommerce-admin/issues/5690 as an example of how this is affecting the app.

**Comment by moon0326** [comment]
> #5690

Thanks, @joshuatf for the link. 'm not fully convinced that preloading options is the main cause of the low-performance issue described in the linked issue as options are autoloaded anyway 🤔 I'll look into it. It's interesting. 

I like the idea of adding a spinner 👍 I'll work on it.

**Comment by joshuatf** [comment]
>I'm not fully convinced that preloading options is the main cause of the low-performance issue described in the linked issue as options are autoloaded anyway

I don't think the loading of these options is what causes the performance issue; as you noted autoloading is enabled for most options preloaded and the WP global cache will handle database retrieval times.   I think the bigger issue is probably the pure volume of how many options we're enqueuing for assets on every single page where they're not needed.  But if you have other thoughts on what might be causing the performance issues, please do share on that issue.

Either way, reducing these to the bare minimum to reduce time to FMP should be our long-term goal and creating more meaningful REST APIs to fetch necessary data.

>I like the idea of adding a spinner 👍 I'll work on it.

Awesome- thanks!

**Comment by moon0326** [comment]
@joshuatf Added a spinner in https://github.com/woocommerce/woocommerce-admin/pull/7269/commits/63ac4ecb59ef29e914331017115a49b54f14e91d

**Review by joshuatf — APPROVED** [review]
Nice!  Testing well with and without the jetpack option opted into.  Thanks for the work here, Moon!

**Comment by moon0326** [comment]
> Nice! Testing well with and without the jetpack option opted into. Thanks for the work here, Moon!

Thank you for your suggestions 👍

**Pull request merged**
