### PR TITLE
Component - Chart: check if second x axis tick required

### PR DESCRIPTION
**Pull request by greenafrican**
Chart Master Thread: #164 

This PR ensures that there is a second x-axis tick whenever the value for the second x-axis tick changes, month, year etc. This should also work on the PR that reduces the x-axis ticks.

screenshot 2018-09-14 13 37 27

To test (once #398 is merged):
- change the date picker to a longer range like year to date or quater to date
- ensure that the chart includes the month and year for the first tick of that month
- resize the chart and see that it updates as you'd expect

### CODE REVIEW

**Comment by timmyc** [comment]
I merged #398 and rebased this branch so it can be tested out. Sorry for the force push if that messed anyone up!

**Comment by timmyc** [comment]
With #398 merged in and rebased this branch I'm still seeing some oddities:

image

**Comment by LevinMedia** [comment]
I'm seeing similar

screen shot 2018-09-14 at 11 03 51 am

**Comment by greenafrican** [comment]
@timmyc thanks for the rebase. This was expected as `params.uniqueDates` needed to be renamed to `ticks` once done or during the rebase. The trouble with too many overlapping PRs :)

**Comment by greenafrican** [comment]
I've fixed the branch mismatch in https://github.com/woocommerce/wc-admin/pull/413/commits/acb03555513e23228ba336d13e0d1696546f0e22 and will merge.

**Pull request merged**
