### PR TITLE
Drop local copy of @wordpress/notices

### PR DESCRIPTION
**Pull request by becdetat**
Discussion here: p90Yrv-2ev-p2#comment-5284

We copied `@wordpress/notices` during development of the Customer Effort Score feature so that we could quickly add features to notices/snackbar notifications without relying on them being published in Gutenberg. Now those features have been added and we can drop the local copy and just use `@wordpress/notices` directly.

### Detailed test instructions:

- Test that the customer effort score snackbar appears when performing an action such as modifying WooCommerce settings
- Test that the snackbar appears in reports when downloading the report and there is more than 25 items in the table

### CODE REVIEW

**Comment by psealock** [comment]
This is a handy resource to determine if we can drop support https://developer.wordpress.org/block-editor/contributors/versions-in-wordpress/

It looks like Gutenberg 7.6, shipped with WP 5.5 is the oldest we still need to consider. So the missing features will need to be part of 7.6 before we can remove.

**Comment by becdetat** [comment]
Thanks for this @psealock and @timmyc 

The two features were added in Gutenberg 9.6.0 and 9.4.0, which are in WP 5.7 (the latest). So it looks like we need to wait for a while before we can drop the local copy.

**Comment by timmyc** [comment]
Thanks for confirming that @becdetat - so looks like we will need to keep the work-arounds here until WP 5.9 ships, and in the subsequent Woo core release we could ship this PR.

**Comment by psealock** [comment]
Thanks for the update. We can release packages individually until that time

**Comment by ilyasfoo** [comment]
WordPress 5.9 is estimated to be released in December 2021

**Comment by joshuatf** [comment]
@becdetat @ilyasfoo Should we close this PR for now and re-open when 5.9 drops?

**Comment by becdetat** [comment]
@joshuatf I'm happy with that

**Pull request closed without merging**
