### PR TITLE
Hook up leaderboards endpoint to dashboard

### LINKED ISSUE #1972: Dashboard: Add Ability to Register Custom Leaderboards
Currently the list of Leaderboards presented in the Dashboard are [hard coded](https://github.com/woocommerce/woocommerce-admin/blob/master/client/dashboard/leaderboards/index.js#L58). Given a number of the extension's we want to add wc-admin support to are seeking to add custom leaderboards ( p75Izm-1Tp-p2 ) - it feels like a good time to start exploring this!

So the long-range goal for this issue is to allow for an entirely new leaderboard to be registered/supported from an extension. I anticipate this taking longer than one sprint to accomplish, but figured we should begin to work towards the end goal.

_Random Thoughts_
- Perhaps we can provide a "core" leaderboard endpoint that accepts date range picker arguments and outputs an object of leaderboard data, keyed by leaderboard "slug". For example if I'm making a leaderboard for "Bookings" I could hook into the API requests to the `/wc/v4/stats/leaderboard` endpoint, and add in my data for the given date range.
- Alternatively, maybe it would be easier to allow leaderboards to register a data callback method which the REST endpoint would use to assemble the data
- Do we want to limit the number of columns in leaderboard tables?
- Should we refactor current leaderboards that are built stand-alone in JS to use the new scheme?

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #1972 

Hooks up the dashboard leaderboards to the new leaderboards endpoint and allows custom leaderboards to be added via the endpoint hook.

### Screenshots

Screen Shot 2019-04-09 at 4 11 16 PM

### Detailed test instructions:

1. Go to the dashboard.
2. Check that leaderboards are shown with loading rows while being fetched.
3. Check that data is fetched and shown properly for leaderboards.
4. Check that leaderboards can be toggled on/off still and that this persists after refreshing.
5. Check that changing the rows option still affects the shown number of rows.
6. Check that changing the date range affects leaderboards.
7. Check that custom leaderboards show up here.

### Test Data

Here's a quick copy/paste example to test custom leaderboards:

```php
add_filter( 'woocommerce_leaderboards', function( $leaderboards ) {
	$leaderboards[] = array(
		'id'      => 'dragons',
		'label'   => __( 'Top Dragons', 'woocommerce-admin' ),
		'headers' => array(
			array(
				'label' => __( 'Name', 'woocommerce-admin' ),
			),
			array(
				'label' => __( 'Fire Color', 'woocommerce-admin' ),
			),
		),
		'rows'    => array(
			array(
				array(
					'display' => '<a href="#">Drogon</a>',
					'value' => 'Drogon',
				),
				array(
					'display' => 'Orange',
					'value' => 'orange',
				),
			),
			array(
				array(
					'display' => '<a href="#">Rhaegal</a>',
					'value' => 'Rhaegal',
				),
				array(
					'display' => 'Orange',
					'value' => 'orange',
				),
			),
			array(
				array(
					'display' => '<a href="#">Viserion</a>',
					'value' => 'Viserion',
				),
				array(
					'display' => 'Blue',
					'value' => 'blue',
				),
			),
		),
	);
	return $leaderboards;
} );
```

### CODE REVIEW

**Comment by jeffstieler** [comment]
I'm getting the following PHP Notices and Warnings:

```
[09-Apr-2019 19:16:53 UTC] PHP Notice:  Trying to get property 'data' of non-object in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-leaderboards-controller.php on line 216
[09-Apr-2019 19:16:53 UTC] PHP Warning:  Invalid argument supplied for foreach() in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-leaderboards-controller.php on line 216
[09-Apr-2019 19:16:53 UTC] PHP Notice:  Trying to get property 'data' of non-object in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-leaderboards-controller.php on line 87
[09-Apr-2019 19:16:53 UTC] PHP Warning:  Invalid argument supplied for foreach() in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-leaderboards-controller.php on line 87
[09-Apr-2019 19:16:53 UTC] PHP Notice:  Trying to get property 'data' of non-object in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-leaderboards-controller.php on line 153
[09-Apr-2019 19:16:53 UTC] PHP Warning:  Invalid argument supplied for foreach() in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-leaderboards-controller.php on line 153
[09-Apr-2019 19:16:53 UTC] PHP Notice:  Trying to get property 'data' of non-object in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-leaderboards-controller.php on line 281
[09-Apr-2019 19:16:53 UTC] PHP Warning:  Invalid argument supplied for foreach() in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-admin/includes/api/class-wc-admin-rest-leaderboards-controller.php on line 281
```

**Comment by jeffstieler** [comment]
Aside from the warnings, this tested well and the code looks good. Let me know when you resolve the warnings and I'll retest @joshuatf.

**Comment by joshuatf** [comment]
Thanks for reviewing @jeffstieler!  Fixed up that call to data when no data is fetched from the store; those warnings should be resolved now.

**Review by jeffstieler — APPROVED** [review]
Nice work on this @joshuatf! Code looks good and tests well _(without warnings!)_. 🚢 it!

**Comment by joshuatf** [comment]
Thanks again for the review @jeffstieler!

**Pull request merged**
