### PR TITLE
Fix#1801 sku filter issue on variation product.

### LINKED ISSUE #1801: REST API: Issue when sorting the variation products via SKU in products analytics tabs in single product
**Describe the bug**
When We have multiple orders of the same product with different variation and that both products have different SKUs at that time there is a bug in REST API so when We click on sort by SKU on the product single page on analytics at that time it gives 400 error because there is not SKU parameter in REST API.
filter=single_product page.

File wc-includes/api/class-wc-admin-rest-reports-variations-controller.php

Line 287:
$params['orderby']       = array(
			'description'       => __( 'Sort collection by object attribute.', 'wc-admin' ),
			'type'              => 'string',
			'default'           => 'date',
			'enum'              => array(
				'date',
				'net_revenue',
				'orders_count',
				'items_sold',
			),
			'validate_callback' => 'rest_validate_request_arg',
		);

It does not take sku option from order by params so it gives 400 error in the rest API response.
wc-admin

Also, the query is not set for the filter by SKU in variation in the data store files.

**To Reproduce**

1. Create a product with 2 or more variation or choose the product which has 2 or more variations.
2. Assign different SKUs to all variants
2. Place different orders of that same product with different variations.
3. Go, WooCommerce admin on analytics menu and click on products
4. Where you will see the product name(which you have ordered with different variation) and Item sold columns 
screenshot-localhost-2019 03 14-12-11-09

5. Click on that product
6. You will be able to see all products with variation
Like
screenshot-localhost-2019 03 14-14-37-46

7. Now you will be able to see both variations have different SKUs.
8. Click on SKU column to sort it.
9. You will see the following error,
ezgif com-video-to-gif (5)

10. The columns will become empty and in REST API response it wil return 400 error.
**Expected behavior**
It should Filter according to SKU in Ascending, descending flow.

**Screenshots**
ezgif com-video-to-gif (5)

**Desktop (please complete the following information):**

* OS: Ubuntu
* Browser Chrome

**Additional context**
I have fixed it and attached a PR on it.

### PR DESCRIPTION
**Pull request by ronakganatra9**
Fix#1801 sku filter issue on variation product.

Fixes #1802 

Added an SKU parameter in class-wc-admin-rest-reports-variation-controller.php
modified query params for SKU sort in datastores/class-wc-admin-reports-variations-data-store.php

### Screenshots

ezgif com-video-to-gif (6)

### Detailed test instructions:

- I have tested it after the changes and it works fine.

### CODE REVIEW

**Comment by jeffstieler** [comment]
Thanks for another PR @ronakganatra9!

> Added an SKU parameter in `class-wc-admin-rest-reports-variation-controller.php`

I see this change.

> modified query params for SKU sort in `datastores/class-wc-admin-reports-variations-data-store.php`

I only see whitespace changes in this file - can you please revert the whitespace changes and add in your query params change?

Also - it seems like your commit name still isn't matching your GitHub username. If you want to show up under [Contributors](https://github.com/woocommerce/woocommerce-admin/graphs/contributors) on GitHub, you'll need to remedy that. See: https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user

**Comment by ronakganatra9** [comment]
Hello @jeffstieler ,

Thanks for reviewing this PR and letting know me that my username was showing correctly. I have updated it now and added new commit. Please review it and let me know your feedback on it.

Guide me if I am doing wrong. 

Thanks & Regards,
Ronak

**Comment by jeffstieler** [comment]
Hi @ronakganatra9 - I'm only seeing your GitHub user get associated with this commit: https://github.com/woocommerce/woocommerce-admin/pull/1808/commits/d5906701435809c84a88a96d73b57c10e8d51b1e.

Can you perhaps try recreating the PR (new branch off master) since it seems you've sorted the username?

**Comment by ronakganatra9** [comment]
Hi @jeffstieler ,

Thanks for your reply. I am seeing that yes [d590670](https://github.com/woocommerce/woocommerce-admin/commit/d5906701435809c84a88a96d73b57c10e8d51b1e) this changes only committed with my right username and in this commit, there are 2 files are changed datastores/class-wc-admin-reports-variations-data-store.php, includes/api/class-wc-admin-rest-reports-variations-controller.php

in 1 I have added an SKU parameter and in the second file, I have added SQL query params.

Let me know if it still not proper. Then I can recreate the PR.

**Comment by ronakganatra9** [comment]
Attached a new PR #1837

**Comment by jeffstieler** [comment]
Closing this - supplanted by #1837.

**Pull request closed without merging**
