### PR TITLE
Update README.md and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ilyasfoo**
Improved our docs from my onboarding experience, in the hope to reduce frictions for new contributors.

I've added a `Common Issues` section in contrib docs, which aims to be a comprehensive list of known issues with solution or workaround that is not so obvious to discover. Although I'm not sure if this is better as a different document altogether.

Please let me know what you think!

### CODE REVIEW

**Comment by adrianduffell** [comment]
Thanks @ilyasfoo! I think the addition of the Common Issues documentation is going to be helpful.

> Although I'm not sure if this is better as a different document altogether.

I wonder if the content would better in the GitHub wiki, but with a link to it from the README? I'm thinking the wiki would be simpler to keep up to date.

**Comment by becdetat** [comment]
@ilyasfoo 

> I wonder if the content would better in the GitHub wiki

I agree with @adrianduffell. Our wiki could use some love, and this  seems like something that can and should be added to quite quickly. I've dodged the documentation issue so far by keeping a paper notebook with the tips and tricks I've picked up, which isn't ideal for sharing.

**Comment by becdetat** [comment]
Nice job on this :-D

**Comment by ilyasfoo** [comment]
Thank you for your insights @becdetat @adrianduffell! I totally agree and made a wiki [here](https://github.com/woocommerce/woocommerce-admin/wiki/Common-Issues)

**Review by adrianduffell — APPROVED** [review]
Thanks @ilyasfoo this looks good! 👍 🚀

**Pull request merged**
