### PR TITLE
Load on hold reviews in the Activity Panel

### LINKED ISSUE #1868: Activity Panel: Reviews awaiting approval do not appear in the Reviews Activity Panel
Described [here](https://github.com/woocommerce/woocommerce-admin/pull/1860#pullrequestreview-217009429) by @psealock and @joshuatf.

> I see the unread indicator appear on comments that are pre-approved or once they are approved, but not ones that are awaiting approval. It seems to be a good thing to tackle in a follow up PR.

> Noted the same issue @psealock did with unapproved reviews, which we'll definitely want to follow up on since those are probably more "actionable."

### PR DESCRIPTION
**Pull request by Aljullu**
Fixes #1868.

In addition to approved reviews, load also on hold reviews in the Activity Panel.

### Screenshots
image

Detailed test instructions:
- Go to _Settings_ > _Discussion_ and check _Comment must be manually approved_.
- Create a product review.
- Go to any WooCommerce Admin page and verify an unread indicator (red dot) appears next to the _Reviews_ tab of the Activity Panel.
- Click on the tab and verify the new review appears and is marked with a red dot.

### CODE REVIEW

**Review by jeffstieler — COMMENTED** [review]
Code looks good, and tests well. I just want to make sure that it's expected that the indicator disappears from the "on hold" review here:



If that's expected, consider this approved!

**Comment by Aljullu** [comment]
> I just want to make sure that it's expected that the indicator disappears from the "on hold" review here:

That's a good point. @timmyc and @LevinMedia what are your thoughts here? Should the _Reviews_ panel mark reviews as unread only when they need to be approved, only when they are unread, or they should be marked as unread in both cases?

**Comment by LevinMedia** [comment]
@Aljullu I'm thinking both

**Comment by Aljullu** [comment]
> @Aljullu I'm thinking both

In that case, reviews that are not approved should be sorted on top of approved reviews, even when they are older, right?

**Comment by Aljullu** [comment]
@jeffstieler I updated this PR so 'on hold' reviews are always marked as unread. The only issue is we need to perform two different API requests in order to detect if 1) there are new reviews 2) there are 'on hold' reviews. I think we could consider creating a specific endpoint for that so only one request is needed, but that could be implemented in a follow-up not blocking this one.

Would you like to take a second look?

**Comment by LevinMedia** [comment]
>@LevinMedia in that case, reviews that are not approved should be sorted on top of approved reviews, even when they are older? Or should they be sorted by date anyway?

for now lets keep them sorted by date. @jameskoster and I were discussing giving users the option to choose between showing all reviews, and only reviews that require specific action, but we'd want to handle that in a different issue / PR if we go that route.

**Comment by jeffstieler** [comment]
> The only issue is we need to perform two different API requests in order to detect if 1) there are new reviews 2) there are 'on hold' reviews. I think we could consider creating a specific endpoint for that so only one request is needed, but that could be implemented in a follow-up not blocking this one.

Rather than introduce another query, what do you think about just issuing the same query as the Reviews panel to get the unread status? Sure, it's more data than needed if the user doesn't open the panel, but it actually saves a request if they do.

See it in action: https://gist.github.com/jeffstieler/30c8b87016492e6f76f26a206ed51fcb

**Comment by Aljullu** [comment]
> Rather than introduce another query, what do you think about just issuing the same query as the Reviews panel to get the unread status? Sure, it's more data than needed if the user doesn't open the panel, but it actually saves a request if they do.

I like your approach but if I understand it correctly, it would not display the unread circle if the 'on hold' review is not in the last 25, right? Do you think that's an edge case we can ignore?

**Comment by jeffstieler** [comment]
> it would not display the unread circle if the 'on hold' review is not in the last 25, right?

Ah - good catch. You're right about that.

> Do you think that's an edge case we can ignore?

Probably not - disregard my suggestion. I'll re-review.

**Comment by Aljullu** [comment]
Hey @jeffstieler, did you have time to take a second look at this? :point_up:

**Review by jeffstieler — APPROVED** [review]
Looks good - 🛳it!

**Pull request merged**
