### PR TITLE
Use static images for nav intro modal

### LINKED ISSUE #6479: Nav intro video does not meet plugin guidelines
**Describe the bug**
A new modal was added in https://github.com/woocommerce/woocommerce-admin/pull/6367 to introduce the Woo Navigation, which includes videos of screen captures (GIFs).

These videos do not meet plugin review guidelines because the GIFs are hosted from woocommerce.com and it raises GDPR concerns.

**Expected behavior**

Videos are hosted from an allowed source: VideoPress, YouTube, Vimeo, or WordPress.TV.

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #6479

Use bundled static images instead of external resources for nav images.

### Screenshots

Screen Shot 2021-03-02 at 3 29 49 PM

### Detailed test instructions:

1. Dismiss the welcome modal if you haven't already.
1. Delete the `woocommerce_navigation_intro_modal_dismissed` if it exists.
2. Navigate to the homepage.
3. Note that the images work as expected and are now derived directly from the bundle instead of WooCommerce.com.

### CODE REVIEW

**Review by psealock — APPROVED** [review]
Thanks @joshuatf, this is working well and the code looks good. Image file sizes are quite small too.

**Review by joelclimbsthings — APPROVED** [review]
Works great! :ship:

**Comment by elizaan36** [comment]
nice one getting this together so fast. I can see how the images are a little pixelated - if we have time we can try to drop these 3 in instead and hopefully that helps! https://share.getcloudapp.com/YEuXJd97

**Comment by joshuatf** [comment]
Thanks, @elizaan36 - updated with the 2x images.

**Comment by psealock** [comment]
I was wondering about the pixelation too. I took this for a spin and it looks much better.

I also see the 2x files are actually smaller than the previous version 👍🏽 

Screen Shot 2021-03-03 at 11 51 24 AM

Good to merge team?

**Pull request merged**
