### PR TITLE
Remove 1 global from main file

### PR DESCRIPTION
**Pull request by szepeviktor**
Just remove 1 unprefixed global variable from main file.

### CODE REVIEW

**Review by adrianduffell — APPROVED** [review]
Thanks @szepeviktor this looks like a wise change to make.

Could you please add this changelog entry under the **Unreleased** heading in readme.txt? It will then be good to merge.

```
Tweak: Refactor autoloader to remove global variable.
```

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by adrianduffell** [comment]
@szepeviktor Sorry, my bad --  could you please also add the PR number to the entry 😓

We've just put in a CI check for this today.

```
Tweak: Refactor autoloader to remove global variable. #6412
```

**Comment by szepeviktor** [comment]
I've done just that.

https://github.com/woocommerce/woocommerce-admin/pull/6412/files#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6R121

**Comment by szepeviktor** [comment]
The `pr-labeler` step fails.

**Comment by adrianduffell** [comment]
> I've done just that.

You're right, thank you! Merging this now.

**Comment by adrianduffell** [comment]
I'm curious if the global was causing you an issue?

**Comment by szepeviktor** [comment]
> I'm curious if the global was causing you an issue?

I hope so :)

**Pull request merged**
