### PR TITLE
Update generic method prefixes to wc_admin_

### LINKED ISSUE #1734: Namespace methods in wc-admin.php
Background: p90Yrv-Ze-p2

In order to have the plugin published in the .org repo, we need to ensure non-class methods are properly namespaced:

```
## Generic function (and/or define) names 

All plugins must have unique function names, namespaces, defines, and classnames. This prevents your plugin from conflicting with other plugins or themes. We need you to update your plugin to use more unique and distinct names.
```

I believe most of the offending function names exist in `wc-admin.php`, so thinking we should standardize on the `wc_admin_` prefix:

## wc-admin.php

Existing Method | New Name
-----------------|------------
`dependencies_satisfied` | `wc_admin_dependencies_satisfied`
`do_wc_admin_daily` | `wc_admin_do_daily_notes`
`activate_wc_admin_plugin` | `wc_admin_activate_plugin`
`possibly_deactivate_wc_admin_plugin` | `wc_admin_possibly_deactivate_plugin`
`deactivate_wc_admin_plugin` | `wc_admin_deactivate_plugin`

## lib/client-assets.php

Existing Method | New Name
-----------------|------------
`format_order_statuses` | `wc_admin_format_order_statuses`

## lib/admin.php

Existing Method | New Name
-----------------|------------
`woocommerce_embed_page_header` | `wc_admin_embed_page_header`

### PR DESCRIPTION
**Pull request by joshuatf**
Fixes #1734 

Updates the generically named functions to be prefixed with `wc_admin_`.

### Detailed test instructions:

1.  Any functions not prefixed with `wc_admin_`?
2.  Plugin still working?

### CODE REVIEW

**Comment by ronakganatra9** [comment]
isn't it the duplicate of #1775 ?

**Comment by joshuatf** [comment]
Hi @ronakganatra9 - sorry, I didn't see an assignee on #1734 and didn't notice you had a PR open for it so I grabbed it.  Nice work on that!

I'll close this PR and we can merge in #1775 if you can get that rebased (looks like it still needs to be rebased from master).

**Comment by ronakganatra9** [comment]
Hello Joshua,

I have already applied to rebase. Let me know if I need to do anything more.

Let me know your thoughts on the same.

**Comment by psealock** [comment]
Closing for now. We can re-open if need be

**Pull request closed without merging**
