### PR TITLE
Add filter variation to tracks data in products analytics

### LINKED ISSUE #6221: wcadmin_analytics_filter Tracking event is blind to variation filter changes.
**Describe the bug**
I'm not sure if it's a bug or a desired behavior.

When I change the product variation filter value, the recorded event contains always:
```
{report: "products", filter: "single_product"}
```
even though I change the value to `"all", "compare"` for variations.

While recording at https://github.com/woocommerce/woocommerce-admin/blob/main/client/analytics/components/report-filters/index.js the value of the variations filter is completely disregarded.

Is that the desired behavior?

**To Reproduce**

1. Go to 'http://localhost/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Fproducts'
2. Open browser console
3. Execute `localStorage.setItem( 'debug', 'wc-admin*' );` to make  tracking easier to inspect
3. Pick "Single product" and variable product
4. Change the value of the variation filter.

**Expected behavior**
I guess the respective values of the changed filter should be tracked.

**Actual behavior**
`{report: "products", filter: "single_product"}` is recorded for `"all", "compare", "select_variation"`

**Screenshots**
Animation of reproduction steps, with visible event logging in the console.

**Additional context**
I'm asking, as I'm about to implement similar tracking in another plugin, and would like to keep it consistent.

### PR DESCRIPTION
**Pull request by becdetat**
Fixes #6221

The filter variation type (`single_variation` or `compare-variations`) is missing from the recorded tracks event. This PR adds it as `filter_variation`.

### Detailed test instructions:

- Have a product with several variations
- Open Analytics -> Products
- Show "SIngle product" and select your variable product
- In the console there should be an event like this: `{report: "products", filter: "single_product", filter_variation: "all"}`
- Select "Single variation" and select a variation
- In the console there should be an event like this: `{report: "products", filter: "single_product", filter_variation: "single_variation"}`
- Select "Comparison"
- In the console there should be an event like this: `{report: "products", filter: "single_product", filter_variation: "compare-variations"}`

### CODE REVIEW

**Review by ilyasfoo — CHANGES_REQUESTED** [review]
According to the original issue, we'd need to track `all_variations` too. Seeing that we don't have the value actually in `data`, maybe we can assume it somehow?

Also, is it a concern to have the default value of `filter_variation` be `undefined`? I'm getting this with single product filter without a variation product.

**Comment by becdetat** [comment]
@ilyasfoo good catch. I'll handle `all_variations`. I don't think having `filter_variation` `undefined` by default is an issue but I'll try to skip it if it isn't required.

**Comment by becdetat** [comment]
This now:
- only adds `filter_variations` if the single product filter is selected
- defaults to 'all' if the filter variation isn't set (which is the case for the 'all variations' filter)

**Review by ilyasfoo — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
