### PR TITLE
Fix CurrencyFactory constructor to use proper function

### LINKED ISSUE #7260: Currency package build causing unintended breaking changes
**Describe the bug**
The built module of `@woocommerce/currency` on the latest `main` and `2.4.0-rc2` breaks existing package consumers (namely WooCommerce Payments). 

In `2.3.1`, the built module `dist/currency/index.js` had the factory set as a proper function:
```js
var CurrencyFactory = function CurrencyFactory(currencySetting) {...}
```

Building using our current `main` however, produces code that uses the arrow function:
```js
const CurrencyFactory = currencySetting => {...}
```

An arrow function [could not be used as a constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), causing fatal errors in WCPay at least in [here](https://github.com/Automattic/woocommerce-payments/blob/47ea0a9bdd31b91bb831f267fe5a7c243531fec9/client/utils/currency/index.js#L48).

**To Reproduce**

1. Checkout the latest main, run `npm run clean && npm start` to make sure a clean build.
1. If you already have WCPay set up and connected, you can try to go to Overview or Transactions page to observe the error when it tries to get currency. Otherwise, you can try to add the following code wherever in your local repository:
```js
import Currency from '@woocommerce/currency';
var test = new Currency( currency );
```
3. Observe error along the lines of `You would get Uncaught TypeError: Currency is not a constructor`.

**Screenshots**

image

**Expected behavior**
No error.

### PR DESCRIPTION
**Pull request by ilyasfoo**
Fixes #7260 

Change CurrencyFactory constructor to use a proper function instead of an arrow function to guarantee the build won't be producing an arrow function for a constructor.

### Detailed test instructions:

1.  Run `npm run clean && npm start` to make sure a clean build.
1.  Open up the built `dist/currency/index.js` file.
2. Search for the `CurrencyFactory` constructor and make sure it's not an arrow function.

### CODE REVIEW

**Comment by psealock** [comment]
This wasn't intended to be a class instantiated by `new`, so I think the usage in WC Pay is wrong. In wc-admin, its used as a function returning an object, not a class.

```js
import { CURRENCY } from '@woocommerce/wc-admin-settings';

const appCurrency = CurrencyFactory( CURRENCY );
```

**Comment by psealock** [comment]
I suppose this solution doesn't hurt anything, but further unintended consequences could appear if the implementation isn't fixed alongside this.

**Comment by samueljseay** [comment]
@psealock not to pick apart the OG implementation but I find the design of it quite unusual, it feels like for most purposes its behaving exactly like a class or at least the pseudo classes people used to write in the JS of yore 😛 especially since it holds a currency in state via a variable.

Maybe we should just convert this to a class or otherwise redesign it to be a set of idempotent functions in future. Unfortunately that's probably out of scope here but I can see why consumers expected to use a constructor so I'd say at the very least the API is confusing.

**Comment by ilyasfoo** [comment]
Thanks for chiming in @psealock @samueljseay! A thing that I cant seem to figure out is why our build changed out of nowhere. Is it something to do with the updated `@wordpress/babel-preset-default` 🤔 

Anyway, would be great if this gets ✅  soon, as it needs to be included in the release for WooCommerce 5.5 RC 🙇

**Review by samueljseay — APPROVED** [review]
As Paul mentioned the change is low risk, I don't see any references to `this` internally. 🚀

**Review by psealock — APPROVED** [review]
@samueljseay is correct in that the implementation resembles a class, and since thats the case a refactor is probably in order. In the meantime, this change is 👍🏽

**Pull request merged**
