### PR TITLE
Fix: date params were no longer persisted when navigating pages

### PR DESCRIPTION
**Pull request by Aljullu**
When trying to reproduce #663, I noticed date params persistence was broken in master. This PR should fix that (some changes to the selector that highlights the links was required too).

### Detailed test instructions:

- Go to any page of `wc-admin`.
- Change the time range and verify the links are still correctly highlighted.
- Navigate to another page and verify the time range persisted and links are correctly highlighted too.

cc @belcherj you did some modifications to that part of the code recently, so you might want to take a look and make sure I'm not breaking anything new :slightly_smiling_face:

### CODE REVIEW

**Comment by ryelle** [comment]
I'm not sure if I'm reading the problem correctly– we want the selected date range to persist between different reports? So if I'm on the Revenue report, and I pick "last year", then go to the Products report, it should stay "last year"?

**Comment by Aljullu** [comment]
@ryelle Exactly, that was implemented in #568, but it got broken recently when we did some changes in the menu.

Getting in some more detail, I found that [this selector](https://github.com/woocommerce/wc-admin/pull/717/files#diff-5c8a66f908738b94586c976c499edfe5R73) which updates the navigation menu URLs stopped working for links under _Analytics_ because their `wpOpenMenu` id was `toplevel_page_wc-admin--analytics` but the id of the menu element was `toplevel_page_wc-admin--analytics-revenue`, so they were never selected and therefore never updated with the time parameters.

**Comment by allendav** [comment]
I see .current correctly moving from item to item under the Analytics menu as I use the browser's forward and back buttons, but I don't understand how this PR fixes the date params. Can you explain?

**Review by allendav — APPROVED** [review]
Tests well for me!

**Comment by Aljullu** [comment]
> Nevermind - I see it now - needed to expand the li to see the a to see the href change in dev tools.

Exactly! It works changing the `href` of the links.

**Pull request merged**
