### PR TITLE
Copy the snackbar component from Gutenberg into wp-admin

### PR DESCRIPTION
**Pull request by becdetat**
_EDIT: I needed to copy the `core/notices` data source (which is where `createNotice` lives), because the entire options object isn't passed down to the snackbar component meaning that each new option needed for the CES feature will have to be implemented in `core/notices` as well._

This copies the [`SnackbarList`](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/snackbar/list.js) and [`Snackbar`](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/snackbar/index.js) components in from Gutenberg, as well as the `core/notices` data source (renamed to `core/notices2`) from the `@wordpress/notices` package. This is so we can iterate over the snackbar designs in the Customer Effort Score feature without being blocked by a Gutenberg release.

NOTE: When the changes to the snackbar are pushed upstream to Gutenberg and released, the components and data source can be removed.

### Detailed test instructions:

Follow the test instructions in this PR #5406, and make sure the snackbar works as expected.

### Changelog Note:

Dev: Copy the snackbar component and core/notices from Gutenberg into WordPress Admin

### CODE REVIEW

**Review by mattsherman — APPROVED** [review]
Still works as expected!

**Comment by becdetat** [comment]
@mattsherman Thanks! Turned out I needed to pull in the `core/notices` data source in as well, as all of the modifications to the snackbar also need to be reflected in the data source. Can you retest this please?

**Review by mattsherman — APPROVED** [review]
Change works as expected.

We should make sure that we have a specific plan for moving our improvements back upstream to Gutenberg so that our local copy doesn't linger for longer than necessary.

**Comment by becdetat** [comment]
> We should make sure that we have a specific plan for moving our improvements back upstream to Gutenberg so that our local copy doesn't linger for longer than necessary.

Great point. I've got a plan in my mind but I'll get it out into a P2 post tomorrow.

**Pull request merged**
